#!/usr/bin/env bash
# Copyright (c) 2024, NVIDIA CORPORATION.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# THIS FILE IS AUTOMATICALLY GENERATED BY _1_create_git_clone.py
mkdir -p repos
if [ ! -d repos/Applied-Data-Science-with-Python-Specialization ]; then git clone --depth 1 https://github.com/yonycherkos/Applied-Data-Science-with-Python-Specialization.git repos/Applied-Data-Science-with-Python-Specialization ; fi
echo Applied-Data-Science-with-Python-Specialization > repos/Applied-Data-Science-with-Python-Specialization/_conda_forge_name
if [ ! -d repos/FirstCourseNetworkScience ]; then git clone --depth 1 https://github.com/CambridgeUniversityPress/FirstCourseNetworkScience.git repos/FirstCourseNetworkScience ; fi
echo FirstCourseNetworkScience > repos/FirstCourseNetworkScience/_conda_forge_name
if [ ! -d repos/GML2023 ]; then git clone --depth 1 https://github.com/xbresson/GML2023.git repos/GML2023 ; fi
echo GML2023 > repos/GML2023/_conda_forge_name
if [ ! -d repos/Graph-Analysis-with-NetworkX ]; then git clone --depth 1 https://github.com/KangboLu/Graph-Analysis-with-NetworkX.git repos/Graph-Analysis-with-NetworkX ; fi
echo Graph-Analysis-with-NetworkX > repos/Graph-Analysis-with-NetworkX/_conda_forge_name
if [ ! -d repos/Network-Analysis-Made-Simple ]; then git clone --depth 1 https://github.com/ericmjl/Network-Analysis-Made-Simple.git repos/Network-Analysis-Made-Simple ; fi
echo Network-Analysis-Made-Simple > repos/Network-Analysis-Made-Simple/_conda_forge_name
if [ ! -d repos/Network-Science-with-Python ]; then git clone --depth 1 https://github.com/PacktPublishing/Network-Science-with-Python.git repos/Network-Science-with-Python ; fi
echo Network-Science-with-Python > repos/Network-Science-with-Python/_conda_forge_name
if [ ! -d repos/activity-browser ]; then git clone --depth 1 https://github.com/LCA-ActivityBrowser/activity-browser.git repos/activity-browser ; fi
echo activity-browser > repos/activity-browser/_conda_forge_name
if [ ! -d repos/aimodelshare ]; then git clone --depth 1 https://github.com/AIModelShare/aimodelshare.git repos/aimodelshare ; fi
echo aimodelshare > repos/aimodelshare/_pypi_name
echo aimodelshare > repos/aimodelshare/_conda_forge_name
if [ ! -d repos/ale ]; then git clone --depth 1 https://github.com/DOI-USGS/ale.git repos/ale ; fi
echo ale > repos/ale/_conda_forge_name
if [ ! -d repos/amazon-braket-sdk ]; then git clone --depth 1 https://github.com/aws/amazon-braket-sdk-python.git repos/amazon-braket-sdk ; fi
echo amazon-braket-sdk > repos/amazon-braket-sdk/_pypi_name
echo amazon-braket-sdk > repos/amazon-braket-sdk/_conda_forge_name
if [ ! -d repos/arsenic ]; then git clone --depth 1 https://github.com/OpenFreeEnergy/arsenic.git repos/arsenic ; fi
echo arsenic > repos/arsenic/_conda_forge_name
if [ ! -d repos/asimov ]; then git clone --depth 1 https://git.ligo.org/asimov/asimov.git repos/asimov ; fi
echo asimov > repos/asimov/_pypi_name
echo asimov > repos/asimov/_conda_forge_name
if [ ! -d repos/autode ]; then git clone --depth 1 https://github.com/duartegroup/autodE.git repos/autode ; fi
echo autode > repos/autode/_conda_forge_name
if [ ! -d repos/autogluon.core ]; then git clone --depth 1 https://github.com/autogluon/autogluon.git repos/autogluon.core ; fi
echo autogluon.core > repos/autogluon.core/_pypi_name
echo autogluon.core > repos/autogluon.core/_conda_forge_name
if [ ! -d repos/autogluon.tabular ]; then git clone --depth 1 https://github.com/autogluon/autogluon.git repos/autogluon.tabular ; fi
echo autogluon.tabular > repos/autogluon.tabular/_pypi_name
echo autogluon.tabular > repos/autogluon.tabular/_conda_forge_name
if [ ! -d repos/autogluon.timeseries ]; then git clone --depth 1 https://github.com/autogluon/autogluon.git repos/autogluon.timeseries ; fi
echo autogluon.timeseries > repos/autogluon.timeseries/_pypi_name
echo autogluon.timeseries > repos/autogluon.timeseries/_conda_forge_name
if [ ! -d repos/basictools ]; then git clone --depth 1 https://gitlab.com/DRTI/basic-tools.git repos/basictools ; fi
echo basictools > repos/basictools/_conda_forge_name
if [ ! -d repos/betse ]; then git clone --depth 1 https://github.com/betsee/betse.git repos/betse ; fi
echo betse > repos/betse/_pypi_name
echo betse > repos/betse/_conda_forge_name
if [ ! -d repos/biotite ]; then git clone --depth 1 https://github.com/biotite-dev/biotite.git repos/biotite ; fi
echo biotite > repos/biotite/_conda_forge_name
if [ ! -d repos/blackboxauditing ]; then git clone --depth 1 https://github.com/algofairness/BlackBoxAuditing.git repos/blackboxauditing ; fi
echo blackboxauditing > repos/blackboxauditing/_pypi_name
echo blackboxauditing > repos/blackboxauditing/_conda_forge_name
if [ ! -d repos/blueqat ]; then git clone --depth 1 https://github.com/Blueqat/Blueqat.git repos/blueqat ; fi
echo blueqat > repos/blueqat/_pypi_name
echo blueqat > repos/blueqat/_conda_forge_name
if [ ! -d repos/bmorph ]; then git clone --depth 1 https://github.com/UW-Hydro/bmorph.git repos/bmorph ; fi
echo bmorph > repos/bmorph/_conda_forge_name
if [ ! -d repos/campo ]; then git clone --depth 1 https://github.com/computationalgeography/campo.git repos/campo ; fi
echo campo > repos/campo/_conda_forge_name
if [ ! -d repos/catalystcoop.pudl ]; then git clone --depth 1 https://github.com/catalyst-cooperative/pudl.git repos/catalystcoop.pudl ; fi
echo catalystcoop-pudl > repos/catalystcoop.pudl/_pypi_name
echo catalystcoop.pudl > repos/catalystcoop.pudl/_conda_forge_name
if [ ! -d repos/catlearn ]; then git clone --depth 1 https://github.com/SUNCAT-Center/CatLearn.git repos/catlearn ; fi
echo catlearn > repos/catlearn/_pypi_name
echo catlearn > repos/catlearn/_conda_forge_name
if [ ! -d repos/causal-learn ]; then git clone --depth 1 https://github.com/py-why/causal-learn.git repos/causal-learn ; fi
echo causal-learn > repos/causal-learn/_pypi_name
echo causal-learn > repos/causal-learn/_conda_forge_name
if [ ! -d repos/causalnex ]; then git clone --depth 1 https://github.com/quantumblacklabs/causalnex.git repos/causalnex ; fi
echo causalnex > repos/causalnex/_pypi_name
echo causalnex > repos/causalnex/_conda_forge_name
if [ ! -d repos/cctk ]; then git clone --depth 1 https://github.com/ekwan/cctk.git repos/cctk ; fi
echo cctk > repos/cctk/_pypi_name
echo cctk > repos/cctk/_conda_forge_name
if [ ! -d repos/cdt ]; then git clone --depth 1 https://github.com/FenTechSolutions/CausalDiscoveryToolbox.git repos/cdt ; fi
echo cdt > repos/cdt/_pypi_name
echo cdt > repos/cdt/_conda_forge_name
if [ ! -d repos/cellrank ]; then git clone --depth 1 https://github.com/theislab/cellrank.git repos/cellrank ; fi
echo cellrank > repos/cellrank/_pypi_name
echo cellrank > repos/cellrank/_conda_forge_name
if [ ! -d repos/checkov ]; then git clone --depth 1 https://github.com/bridgecrewio/checkov.git repos/checkov ; fi
echo checkov > repos/checkov/_pypi_name
echo checkov > repos/checkov/_conda_forge_name
if [ ! -d repos/chemper ]; then git clone --depth 1 https://github.com/mobleylab/chemper.git repos/chemper ; fi
echo chemper > repos/chemper/_conda_forge_name
if [ ! -d repos/chinese-whispers ]; then git clone --depth 1 https://github.com/nlpub/chinese-whispers-python.git repos/chinese-whispers ; fi
echo chinese-whispers > repos/chinese-whispers/_pypi_name
echo chinese-whispers > repos/chinese-whispers/_conda_forge_name
if [ ! -d repos/chunky3d ]; then git clone --depth 1 https://github.com/K3D-tools/chunky3d.git repos/chunky3d ; fi
echo chunky3d > repos/chunky3d/_pypi_name
echo chunky3d > repos/chunky3d/_conda_forge_name
if [ ! -d repos/cinnabar ]; then git clone --depth 1 https://github.com/OpenFreeEnergy/cinnabar.git repos/cinnabar ; fi
echo cinnabar > repos/cinnabar/_conda_forge_name
if [ ! -d repos/circuitq ]; then git clone --depth 1 https://github.com/PhilippAumann/circuitq.git repos/circuitq ; fi
echo circuitq > repos/circuitq/_pypi_name
echo circuitq > repos/circuitq/_conda_forge_name
if [ ! -d repos/cirq ]; then git clone --depth 1 https://github.com/quantumlib/Cirq.git repos/cirq ; fi
echo cirq > repos/cirq/_conda_forge_name
if [ ! -d repos/cnmfsns ]; then git clone --depth 1 https://github.com/MorrissyLab/cNMF-SNS.git repos/cnmfsns ; fi
echo cnmfsns > repos/cnmfsns/_pypi_name
echo cnmfsns > repos/cnmfsns/_conda_forge_name
if [ ! -d repos/cogdl ]; then git clone --depth 1 https://github.com/THUDM/cogdl.git repos/cogdl ; fi
echo cogdl > repos/cogdl/_conda_forge_name
if [ ! -d repos/compas ]; then git clone --depth 1 https://github.com/compas-dev/compas.git repos/compas ; fi
echo COMPAS > repos/compas/_pypi_name
echo compas > repos/compas/_conda_forge_name
if [ ! -d repos/compas_slicer ]; then git clone --depth 1 https://github.com/compas-dev/compas_slicer.git repos/compas_slicer ; fi
echo compas-slicer > repos/compas_slicer/_pypi_name
echo compas_slicer > repos/compas_slicer/_conda_forge_name
if [ ! -d repos/conda-replicate ]; then git clone --depth 1 https://github.com/cswartzvi/conda-replicate.git repos/conda-replicate ; fi
echo conda-replicate > repos/conda-replicate/_conda_forge_name
if [ ! -d repos/covalent ]; then git clone --depth 1 https://github.com/AgnostiqHQ/covalent.git repos/covalent ; fi
echo covalent > repos/covalent/_pypi_name
echo covalent > repos/covalent/_conda_forge_name
if [ ! -d repos/ctrl-benchmark ]; then git clone --depth 1 https://github.com/facebookresearch/CTrLBenchmark.git repos/ctrl-benchmark ; fi
echo ctrl-benchmark > repos/ctrl-benchmark/_pypi_name
echo ctrl-benchmark > repos/ctrl-benchmark/_conda_forge_name
if [ ! -d repos/cubed ]; then git clone --depth 1 https://github.com/tomwhite/cubed.git repos/cubed ; fi
echo cubed > repos/cubed/_pypi_name
echo cubed > repos/cubed/_conda_forge_name
if [ ! -d repos/curviriver ]; then git clone --depth 1 https://github.com/cheginit/curviriver.git repos/curviriver ; fi
echo curviriver > repos/curviriver/_pypi_name
echo curviriver > repos/curviriver/_conda_forge_name
if [ ! -d repos/dace ]; then git clone --depth 1 https://github.com/spcl/dace.git repos/dace ; fi
echo dace > repos/dace/_pypi_name
echo dace > repos/dace/_conda_forge_name
if [ ! -d repos/dags ]; then git clone --depth 1 https://github.com/OpenSourceEconomics/dags.git repos/dags ; fi
echo dags > repos/dags/_pypi_name
echo dags > repos/dags/_conda_forge_name
if [ ! -d repos/dantro ]; then git clone --depth 1 https://gitlab.com/utopia-project/dantro.git repos/dantro ; fi
echo dantro > repos/dantro/_pypi_name
echo dantro > repos/dantro/_conda_forge_name
if [ ! -d repos/datajoint ]; then git clone --depth 1 https://github.com/datajoint/datajoint-python.git repos/datajoint ; fi
echo datajoint > repos/datajoint/_pypi_name
echo datajoint > repos/datajoint/_conda_forge_name
if [ ! -d repos/dataprofiler ]; then git clone --depth 1 https://github.com/capitalone/data-profiler.git repos/dataprofiler ; fi
echo DataProfiler > repos/dataprofiler/_pypi_name
echo dataprofiler > repos/dataprofiler/_conda_forge_name
if [ ! -d repos/datatoolbox ]; then git clone --depth 1 https://gitlab.com/climateanalytics/datatoolbox.git repos/datatoolbox ; fi
echo datatoolbox > repos/datatoolbox/_pypi_name
echo datatoolbox > repos/datatoolbox/_conda_forge_name
if [ ! -d repos/dbt ]; then git clone --depth 1 https://github.com/dbt-labs/dbt.git repos/dbt ; fi
echo dbt-core > repos/dbt/_pypi_name
echo dbt > repos/dbt/_conda_forge_name
if [ ! -d repos/deduplipy ]; then git clone --depth 1 https://github.com/fritshermans/deduplipy.git repos/deduplipy ; fi
echo deduplipy > repos/deduplipy/_pypi_name
echo deduplipy > repos/deduplipy/_conda_forge_name
if [ ! -d repos/deeplabcut ]; then git clone --depth 1 https://github.com/DeepLabCut/DeepLabCut.git repos/deeplabcut ; fi
echo deeplabcut > repos/deeplabcut/_pypi_name
echo deeplabcut > repos/deeplabcut/_conda_forge_name
if [ ! -d repos/deeprobust ]; then git clone --depth 1 https://github.com/DSE-MSU/DeepRobust.git repos/deeprobust ; fi
echo deeprobust > repos/deeprobust/_pypi_name
echo deeprobust > repos/deeprobust/_conda_forge_name
if [ ! -d repos/dgl ]; then git clone --depth 1 https://github.com/dmlc/dgl.git repos/dgl ; fi
echo dgl > repos/dgl/_conda_forge_name
if [ ! -d repos/dit ]; then git clone --depth 1 https://github.com/dit/dit.git repos/dit ; fi
echo dit > repos/dit/_pypi_name
echo dit > repos/dit/_conda_forge_name
if [ ! -d repos/dmf-chip ]; then git clone --depth 1 https://github.com/sci-bots/dmf-chip.git repos/dmf-chip ; fi
echo dmf-chip > repos/dmf-chip/_conda_forge_name
if [ ! -d repos/dmff ]; then git clone --depth 1 https://github.com/deepmodeling/DMFF.git repos/dmff ; fi
echo dmff > repos/dmff/_conda_forge_name
if [ ! -d repos/dowhy ]; then git clone --depth 1 https://github.com/microsoft/dowhy.git repos/dowhy ; fi
echo dowhy > repos/dowhy/_pypi_name
echo dowhy > repos/dowhy/_conda_forge_name
if [ ! -d repos/dtale ]; then git clone --depth 1 https://github.com/man-group/dtale.git repos/dtale ; fi
echo dtale > repos/dtale/_pypi_name
echo dtale > repos/dtale/_conda_forge_name
if [ ! -d repos/dtool_ibeis ]; then git clone --depth 1 https://github.com/Erotemic/dtool_ibeis.git repos/dtool_ibeis ; fi
echo dtool-ibeis > repos/dtool_ibeis/_pypi_name
echo dtool_ibeis > repos/dtool_ibeis/_conda_forge_name
if [ ! -d repos/dvc ]; then git clone --depth 1 https://github.com/iterative/dvc.git repos/dvc ; fi
echo dvc > repos/dvc/_pypi_name
echo dvc > repos/dvc/_conda_forge_name
if [ ! -d repos/dwave-hybrid ]; then git clone --depth 1 https://github.com/dwavesystems/dwave-hybrid.git repos/dwave-hybrid ; fi
echo dwave-hybrid > repos/dwave-hybrid/_pypi_name
echo dwave-hybrid > repos/dwave-hybrid/_conda_forge_name
if [ ! -d repos/dwave-networkx ]; then git clone --depth 1 https://github.com/dwavesystems/dwave_networkx.git repos/dwave-networkx ; fi
echo dwave-networkx > repos/dwave-networkx/_pypi_name
echo dwave-networkx > repos/dwave-networkx/_conda_forge_name
if [ ! -d repos/dwave-samplers ]; then git clone --depth 1 https://github.com/dwavesystems/dwave-samplers.git repos/dwave-samplers ; fi
echo dwave-samplers > repos/dwave-samplers/_conda_forge_name
if [ ! -d repos/dwavebinarycsp ]; then git clone --depth 1 https://github.com/dwavesystems/dwavebinarycsp.git repos/dwavebinarycsp ; fi
echo dwavebinarycsp > repos/dwavebinarycsp/_pypi_name
echo dwavebinarycsp > repos/dwavebinarycsp/_conda_forge_name
if [ ! -d repos/dynamo-release ]; then git clone --depth 1 https://github.com/aristoteleo/dynamo-release.git repos/dynamo-release ; fi
echo dynamo-release > repos/dynamo-release/_conda_forge_name
if [ ! -d repos/dyntapy ]; then git clone --depth 1 https://gitlab.kuleuven.be/ITSCreaLab/public-toolboxes/dyntapy.git repos/dyntapy ; fi
echo dyntapy > repos/dyntapy/_pypi_name
echo dyntapy > repos/dyntapy/_conda_forge_name
if [ ! -d repos/ebg ]; then git clone --depth 1 https://github.com/wiegertj/EBG.git repos/ebg ; fi
echo ebg > repos/ebg/_pypi_name
echo ebg > repos/ebg/_conda_forge_name
if [ ! -d repos/econci ]; then git clone --depth 1 https://github.com/phcsoares/econci.git repos/econci ; fi
echo econci > repos/econci/_pypi_name
echo econci > repos/econci/_conda_forge_name
if [ ! -d repos/eden-kernel ]; then git clone --depth 1 https://github.com/fabriziocosta/EDeN.git repos/eden-kernel ; fi
echo eden-kernel > repos/eden-kernel/_pypi_name
echo eden-kernel > repos/eden-kernel/_conda_forge_name
if [ ! -d repos/elfi ]; then git clone --depth 1 https://github.com/elfi-dev/elfi.git repos/elfi ; fi
echo elfi > repos/elfi/_conda_forge_name
if [ ! -d repos/elyra ]; then git clone --depth 1 https://github.com/elyra-ai/elyra.git repos/elyra ; fi
echo elyra > repos/elyra/_pypi_name
echo elyra > repos/elyra/_conda_forge_name
if [ ! -d repos/elyra-server ]; then git clone --depth 1 https://github.com/elyra-ai/elyra.git repos/elyra-server ; fi
echo elyra-server > repos/elyra-server/_pypi_name
echo elyra-server > repos/elyra-server/_conda_forge_name
if [ ! -d repos/evalml-core ]; then git clone --depth 1 https://github.com/alteryx/evalml.git repos/evalml-core ; fi
echo evalml > repos/evalml-core/_pypi_name
echo evalml-core > repos/evalml-core/_conda_forge_name
if [ ! -d repos/featurewiz ]; then git clone --depth 1 https://github.com/AutoViML/featurewiz.git repos/featurewiz ; fi
echo featurewiz > repos/featurewiz/_pypi_name
echo featurewiz > repos/featurewiz/_conda_forge_name
if [ ! -d repos/finesse ]; then git clone --depth 1 https://git.ligo.org/finesse/finesse3.git repos/finesse ; fi
echo finesse > repos/finesse/_pypi_name
echo finesse > repos/finesse/_conda_forge_name
if [ ! -d repos/flo ]; then git clone --depth 1 https://github.com/deanmalmgren/flo.git repos/flo ; fi
echo flo > repos/flo/_pypi_name
echo flo > repos/flo/_conda_forge_name
if [ ! -d repos/floweaver ]; then git clone --depth 1 https://github.com/ricklupton/floweaver.git repos/floweaver ; fi
echo floweaver > repos/floweaver/_pypi_name
echo floweaver > repos/floweaver/_conda_forge_name
if [ ! -d repos/forcebalance ]; then git clone --depth 1 https://github.com/leeping/forcebalance.git repos/forcebalance ; fi
echo forcebalance > repos/forcebalance/_conda_forge_name
if [ ! -d repos/foyer ]; then git clone --depth 1 https://github.com/mosdef-hub/foyer.git repos/foyer ; fi
echo foyer > repos/foyer/_conda_forge_name
if [ ! -d repos/gdpx ]; then git clone --depth 1 https://github.com/hsulab/GDPy.git repos/gdpx ; fi
echo gdpx > repos/gdpx/_conda_forge_name
if [ ! -d repos/gemseo ]; then git clone --depth 1 https://gitlab.com/gemseo/dev/gemseo.git repos/gemseo ; fi
echo gemseo > repos/gemseo/_pypi_name
echo gemseo > repos/gemseo/_conda_forge_name
if [ ! -d repos/geograph ]; then git clone --depth 1 https://github.com/ai4er-cdt/geograph.git repos/geograph ; fi
echo geograph > repos/geograph/_pypi_name
echo geograph > repos/geograph/_conda_forge_name
if [ ! -d repos/geometric ]; then git clone --depth 1 https://github.com/leeping/geomeTRIC.git repos/geometric ; fi
echo geometric > repos/geometric/_conda_forge_name
if [ ! -d repos/gerrychain ]; then git clone --depth 1 https://github.com/mggg/GerryChain.git repos/gerrychain ; fi
echo gerrychain > repos/gerrychain/_pypi_name
echo gerrychain > repos/gerrychain/_conda_forge_name
if [ ! -d repos/gettsim ]; then git clone --depth 1 https://github.com/iza-institute-of-labor-economics/gettsim.git repos/gettsim ; fi
echo gettsim > repos/gettsim/_pypi_name
echo gettsim > repos/gettsim/_conda_forge_name
if [ ! -d repos/gglasso ]; then git clone --depth 1 https://github.com/fabian-sp/GGLasso.git repos/gglasso ; fi
echo gglasso > repos/gglasso/_pypi_name
echo gglasso > repos/gglasso/_conda_forge_name
if [ ! -d repos/gmso ]; then git clone --depth 1 https://github.com/mosdef-hub/gmso.git repos/gmso ; fi
echo gmso > repos/gmso/_conda_forge_name
if [ ! -d repos/gotran ]; then git clone --depth 1 https://github.com/ComputationalPhysiology/gotran.git repos/gotran ; fi
echo gotran > repos/gotran/_pypi_name
echo gotran > repos/gotran/_conda_forge_name
if [ ! -d repos/grapharray ]; then git clone --depth 1 https://github.com/Geb-algebra/grapharray.git repos/grapharray ; fi
echo grapharray > repos/grapharray/_pypi_name
echo grapharray > repos/grapharray/_conda_forge_name
if [ ! -d repos/graphml-class ]; then git clone --depth 1 https://github.com/Graphlet-AI/graphml-class.git repos/graphml-class ; fi
echo graphml-class > repos/graphml-class/_conda_forge_name
if [ ! -d repos/graphpro ]; then git clone --depth 1 https://github.com/pegerto/graphpro.git repos/graphpro ; fi
echo graphpro > repos/graphpro/_pypi_name
echo graphpro > repos/graphpro/_conda_forge_name
if [ ! -d repos/graspy ]; then git clone --depth 1 https://github.com/neurodata/graspy.git repos/graspy ; fi
echo graspy > repos/graspy/_conda_forge_name
if [ ! -d repos/grave ]; then git clone --depth 1 https://github.com/networkx/grave.git repos/grave ; fi
echo grave > repos/grave/_conda_forge_name
if [ ! -d repos/greedy ]; then git clone --depth 1 https://github.com/martinfleis/greedy.git repos/greedy ; fi
echo greedy > repos/greedy/_pypi_name
echo greedy > repos/greedy/_conda_forge_name
if [ ! -d repos/griottes ]; then git clone --depth 1 https://github.com/BaroudLab/Griottes.git repos/griottes ; fi
echo griottes > repos/griottes/_pypi_name
echo griottes > repos/griottes/_conda_forge_name
if [ ! -d repos/grove ]; then git clone --depth 1 https://github.com/rigetticomputing/grove.git repos/grove ; fi
echo quantum-grove > repos/grove/_pypi_name
echo grove > repos/grove/_conda_forge_name
if [ ! -d repos/gruut ]; then git clone --depth 1 https://github.com/rhasspy/gruut.git repos/gruut ; fi
echo gruut > repos/gruut/_pypi_name
echo gruut > repos/gruut/_conda_forge_name
if [ ! -d repos/gufe ]; then git clone --depth 1 https://github.com/OpenFreeEnergy/gufe.git repos/gufe ; fi
echo gufe > repos/gufe/_conda_forge_name
if [ ! -d repos/gunpowder ]; then git clone --depth 1 https://github.com/funkey/gunpowder.git repos/gunpowder ; fi
echo gunpowder > repos/gunpowder/_pypi_name
echo gunpowder > repos/gunpowder/_conda_forge_name
if [ ! -d repos/haystack-ai ]; then git clone --depth 1 https://github.com/deepset-ai/haystack.git repos/haystack-ai ; fi
echo haystack-ai > repos/haystack-ai/_pypi_name
echo haystack-ai > repos/haystack-ai/_conda_forge_name
if [ ! -d repos/hiclass ]; then git clone --depth 1 https://github.com/scikit-learn-contrib/hiclass.git repos/hiclass ; fi
echo hiclass > repos/hiclass/_pypi_name
echo hiclass > repos/hiclass/_conda_forge_name
if [ ! -d repos/honto ]; then git clone --depth 1 https://github.com/fabio-cumbo/honto.git repos/honto ; fi
echo honto > repos/honto/_pypi_name
echo honto > repos/honto/_conda_forge_name
if [ ! -d repos/htmd-pdb2pqr ]; then git clone --depth 1 https://github.com/tonigi/apbs-pdb2pqr.git repos/htmd-pdb2pqr ; fi
echo htmd-pdb2pqr > repos/htmd-pdb2pqr/_conda_forge_name
if [ ! -d repos/htpolynet ]; then git clone --depth 1 https://github.com/AbramsGroup/HTPolyNet.git repos/htpolynet ; fi
echo htpolynet > repos/htpolynet/_pypi_name
echo htpolynet > repos/htpolynet/_conda_forge_name
if [ ! -d repos/hyperlib ]; then git clone --depth 1 https://github.com/nalexai/hyperbolic.git repos/hyperlib ; fi
echo hyperlib > repos/hyperlib/_pypi_name
echo hyperlib > repos/hyperlib/_conda_forge_name
if [ ! -d repos/hyperopt ]; then git clone --depth 1 https://github.com/hyperopt/hyperopt.git repos/hyperopt ; fi
echo hyperopt > repos/hyperopt/_pypi_name
echo hyperopt > repos/hyperopt/_conda_forge_name
if [ ! -d repos/hypothesis-networkx ]; then git clone --depth 1 https://github.com/pckroon/hypothesis-networkx.git repos/hypothesis-networkx ; fi
echo hypothesis-networkx > repos/hypothesis-networkx/_pypi_name
echo hypothesis-networkx > repos/hypothesis-networkx/_conda_forge_name
if [ ! -d repos/ifermi ]; then git clone --depth 1 https://github.com/fermisurfaces/IFermi.git repos/ifermi ; fi
echo ifermi > repos/ifermi/_pypi_name
echo ifermi > repos/ifermi/_conda_forge_name
if [ ! -d repos/importlab ]; then git clone --depth 1 https://github.com/google/importlab.git repos/importlab ; fi
echo importlab > repos/importlab/_pypi_name
echo importlab > repos/importlab/_conda_forge_name
if [ ! -d repos/inferno ]; then git clone --depth 1 https://github.com/inferno-pytorch/inferno.git repos/inferno ; fi
echo inferno > repos/inferno/_conda_forge_name
if [ ! -d repos/ipart ]; then git clone --depth 1 https://github.com/ihesp/IPART.git repos/ipart ; fi
echo ipart > repos/ipart/_conda_forge_name
if [ ! -d repos/ipyelk ]; then git clone --depth 1 https://github.com/jupyrdf/ipyelk.git repos/ipyelk ; fi
echo ipyelk > repos/ipyelk/_pypi_name
echo ipyelk > repos/ipyelk/_conda_forge_name
if [ ! -d repos/ipyradiant ]; then git clone --depth 1 https://github.com/jupyrdf/ipyradiant.git repos/ipyradiant ; fi
echo ipyradiant > repos/ipyradiant/_pypi_name
echo ipyradiant > repos/ipyradiant/_conda_forge_name
if [ ! -d repos/itpminer ]; then git clone --depth 1 https://github.com/Local-E-Rewards-ML/itpminer.git repos/itpminer ; fi
echo itpminer > repos/itpminer/_pypi_name
echo itpminer > repos/itpminer/_conda_forge_name
if [ ! -d repos/jobflow ]; then git clone --depth 1 https://github.com/materialsproject/jobflow.git repos/jobflow ; fi
echo jobflow > repos/jobflow/_pypi_name
echo jobflow > repos/jobflow/_conda_forge_name
if [ ! -d repos/karateclub ]; then git clone --depth 1 https://github.com/benedekrozemberczki/karateclub.git repos/karateclub ; fi
echo karateclub > repos/karateclub/_pypi_name
echo karateclub > repos/karateclub/_conda_forge_name
if [ ! -d repos/kedro-viz ]; then git clone --depth 1 https://github.com/kedro-org/kedro-viz.git repos/kedro-viz ; fi
echo kedro-viz > repos/kedro-viz/_conda_forge_name
if [ ! -d repos/kinbot ]; then git clone --depth 1 https://github.com/zadorlab/KinBot.git repos/kinbot ; fi
echo kinbot > repos/kinbot/_pypi_name
echo kinbot > repos/kinbot/_conda_forge_name
if [ ! -d repos/kosh ]; then git clone --depth 1 https://github.com/LLNL/kosh.git repos/kosh ; fi
echo kosh > repos/kosh/_conda_forge_name
if [ ! -d repos/lammps-interface ]; then git clone --depth 1 https://github.com/peteboyd/lammps_interface.git repos/lammps-interface ; fi
echo lammps-interface > repos/lammps-interface/_pypi_name
echo lammps-interface > repos/lammps-interface/_conda_forge_name
if [ ! -d repos/laptrack ]; then git clone --depth 1 https://github.com/yfukai/laptrack.git repos/laptrack ; fi
echo laptrack > repos/laptrack/_pypi_name
echo laptrack > repos/laptrack/_conda_forge_name
if [ ! -d repos/larch ]; then git clone --depth 1 https://github.com/jpn--/larch.git repos/larch ; fi
echo larch > repos/larch/_conda_forge_name
if [ ! -d repos/libneuroml ]; then git clone --depth 1 https://github.com/NeuralEnsemble/libNeuroML.git repos/libneuroml ; fi
echo libneuroml > repos/libneuroml/_pypi_name
echo libneuroml > repos/libneuroml/_conda_forge_name
if [ ! -d repos/ligo-asimov ]; then git clone --depth 1 https://git.ligo.org/asimov/asimov.git repos/ligo-asimov ; fi
echo ligo-asimov > repos/ligo-asimov/_pypi_name
echo ligo-asimov > repos/ligo-asimov/_conda_forge_name
if [ ! -d repos/ligo.skymap ]; then git clone --depth 1 https://github.com/lpsinger/ligo.skymap.git repos/ligo.skymap ; fi
echo ligo.skymap > repos/ligo.skymap/_pypi_name
echo ligo.skymap > repos/ligo.skymap/_conda_forge_name
if [ ! -d repos/lineapy ]; then git clone --depth 1 https://github.com/LineaLabs/lineapy.git repos/lineapy ; fi
echo lineapy > repos/lineapy/_pypi_name
echo lineapy > repos/lineapy/_conda_forge_name
if [ ! -d repos/llama-index ]; then git clone --depth 1 https://github.com/run-llama/llama_index.git repos/llama-index ; fi
echo llama-index > repos/llama-index/_pypi_name
echo llama-index > repos/llama-index/_conda_forge_name
if [ ! -d repos/llama-index-core ]; then git clone --depth 1 https://github.com/run-llama/llama_index.git repos/llama-index-core ; fi
echo llama-index-core > repos/llama-index-core/_pypi_name
echo llama-index-core > repos/llama-index-core/_conda_forge_name
if [ ! -d repos/llama-index-legacy ]; then git clone --depth 1 https://github.com/run-llama/llama_index.git repos/llama-index-legacy ; fi
echo llama-index-legacy > repos/llama-index-legacy/_pypi_name
echo llama-index-legacy > repos/llama-index-legacy/_conda_forge_name
if [ ! -d repos/locan ]; then git clone --depth 1 https://github.com/super-resolution/Locan.git repos/locan ; fi
echo locan > repos/locan/_pypi_name
echo locan > repos/locan/_conda_forge_name
if [ ! -d repos/lofo-importance ]; then git clone --depth 1 https://github.com/aerdem4/lofo-importance.git repos/lofo-importance ; fi
echo lofo-importance > repos/lofo-importance/_pypi_name
echo lofo-importance > repos/lofo-importance/_conda_forge_name
if [ ! -d repos/lomap2 ]; then git clone --depth 1 https://github.com/OpenFreeEnergy/Lomap.git repos/lomap2 ; fi
echo lomap2 > repos/lomap2/_conda_forge_name
if [ ! -d repos/manim ]; then git clone --depth 1 https://github.com/ManimCommunity/manim.git repos/manim ; fi
echo manim > repos/manim/_pypi_name
echo manim > repos/manim/_conda_forge_name
if [ ! -d repos/mapclassify ]; then git clone --depth 1 https://github.com/pysal/mapclassify.git repos/mapclassify ; fi
echo mapclassify > repos/mapclassify/_pypi_name
echo mapclassify > repos/mapclassify/_conda_forge_name
if [ ! -d repos/matid ]; then git clone --depth 1 https://github.com/SINGROUP/matid.git repos/matid ; fi
echo matid > repos/matid/_pypi_name
echo matid > repos/matid/_conda_forge_name
if [ ! -d repos/mbuild ]; then git clone --depth 1 https://github.com/mosdef-hub/mbuild.git repos/mbuild ; fi
echo mbuild > repos/mbuild/_conda_forge_name
if [ ! -d repos/mchammer ]; then git clone --depth 1 https://github.com/andrewtarzia/MCHammer.git repos/mchammer ; fi
echo mchammer > repos/mchammer/_pypi_name
echo mchammer > repos/mchammer/_conda_forge_name
if [ ! -d repos/mechwolf ]; then git clone --depth 1 https://github.com/MechWolf/MechWolf.git repos/mechwolf ; fi
echo mechwolf > repos/mechwolf/_pypi_name
echo mechwolf > repos/mechwolf/_conda_forge_name
if [ ! -d repos/medchem ]; then git clone --depth 1 https://github.com/datamol-io/medchem.git repos/medchem ; fi
echo medchem > repos/medchem/_pypi_name
echo medchem > repos/medchem/_conda_forge_name
if [ ! -d repos/mesa ]; then git clone --depth 1 https://github.com/projectmesa/mesa.git repos/mesa ; fi
echo mesa > repos/mesa/_pypi_name
echo mesa > repos/mesa/_conda_forge_name
if [ ! -d repos/metaknowledge ]; then git clone --depth 1 https://github.com/networks-lab/metaknowledge.git repos/metaknowledge ; fi
echo metaknowledge > repos/metaknowledge/_pypi_name
echo metaknowledge > repos/metaknowledge/_conda_forge_name
if [ ! -d repos/mfpymake ]; then git clone --depth 1 https://github.com/modflowpy/pymake.git repos/mfpymake ; fi
echo mfpymake > repos/mfpymake/_pypi_name
echo mfpymake > repos/mfpymake/_conda_forge_name
if [ ! -d repos/minian ]; then git clone --depth 1 https://github.com/DeniseCaiLab/minian.git repos/minian ; fi
echo minian > repos/minian/_conda_forge_name
if [ ! -d repos/minorminer ]; then git clone --depth 1 https://github.com/dwavesystems/minorminer.git repos/minorminer ; fi
echo minorminer > repos/minorminer/_conda_forge_name
if [ ! -d repos/mocpy ]; then git clone --depth 1 https://github.com/cds-astro/mocpy.git repos/mocpy ; fi
echo MOCPy > repos/mocpy/_pypi_name
echo mocpy > repos/mocpy/_conda_forge_name
if [ ! -d repos/modelx ]; then git clone --depth 1 https://github.com/fumitoh/modelx.git repos/modelx ; fi
echo modelx > repos/modelx/_pypi_name
echo modelx > repos/modelx/_conda_forge_name
if [ ! -d repos/mofchecker ]; then git clone --depth 1 https://github.com/kjappelbaum/mofchecker.git repos/mofchecker ; fi
echo mofchecker > repos/mofchecker/_pypi_name
echo mofchecker > repos/mofchecker/_conda_forge_name
if [ ! -d repos/moffragmentor ]; then git clone --depth 1 https://github.com/kjappelbaum/moffragmentor.git repos/moffragmentor ; fi
echo moffragmentor > repos/moffragmentor/_pypi_name
echo moffragmentor > repos/moffragmentor/_conda_forge_name
if [ ! -d repos/moleculekit ]; then git clone --depth 1 https://github.com/Acellera/moleculekit.git repos/moleculekit ; fi
echo moleculekit > repos/moleculekit/_pypi_name
echo moleculekit > repos/moleculekit/_conda_forge_name
if [ ! -d repos/momepy ]; then git clone --depth 1 https://github.com/pysal/momepy.git repos/momepy ; fi
echo momepy > repos/momepy/_pypi_name
echo momepy > repos/momepy/_conda_forge_name
if [ ! -d repos/mordred ]; then git clone --depth 1 https://github.com/mordred-descriptor/mordred.git repos/mordred ; fi
echo mordred > repos/mordred/_pypi_name
echo mordred > repos/mordred/_conda_forge_name
if [ ! -d repos/mordredcommunity ]; then git clone --depth 1 https://github.com/JacksonBurns/mordred-community.git repos/mordredcommunity ; fi
echo mordredcommunity > repos/mordredcommunity/_pypi_name
echo mordredcommunity > repos/mordredcommunity/_conda_forge_name
if [ ! -d repos/mosaicmpi ]; then git clone --depth 1 https://github.com/MorrissyLab/mosaicMPI.git repos/mosaicmpi ; fi
echo mosaicmpi > repos/mosaicmpi/_pypi_name
echo mosaicmpi > repos/mosaicmpi/_conda_forge_name
if [ ! -d repos/moscot ]; then git clone --depth 1 https://github.com/theislab/moscot.git repos/moscot ; fi
echo moscot > repos/moscot/_pypi_name
echo moscot > repos/moscot/_conda_forge_name
if [ ! -d repos/motifcluster ]; then git clone --depth 1 https://github.com/WGUNDERWOOD/motifcluster.git repos/motifcluster ; fi
echo motifcluster > repos/motifcluster/_pypi_name
echo motifcluster > repos/motifcluster/_conda_forge_name
if [ ! -d repos/muscat-split ]; then git clone --depth 1 https://gitlab.com/drti/muscat.git repos/muscat-split ; fi
echo muscat-split > repos/muscat-split/_conda_forge_name
if [ ! -d repos/napari-graph ]; then git clone --depth 1 https://github.com/napari/napari-graph.git repos/napari-graph ; fi
echo napari-graph > repos/napari-graph/_pypi_name
echo napari-graph > repos/napari-graph/_conda_forge_name
if [ ! -d repos/napari-griottes ]; then git clone --depth 1 https://github.com/aaristov/napari-griottes.git repos/napari-griottes ; fi
echo napari-griottes > repos/napari-griottes/_pypi_name
echo napari-griottes > repos/napari-griottes/_conda_forge_name
if [ ! -d repos/napari-workflow-inspector ]; then git clone --depth 1 https://github.com/haesleinhuepf/napari-workflow-inspector.git repos/napari-workflow-inspector ; fi
echo napari-workflow-inspector > repos/napari-workflow-inspector/_pypi_name
echo napari-workflow-inspector > repos/napari-workflow-inspector/_conda_forge_name
if [ ! -d repos/networks-science-course ]; then git clone --depth 1 https://github.com/chatox/networks-science-course.git repos/networks-science-course ; fi
echo networks-science-course > repos/networks-science-course/_conda_forge_name
if [ ! -d repos/networkx-metis ]; then git clone --depth 1 https://github.com/networkx/networkx-metis.git repos/networkx-metis ; fi
echo networkx-metis > repos/networkx-metis/_conda_forge_name
if [ ! -d repos/nipype ]; then git clone --depth 1 https://github.com/nipy/nipype.git repos/nipype ; fi
echo nipype > repos/nipype/_conda_forge_name
if [ ! -d repos/nitime ]; then git clone --depth 1 https://github.com/nipy/nitime.git repos/nitime ; fi
echo nitime > repos/nitime/_pypi_name
echo nitime > repos/nitime/_conda_forge_name
if [ ! -d repos/nncf ]; then git clone --depth 1 https://github.com/openvinotoolkit/nncf.git repos/nncf ; fi
echo nncf > repos/nncf/_pypi_name
echo nncf > repos/nncf/_conda_forge_name
if [ ! -d repos/node2vec ]; then git clone --depth 1 https://github.com/eliorc/node2vec.git repos/node2vec ; fi
echo node2vec > repos/node2vec/_pypi_name
echo node2vec > repos/node2vec/_conda_forge_name
if [ ! -d repos/nxviz ]; then git clone --depth 1 https://github.com/ericmjl/nxviz.git repos/nxviz ; fi
echo nxviz > repos/nxviz/_pypi_name
echo nxviz > repos/nxviz/_conda_forge_name
if [ ! -d repos/odo ]; then git clone --depth 1 https://github.com/blaze/odo.git repos/odo ; fi
echo odo > repos/odo/_conda_forge_name
if [ ! -d repos/omicverse ]; then git clone --depth 1 https://github.com/Starlitnightly/omicverse.git repos/omicverse ; fi
echo omicverse > repos/omicverse/_pypi_name
echo omicverse > repos/omicverse/_conda_forge_name
if [ ! -d repos/openfe ]; then git clone --depth 1 https://github.com/OpenFreeEnergy/openfe.git repos/openfe ; fi
echo openfe > repos/openfe/_conda_forge_name
if [ ! -d repos/openff-qcsubmit ]; then git clone --depth 1 https://github.com/openforcefield/openff-qcsubmit.git repos/openff-qcsubmit ; fi
echo openff-qcsubmit > repos/openff-qcsubmit/_conda_forge_name
if [ ! -d repos/openff-toolkit ]; then git clone --depth 1 https://github.com/openforcefield/openff-toolkit.git repos/openff-toolkit ; fi
echo openff-toolkit > repos/openff-toolkit/_conda_forge_name
if [ ! -d repos/openmdao ]; then git clone --depth 1 https://github.com/OpenMDAO/OpenMDAO.git repos/openmdao ; fi
echo openmdao > repos/openmdao/_pypi_name
echo openmdao > repos/openmdao/_conda_forge_name
if [ ! -d repos/openmetadata-sqllineage ]; then git clone --depth 1 https://github.com/open-metadata/openmetadata-sqllineage.git repos/openmetadata-sqllineage ; fi
echo openmetadata-sqllineage > repos/openmetadata-sqllineage/_pypi_name
echo openmetadata-sqllineage > repos/openmetadata-sqllineage/_conda_forge_name
if [ ! -d repos/openpathsampling ]; then git clone --depth 1 https://github.com/openpathsampling/openpathsampling.git repos/openpathsampling ; fi
echo openpathsampling > repos/openpathsampling/_pypi_name
echo openpathsampling > repos/openpathsampling/_conda_forge_name
if [ ! -d repos/openpnm ]; then git clone --depth 1 https://github.com/PMEAL/OpenPNM.git repos/openpnm ; fi
echo openpnm > repos/openpnm/_pypi_name
echo openpnm > repos/openpnm/_conda_forge_name
if [ ! -d repos/openquake.engine ]; then git clone --depth 1 https://github.com/gem/oq-engine.git repos/openquake.engine ; fi
echo openquake-engine > repos/openquake.engine/_pypi_name
echo openquake.engine > repos/openquake.engine/_conda_forge_name
if [ ! -d repos/ophyd ]; then git clone --depth 1 https://github.com/bluesky/ophyd.git repos/ophyd ; fi
echo ophyd > repos/ophyd/_pypi_name
echo ophyd > repos/ophyd/_conda_forge_name
if [ ! -d repos/orange3 ]; then git clone --depth 1 https://github.com/biolab/orange3.git repos/orange3 ; fi
echo orange3 > repos/orange3/_pypi_name
echo orange3 > repos/orange3/_conda_forge_name
if [ ! -d repos/osmnx ]; then git clone --depth 1 https://github.com/gboeing/osmnx.git repos/osmnx ; fi
echo osmnx > repos/osmnx/_pypi_name
echo osmnx > repos/osmnx/_conda_forge_name
if [ ! -d repos/pandapower ]; then git clone --depth 1 https://github.com/e2nIEE/pandapower.git repos/pandapower ; fi
echo pandapower > repos/pandapower/_pypi_name
echo pandapower > repos/pandapower/_conda_forge_name
if [ ! -d repos/parselglossy ]; then git clone --depth 1 https://github.com/dev-cafe/parselglossy.git repos/parselglossy ; fi
echo parselglossy > repos/parselglossy/_pypi_name
echo parselglossy > repos/parselglossy/_conda_forge_name
if [ ! -d repos/parsl ]; then git clone --depth 1 https://github.com/Parsl/parsl.git repos/parsl ; fi
echo parsl > repos/parsl/_pypi_name
echo parsl > repos/parsl/_conda_forge_name
if [ ! -d repos/penaltymodel ]; then git clone --depth 1 https://github.com/dwavesystems/penaltymodel.git repos/penaltymodel ; fi
echo penaltymodel > repos/penaltymodel/_pypi_name
echo penaltymodel > repos/penaltymodel/_conda_forge_name
if [ ! -d repos/penaltymodel-mip ]; then git clone --depth 1 https://github.com/dwavesystems/penaltymodel.git repos/penaltymodel-mip ; fi
echo penaltymodel-mip > repos/penaltymodel-mip/_pypi_name
echo penaltymodel-mip > repos/penaltymodel-mip/_conda_forge_name
if [ ! -d repos/pennylane ]; then git clone --depth 1 https://github.com/PennyLaneAI/pennylane.git repos/pennylane ; fi
echo pennylane > repos/pennylane/_conda_forge_name
if [ ! -d repos/perses ]; then git clone --depth 1 https://github.com/choderalab/perses.git repos/perses ; fi
echo perses > repos/perses/_conda_forge_name
if [ ! -d repos/pesviewer ]; then git clone --depth 1 https://github.com/zadorlab/PESViewer.git repos/pesviewer ; fi
echo pesviewer > repos/pesviewer/_conda_forge_name
if [ ! -d repos/pgmpy ]; then git clone --depth 1 https://github.com/pgmpy/pgmpy.git repos/pgmpy ; fi
echo pgmpy > repos/pgmpy/_pypi_name
echo pgmpy > repos/pgmpy/_conda_forge_name
if [ ! -d repos/pipefunc ]; then git clone --depth 1 https://github.com/basnijholt/pipefunc.git repos/pipefunc ; fi
echo pipefunc > repos/pipefunc/_pypi_name
echo pipefunc > repos/pipefunc/_conda_forge_name
if [ ! -d repos/ploomber ]; then git clone --depth 1 https://github.com/ploomber/ploomber.git repos/ploomber ; fi
echo ploomber > repos/ploomber/_pypi_name
echo ploomber > repos/ploomber/_conda_forge_name
if [ ! -d repos/polytope ]; then git clone --depth 1 https://github.com/tulip-control/polytope.git repos/polytope ; fi
echo polytope > repos/polytope/_pypi_name
echo polytope > repos/polytope/_conda_forge_name
if [ ! -d repos/pomegranate ]; then git clone --depth 1 https://github.com/jmschrei/pomegranate.git repos/pomegranate ; fi
echo pomegranate > repos/pomegranate/_conda_forge_name
if [ ! -d repos/powerplantmatching ]; then git clone --depth 1 https://github.com/FRESNA/powerplantmatching.git repos/powerplantmatching ; fi
echo powerplantmatching > repos/powerplantmatching/_pypi_name
echo powerplantmatching > repos/powerplantmatching/_conda_forge_name
if [ ! -d repos/prism-ds ]; then git clone --depth 1 https://github.com/runprism/prism.git repos/prism-ds ; fi
echo prism-ds > repos/prism-ds/_pypi_name
echo prism-ds > repos/prism-ds/_conda_forge_name
if [ ! -d repos/psi4 ]; then git clone --depth 1 https://github.com/psi4/psi4.git repos/psi4 ; fi
echo psi4 > repos/psi4/_conda_forge_name
if [ ! -d repos/py2cytoscape ]; then git clone --depth 1 https://github.com/cytoscape/py2cytoscape.git repos/py2cytoscape ; fi
echo py2cytoscape > repos/py2cytoscape/_pypi_name
echo py2cytoscape > repos/py2cytoscape/_conda_forge_name
if [ ! -d repos/pydiverse-pipedag ]; then git clone --depth 1 https://github.com/pydiverse/pydiverse.pipedag.git repos/pydiverse-pipedag ; fi
echo pydiverse-pipedag > repos/pydiverse-pipedag/_pypi_name
echo pydiverse-pipedag > repos/pydiverse-pipedag/_conda_forge_name
if [ ! -d repos/pydtmc ]; then git clone --depth 1 https://github.com/TommasoBelluzzo/PyDTMC.git repos/pydtmc ; fi
echo pydtmc > repos/pydtmc/_pypi_name
echo pydtmc > repos/pydtmc/_conda_forge_name
if [ ! -d repos/pyformlang ]; then git clone --depth 1 https://github.com/Aunsiels/pyformlang.git repos/pyformlang ; fi
echo pyformlang > repos/pyformlang/_pypi_name
echo pyformlang > repos/pyformlang/_conda_forge_name
if [ ! -d repos/pyg4ometry ]; then git clone --depth 1 https://bitbucket.org/jairhul/pyg4ometry.git repos/pyg4ometry ; fi
echo pyg4ometry > repos/pyg4ometry/_conda_forge_name
if [ ! -d repos/pygmo ]; then git clone --depth 1 https://github.com/esa/pygmo2.git repos/pygmo ; fi
echo pygmo > repos/pygmo/_conda_forge_name
if [ ! -d repos/pygod ]; then git clone --depth 1 https://github.com/pygod-team/pygod.git repos/pygod ; fi
echo pygod > repos/pygod/_pypi_name
echo pygod > repos/pygod/_conda_forge_name
if [ ! -d repos/pymatgen ]; then git clone --depth 1 https://github.com/materialsproject/pymatgen.git repos/pymatgen ; fi
echo pymatgen > repos/pymatgen/_pypi_name
echo pymatgen > repos/pymatgen/_conda_forge_name
if [ ! -d repos/pymove ]; then git clone --depth 1 https://github.com/InsightLab/PyMove.git repos/pymove ; fi
echo pymove > repos/pymove/_pypi_name
echo pymove > repos/pymove/_conda_forge_name
if [ ! -d repos/pynguin ]; then git clone --depth 1 https://github.com/se2p/pynguin.git repos/pynguin ; fi
echo pynguin > repos/pynguin/_pypi_name
echo pynguin > repos/pynguin/_conda_forge_name
if [ ! -d repos/pynhd ]; then git clone --depth 1 https://github.com/hyriver/pynhd.git repos/pynhd ; fi
echo pynhd > repos/pynhd/_pypi_name
echo pynhd > repos/pynhd/_conda_forge_name
if [ ! -d repos/pyomo.extras ]; then git clone --depth 1 https://github.com/Pyomo/pyomo.git repos/pyomo.extras ; fi
echo pyomo.extras > repos/pyomo.extras/_conda_forge_name
if [ ! -d repos/pyperunner ]; then git clone --depth 1 https://github.com/glichtner/pyperunner.git repos/pyperunner ; fi
echo pyperunner > repos/pyperunner/_pypi_name
echo pyperunner > repos/pyperunner/_conda_forge_name
if [ ! -d repos/pypsa ]; then git clone --depth 1 https://github.com/PyPSA/PyPSA.git repos/pypsa ; fi
echo pypsa > repos/pypsa/_pypi_name
echo pypsa > repos/pypsa/_conda_forge_name
if [ ! -d repos/pyquil ]; then git clone --depth 1 https://github.com/rigetticomputing/pyquil.git repos/pyquil ; fi
echo pyquil > repos/pyquil/_pypi_name
echo pyquil > repos/pyquil/_conda_forge_name
if [ ! -d repos/pyrender ]; then git clone --depth 1 https://github.com/mmatl/pyrender.git repos/pyrender ; fi
echo pyrender > repos/pyrender/_conda_forge_name
if [ ! -d repos/pyribbit ]; then git clone --depth 1 https://github.com/fishbotics/pyribbit.git repos/pyribbit ; fi
echo pyribbit > repos/pyribbit/_conda_forge_name
if [ ! -d repos/pyscal-rdf ]; then git clone --depth 1 https://github.com/pyscal/pyscal_rdf.git repos/pyscal-rdf ; fi
echo pyscal-rdf > repos/pyscal-rdf/_pypi_name
echo pyscal-rdf > repos/pyscal-rdf/_conda_forge_name
if [ ! -d repos/pyseidon ]; then git clone --depth 1 https://github.com/GrumpyNounours/PySeidon.git repos/pyseidon ; fi
echo pyseidon > repos/pyseidon/_conda_forge_name
if [ ! -d repos/pytask ]; then git clone --depth 1 https://github.com/pytask-dev/pytask.git repos/pytask ; fi
echo pytask > repos/pytask/_pypi_name
echo pytask > repos/pytask/_conda_forge_name
if [ ! -d repos/pytdc ]; then git clone --depth 1 https://github.com/mims-harvard/TDC.git repos/pytdc ; fi
echo pytdc > repos/pytdc/_pypi_name
echo pytdc > repos/pytdc/_conda_forge_name
if [ ! -d repos/python-louvain ]; then git clone --depth 1 https://github.com/taynaud/python-louvain.git repos/python-louvain ; fi
echo python-louvain > repos/python-louvain/_pypi_name
echo python-louvain > repos/python-louvain/_conda_forge_name
if [ ! -d repos/pytorch-cpu ]; then git clone --depth 1 https://github.com/pytorch/pytorch.git repos/pytorch-cpu ; fi
echo pytorch-cpu > repos/pytorch-cpu/_conda_forge_name
if [ ! -d repos/pytorch_geometric ]; then git clone --depth 1 https://github.com/pyg-team/pytorch_geometric.git repos/pytorch_geometric ; fi
echo torch-geometric > repos/pytorch_geometric/_pypi_name
echo pytorch_geometric > repos/pytorch_geometric/_conda_forge_name
if [ ! -d repos/pytrack ]; then git clone --depth 1 https://github.com/cosbidev/PyTrack.git repos/pytrack ; fi
echo pytrack > repos/pytrack/_conda_forge_name
if [ ! -d repos/pytype ]; then git clone --depth 1 https://github.com/google/pytype.git repos/pytype ; fi
echo pytype > repos/pytype/_conda_forge_name
if [ ! -d repos/pyvipr ]; then git clone --depth 1 https://github.com/LoLab-VU/pyvipr.git repos/pyvipr ; fi
echo pyvipr > repos/pyvipr/_pypi_name
echo pyvipr > repos/pyvipr/_conda_forge_name
if [ ! -d repos/pyvis ]; then git clone --depth 1 https://github.com/WestHealth/pyvis.git repos/pyvis ; fi
echo pyvis > repos/pyvis/_pypi_name
echo pyvis > repos/pyvis/_conda_forge_name
if [ ! -d repos/pyvitae ]; then git clone --depth 1 https://github.com/jaydu1/VITAE.git repos/pyvitae ; fi
echo pyvitae > repos/pyvitae/_pypi_name
echo pyvitae > repos/pyvitae/_conda_forge_name
if [ ! -d repos/pywatershed ]; then git clone --depth 1 https://github.com/EC-USGS/pywatershed.git repos/pywatershed ; fi
echo pywatershed > repos/pywatershed/_pypi_name
echo pywatershed > repos/pywatershed/_conda_forge_name
if [ ! -d repos/pywr ]; then git clone --depth 1 https://github.com/pywr/pywr.git repos/pywr ; fi
echo pywr > repos/pywr/_pypi_name
echo pywr > repos/pywr/_conda_forge_name
if [ ! -d repos/pyxtal ]; then git clone --depth 1 https://github.com/qzhu2017/PyXtal.git repos/pyxtal ; fi
echo pyxtal > repos/pyxtal/_pypi_name
echo pyxtal > repos/pyxtal/_conda_forge_name
if [ ! -d repos/qcelemental ]; then git clone --depth 1 https://github.com/MolSSI/QCElemental.git repos/qcelemental ; fi
echo qcelemental > repos/qcelemental/_pypi_name
echo qcelemental > repos/qcelemental/_conda_forge_name
if [ ! -d repos/qforce ]; then git clone --depth 1 https://github.com/selimsami/qforce.git repos/qforce ; fi
echo qforce > repos/qforce/_pypi_name
echo qforce > repos/qforce/_conda_forge_name
if [ ! -d repos/qibocal ]; then git clone --depth 1 https://github.com/qiboteam/qibocal.git repos/qibocal ; fi
echo qibocal > repos/qibocal/_conda_forge_name
if [ ! -d repos/qiskit-optimization ]; then git clone --depth 1 https://github.com/Qiskit/qiskit-optimization.git repos/qiskit-optimization ; fi
echo qiskit-optimization > repos/qiskit-optimization/_pypi_name
echo qiskit-optimization > repos/qiskit-optimization/_conda_forge_name
if [ ! -d repos/qmpy ]; then git clone --depth 1 https://github.com/wolverton-research-group/qmpy.git repos/qmpy ; fi
echo qmpy > repos/qmpy/_pypi_name
echo qmpy > repos/qmpy/_conda_forge_name
if [ ! -d repos/quantumflow ]; then git clone --depth 1 https://github.com/gecrooks/quantumflow.git repos/quantumflow ; fi
echo quantumflow > repos/quantumflow/_pypi_name
echo quantumflow > repos/quantumflow/_conda_forge_name
if [ ! -d repos/qubekit ]; then git clone --depth 1 https://github.com/qubekit/QUBEKit.git repos/qubekit ; fi
echo qubekit > repos/qubekit/_conda_forge_name
if [ ! -d repos/quera-ahs-utils ]; then git clone --depth 1 https://github.com/QuEraComputing/quera-ahs-utils.git repos/quera-ahs-utils ; fi
echo quera-ahs-utils > repos/quera-ahs-utils/_pypi_name
echo quera-ahs-utils > repos/quera-ahs-utils/_conda_forge_name
if [ ! -d repos/radioactivedecay ]; then git clone --depth 1 https://github.com/radioactivedecay/radioactivedecay.git repos/radioactivedecay ; fi
echo radioactivedecay > repos/radioactivedecay/_pypi_name
echo radioactivedecay > repos/radioactivedecay/_conda_forge_name
if [ ! -d repos/rdflib ]; then git clone --depth 1 https://github.com/RDFLib/rdflib.git repos/rdflib ; fi
echo rdflib > repos/rdflib/_pypi_name
echo rdflib > repos/rdflib/_conda_forge_name
if [ ! -d repos/reacnetgenerator ]; then git clone --depth 1 https://github.com/tongzhugroup/reacnetgenerator.git repos/reacnetgenerator ; fi
echo reacnetgenerator > repos/reacnetgenerator/_conda_forge_name
if [ ! -d repos/region ]; then git clone --depth 1 https://github.com/pysal/region.git repos/region ; fi
echo region > repos/region/_pypi_name
echo region > repos/region/_conda_forge_name
if [ ! -d repos/riskfolio-lib ]; then git clone --depth 1 https://github.com/dcajasn/Riskfolio-Lib.git repos/riskfolio-lib ; fi
echo riskfolio-lib > repos/riskfolio-lib/_pypi_name
echo riskfolio-lib > repos/riskfolio-lib/_conda_forge_name
if [ ! -d repos/rivgraph ]; then git clone --depth 1 https://github.com/VeinsOfTheEarth/RivGraph.git repos/rivgraph ; fi
echo rivgraph > repos/rivgraph/_conda_forge_name
if [ ! -d repos/rnatools ]; then git clone --depth 1 https://github.com/grice/RNAtools.git repos/rnatools ; fi
echo rnatools > repos/rnatools/_pypi_name
echo rnatools > repos/rnatools/_conda_forge_name
if [ ! -d repos/robocrys ]; then git clone --depth 1 https://github.com/hackingmaterials/robocrystallographer.git repos/robocrys ; fi
echo robocrys > repos/robocrys/_pypi_name
echo robocrys > repos/robocrys/_conda_forge_name
if [ ! -d repos/rp2biosensor ]; then git clone --depth 1 https://github.com/brsynth/rp2biosensor.git repos/rp2biosensor ; fi
echo rp2biosensor > repos/rp2biosensor/_conda_forge_name
if [ ! -d repos/sage ]; then git clone --depth 1 https://github.com/sagemath/sage.git repos/sage ; fi
echo sage > repos/sage/_conda_forge_name
if [ ! -d repos/scanpy ]; then git clone --depth 1 https://github.com/theislab/scanpy.git repos/scanpy ; fi
echo scanpy > repos/scanpy/_pypi_name
echo scanpy > repos/scanpy/_conda_forge_name
if [ ! -d repos/sceptre ]; then git clone --depth 1 https://github.com/Sceptre/sceptre.git repos/sceptre ; fi
echo sceptre > repos/sceptre/_pypi_name
echo sceptre > repos/sceptre/_conda_forge_name
if [ ! -d repos/scikit-fuzzy ]; then git clone --depth 1 https://github.com/scikit-fuzzy/scikit-fuzzy.git repos/scikit-fuzzy ; fi
echo scikit-fuzzy > repos/scikit-fuzzy/_pypi_name
echo scikit-fuzzy > repos/scikit-fuzzy/_conda_forge_name
if [ ! -d repos/scikit-image ]; then git clone --depth 1 https://github.com/scikit-image/scikit-image.git repos/scikit-image ; fi
echo scikit-image > repos/scikit-image/_pypi_name
echo scikit-image > repos/scikit-image/_conda_forge_name
if [ ! -d repos/scikit-multilearn ]; then git clone --depth 1 https://github.com/scikit-multilearn/scikit-multilearn.git repos/scikit-multilearn ; fi
echo scikit-multilearn > repos/scikit-multilearn/_conda_forge_name
if [ ! -d repos/scine-chemoton ]; then git clone --depth 1 https://github.com/qcscine/chemoton.git repos/scine-chemoton ; fi
echo scine-chemoton > repos/scine-chemoton/_conda_forge_name
if [ ! -d repos/searoute ]; then git clone --depth 1 https://github.com/genthalili/searoute-py.git repos/searoute ; fi
echo searoute > repos/searoute/_pypi_name
echo searoute > repos/searoute/_conda_forge_name
if [ ! -d repos/sharrow ]; then git clone --depth 1 https://github.com/ActivitySim/sharrow.git repos/sharrow ; fi
echo sharrow > repos/sharrow/_pypi_name
echo sharrow > repos/sharrow/_conda_forge_name
if [ ! -d repos/shed ]; then git clone --depth 1 https://github.com/xpdAcq/shed-streaming.git repos/shed ; fi
echo shed > repos/shed/_conda_forge_name
if [ ! -d repos/shed-streaming ]; then git clone --depth 1 https://github.com/xpdAcq/shed-streaming.git repos/shed-streaming ; fi
echo shed-streaming > repos/shed-streaming/_conda_forge_name
if [ ! -d repos/skan ]; then git clone --depth 1 https://github.com/jni/skan.git repos/skan ; fi
echo skan > repos/skan/_pypi_name
echo skan > repos/skan/_conda_forge_name
if [ ! -d repos/smif ]; then git clone --depth 1 https://github.com/nismod/smif.git repos/smif ; fi
echo smif > repos/smif/_pypi_name
echo smif > repos/smif/_conda_forge_name
if [ ! -d repos/snorkel ]; then git clone --depth 1 https://github.com/snorkel-team/snorkel.git repos/snorkel ; fi
echo snorkel > repos/snorkel/_conda_forge_name
if [ ! -d repos/solaris ]; then git clone --depth 1 https://github.com/CosmiQ/solaris.git repos/solaris ; fi
echo solaris > repos/solaris/_pypi_name
echo solaris > repos/solaris/_conda_forge_name
if [ ! -d repos/sos ]; then git clone --depth 1 https://github.com/vatlab/SoS.git repos/sos ; fi
echo sos > repos/sos/_pypi_name
echo sos > repos/sos/_conda_forge_name
if [ ! -d repos/spatialdata ]; then git clone --depth 1 https://github.com/scverse/spatialdata.git repos/spatialdata ; fi
echo spatialdata > repos/spatialdata/_pypi_name
echo spatialdata > repos/spatialdata/_conda_forge_name
if [ ! -d repos/spectrafit ]; then git clone --depth 1 https://github.com/anselmoo/spectrafit.git repos/spectrafit ; fi
echo spectrafit > repos/spectrafit/_pypi_name
echo spectrafit > repos/spectrafit/_conda_forge_name
if [ ! -d repos/spindry ]; then git clone --depth 1 https://github.com/andrewtarzia/SpinDry.git repos/spindry ; fi
echo spindry > repos/spindry/_pypi_name
echo spindry > repos/spindry/_conda_forge_name
if [ ! -d repos/spopt ]; then git clone --depth 1 https://github.com/pysal/spopt.git repos/spopt ; fi
echo spopt > repos/spopt/_pypi_name
echo spopt > repos/spopt/_conda_forge_name
if [ ! -d repos/spyrmsd ]; then git clone --depth 1 https://github.com/RMeli/spyrmsd.git repos/spyrmsd ; fi
echo spyrmsd > repos/spyrmsd/_pypi_name
echo spyrmsd > repos/spyrmsd/_conda_forge_name
if [ ! -d repos/sqllineage ]; then git clone --depth 1 https://github.com/reata/sqllineage.git repos/sqllineage ; fi
echo sqllineage > repos/sqllineage/_pypi_name
echo sqllineage > repos/sqllineage/_conda_forge_name
if [ ! -d repos/steinbock ]; then git clone --depth 1 https://github.com/BodenmillerGroup/steinbock.git repos/steinbock ; fi
echo steinbock > repos/steinbock/_pypi_name
echo steinbock > repos/steinbock/_conda_forge_name
if [ ! -d repos/strawberryfields ]; then git clone --depth 1 https://github.com/XanaduAI/StrawberryFields.git repos/strawberryfields ; fi
echo strawberryfields > repos/strawberryfields/_pypi_name
echo strawberryfields > repos/strawberryfields/_conda_forge_name
if [ ! -d repos/stripnet ]; then git clone --depth 1 https://github.com/stephenleo/stripnet.git repos/stripnet ; fi
echo stripnet > repos/stripnet/_pypi_name
echo stripnet > repos/stripnet/_conda_forge_name
if [ ! -d repos/structout ]; then git clone --depth 1 https://github.com/smautner/StructOut_py3.git repos/structout ; fi
echo structout > repos/structout/_pypi_name
echo structout > repos/structout/_conda_forge_name
if [ ! -d repos/syntheseus ]; then git clone --depth 1 https://github.com/microsoft/syntheseus.git repos/syntheseus ; fi
echo syntheseus > repos/syntheseus/_pypi_name
echo syntheseus > repos/syntheseus/_conda_forge_name
if [ ! -d repos/tardis-sn ]; then git clone --depth 1 https://github.com/tardis-sn/tardis.git repos/tardis-sn ; fi
echo tardis-sn > repos/tardis-sn/_conda_forge_name
if [ ! -d repos/textacy ]; then git clone --depth 1 https://github.com/chartbeat-labs/textacy.git repos/textacy ; fi
echo textacy > repos/textacy/_pypi_name
echo textacy > repos/textacy/_conda_forge_name
if [ ! -d repos/tico ]; then git clone --depth 1 https://github.com/SimonBoothroyd/tico.git repos/tico ; fi
echo tico > repos/tico/_conda_forge_name
if [ ! -d repos/ties20 ]; then git clone --depth 1 https://github.com/UCL-CCS/TIES.git repos/ties20 ; fi
echo ties20 > repos/ties20/_conda_forge_name
if [ ! -d repos/torchmd ]; then git clone --depth 1 https://github.com/torchmd/torchmd.git repos/torchmd ; fi
echo torchmd > repos/torchmd/_pypi_name
echo torchmd > repos/torchmd/_conda_forge_name
if [ ! -d repos/tpot2 ]; then git clone --depth 1 https://github.com/EpistasisLab/tpot2.git repos/tpot2 ; fi
echo tpot2 > repos/tpot2/_pypi_name
echo tpot2 > repos/tpot2/_conda_forge_name
if [ ! -d repos/traffix ]; then git clone --depth 1 https://github.com/Ultios/traffix.git repos/traffix ; fi
echo traffix > repos/traffix/_pypi_name
echo traffix > repos/traffix/_conda_forge_name
if [ ! -d repos/traja ]; then git clone --depth 1 https://github.com/traja-team/traja.git repos/traja ; fi
echo traja > repos/traja/_conda_forge_name
if [ ! -d repos/transformato ]; then git clone --depth 1 https://github.com/wiederm/transformato.git repos/transformato ; fi
echo transformato > repos/transformato/_conda_forge_name
if [ ! -d repos/tropycal ]; then git clone --depth 1 https://github.com/tropycal/tropycal.git repos/tropycal ; fi
echo tropycal > repos/tropycal/_pypi_name
echo tropycal > repos/tropycal/_conda_forge_name
if [ ! -d repos/tsam ]; then git clone --depth 1 https://github.com/FZJ-IEK3-VSA/tsam.git repos/tsam ; fi
echo tsam > repos/tsam/_pypi_name
echo tsam > repos/tsam/_conda_forge_name
if [ ! -d repos/tvb-library ]; then git clone --depth 1 https://github.com/the-virtual-brain/tvb-library.git repos/tvb-library ; fi
echo tvb-library > repos/tvb-library/_pypi_name
echo tvb-library > repos/tvb-library/_conda_forge_name
if [ ! -d repos/urchin ]; then git clone --depth 1 https://github.com/fishbotics/urchin.git repos/urchin ; fi
echo urchin > repos/urchin/_pypi_name
echo urchin > repos/urchin/_conda_forge_name
if [ ! -d repos/urdfpy ]; then git clone --depth 1 https://github.com/mmatl/urdfpy.git repos/urdfpy ; fi
echo urdfpy > repos/urdfpy/_conda_forge_name
if [ ! -d repos/vermouth ]; then git clone --depth 1 https://github.com/marrink-lab/vermouth-martinize.git repos/vermouth ; fi
echo vermouth > repos/vermouth/_pypi_name
echo vermouth > repos/vermouth/_conda_forge_name
if [ ! -d repos/viridis ]; then git clone --depth 1 https://github.com/jni/viridis.git repos/viridis ; fi
echo viridis > repos/viridis/_pypi_name
echo viridis > repos/viridis/_conda_forge_name
if [ ! -d repos/virocon ]; then git clone --depth 1 https://github.com/virocon-organization/virocon.git repos/virocon ; fi
echo virocon > repos/virocon/_pypi_name
echo virocon > repos/virocon/_conda_forge_name
if [ ! -d repos/visions ]; then git clone --depth 1 https://github.com/dylan-profiler/visions.git repos/visions ; fi
echo visions > repos/visions/_pypi_name
echo visions > repos/visions/_conda_forge_name
if [ ! -d repos/vizlo ]; then git clone --depth 1 https://github.com/glaserL/vizlo.git repos/vizlo ; fi
echo vizlo > repos/vizlo/_conda_forge_name
if [ ! -d repos/weldx ]; then git clone --depth 1 https://github.com/BAMWelDX/weldx.git repos/weldx ; fi
echo weldx > repos/weldx/_pypi_name
echo weldx > repos/weldx/_conda_forge_name
if [ ! -d repos/wntr ]; then git clone --depth 1 https://github.com/USEPA/WNTR.git repos/wntr ; fi
echo wntr > repos/wntr/_conda_forge_name
if [ ! -d repos/xyz2mol ]; then git clone --depth 1 https://github.com/jensengroup/xyz2mol.git repos/xyz2mol ; fi
echo xyz2mol > repos/xyz2mol/_conda_forge_name
if [ ! -d repos/ylearn ]; then git clone --depth 1 https://github.com/DataCanvasIO/YLearn.git repos/ylearn ; fi
echo ylearn > repos/ylearn/_conda_forge_name
if [ ! -d repos/zipline ]; then git clone --depth 1 https://github.com/quantopian/zipline.git repos/zipline ; fi
echo zipline > repos/zipline/_pypi_name
echo zipline > repos/zipline/_conda_forge_name
if [ ! -d repos/zipline-reloaded ]; then git clone --depth 1 https://github.com/stefan-jansen/zipline-reloaded.git repos/zipline-reloaded ; fi
echo zipline-reloaded > repos/zipline-reloaded/_pypi_name
echo zipline-reloaded > repos/zipline-reloaded/_conda_forge_name
