#!/usr/bin/env bash
# Copyright (c) 2024, NVIDIA CORPORATION.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# THIS FILE IS AUTOMATICALLY GENERATED BY _1_create_git_clone.py
mkdir -p repos-skip
if [ ! -d repos-skip/airfly ]; then git clone --depth 1 https://github.com/ryanchao2012/airfly.git repos-skip/airfly ; fi
echo airfly > repos-skip/airfly/_pypi_name
echo airfly > repos-skip/airfly/_conda_forge_name
if [ ! -d repos-skip/alphashape ]; then git clone --depth 1 https://github.com/bellockk/alphashape.git repos-skip/alphashape ; fi
echo alphashape > repos-skip/alphashape/_pypi_name
echo alphashape > repos-skip/alphashape/_conda_forge_name
if [ ! -d repos-skip/atomate ]; then git clone --depth 1 https://github.com/hackingmaterials/atomate.git repos-skip/atomate ; fi
echo atomate > repos-skip/atomate/_pypi_name
echo atomate > repos-skip/atomate/_conda_forge_name
if [ ! -d repos-skip/bake ]; then git clone --depth 1 https://github.com/kennethreitz/bake.git repos-skip/bake ; fi
echo bake-cli > repos-skip/bake/_pypi_name
echo bake > repos-skip/bake/_conda_forge_name
if [ ! -d repos-skip/caffe ]; then git clone --depth 1 https://github.com/BVLC/caffe.git repos-skip/caffe ; fi
echo caffe > repos-skip/caffe/_conda_forge_name
if [ ! -d repos-skip/cfn-lint ]; then git clone --depth 1 https://github.com/aws-cloudformation/cfn-python-lint.git repos-skip/cfn-lint ; fi
echo cfn-lint > repos-skip/cfn-lint/_pypi_name
echo cfn-lint > repos-skip/cfn-lint/_conda_forge_name
if [ ! -d repos-skip/chemplot ]; then git clone --depth 1 https://github.com/mcsorkun/ChemPlot.git repos-skip/chemplot ; fi
echo chemplot > repos-skip/chemplot/_pypi_name
echo chemplot > repos-skip/chemplot/_conda_forge_name
if [ ! -d repos-skip/collatex-python ]; then git clone --depth 1 https://github.com/interedition/collatex.git repos-skip/collatex-python ; fi
echo collatex > repos-skip/collatex-python/_pypi_name
echo collatex-python > repos-skip/collatex-python/_conda_forge_name
if [ ! -d repos-skip/colormath ]; then git clone --depth 1 https://github.com/gtaylor/python-colormath.git repos-skip/colormath ; fi
echo colormath > repos-skip/colormath/_pypi_name
echo colormath > repos-skip/colormath/_conda_forge_name
if [ ! -d repos-skip/conda-export ]; then git clone --depth 1 https://github.com/olegtarasov/conda-export.git repos-skip/conda-export ; fi
echo conda-export > repos-skip/conda-export/_conda_forge_name
if [ ! -d repos-skip/conda-tree ]; then git clone --depth 1 https://github.com/rvalieris/conda-tree.git repos-skip/conda-tree ; fi
echo conda-tree > repos-skip/conda-tree/_conda_forge_name
if [ ! -d repos-skip/dagster-libs ]; then git clone --depth 1 https://github.com/dagster-io/dagster.git repos-skip/dagster-libs ; fi
echo dagster-libs > repos-skip/dagster-libs/_conda_forge_name
if [ ! -d repos-skip/dgllife ]; then git clone --depth 1 https://github.com/awslabs/dgl-lifesci.git repos-skip/dgllife ; fi
echo dgllife > repos-skip/dgllife/_pypi_name
echo dgllife > repos-skip/dgllife/_conda_forge_name
if [ ! -d repos-skip/earthformer ]; then git clone --depth 1 https://github.com/opengeos/earthformer.git repos-skip/earthformer ; fi
echo earthformer > repos-skip/earthformer/_pypi_name
echo earthformer > repos-skip/earthformer/_conda_forge_name
if [ ! -d repos-skip/empack ]; then git clone --depth 1 https://github.com/emscripten-forge/empack.git repos-skip/empack ; fi
echo empack > repos-skip/empack/_pypi_name
echo empack > repos-skip/empack/_conda_forge_name
if [ ! -d repos-skip/epitools ]; then git clone --depth 1 https://github.com/epitools/epitools.git repos-skip/epitools ; fi
echo epitools > repos-skip/epitools/_pypi_name
echo epitools > repos-skip/epitools/_conda_forge_name
if [ ! -d repos-skip/ethos_penalps ]; then git clone --depth 1 https://github.com/FZJ-IEK3-VSA/ETHOS_PeNALPS.git repos-skip/ethos_penalps ; fi
echo ethos_penalps > repos-skip/ethos_penalps/_conda_forge_name
if [ ! -d repos-skip/femto ]; then git clone --depth 1 https://github.com/psivant/femto.git repos-skip/femto ; fi
echo femto > repos-skip/femto/_conda_forge_name
if [ ! -d repos-skip/fine ]; then git clone --depth 1 https://github.com/FZJ-IEK3-VSA/FINE.git repos-skip/fine ; fi
echo fine > repos-skip/fine/_conda_forge_name
if [ ! -d repos-skip/gempy ]; then git clone --depth 1 https://github.com/cgre-aachen/gempy.git repos-skip/gempy ; fi
echo gempy > repos-skip/gempy/_pypi_name
echo gempy > repos-skip/gempy/_conda_forge_name
if [ ! -d repos-skip/generalisedformanricci ]; then git clone --depth 1 https://github.com/ExpectozJJ/GeneralisedFormanRicci.git repos-skip/generalisedformanricci ; fi
echo generalisedformanricci > repos-skip/generalisedformanricci/_pypi_name
echo generalisedformanricci > repos-skip/generalisedformanricci/_conda_forge_name
if [ ! -d repos-skip/guardian ]; then git clone --depth 1 https://git.ligo.org/cds/software/guardian.git repos-skip/guardian ; fi
echo guardian > repos-skip/guardian/_conda_forge_name
if [ ! -d repos-skip/infrared ]; then git clone --depth 1 https://gitlab.inria.fr/amibio/Infrared.git repos-skip/infrared ; fi
echo infrared > repos-skip/infrared/_conda_forge_name
if [ ! -d repos-skip/lava ]; then git clone --depth 1 https://github.com/lava-nc/lava.git repos-skip/lava ; fi
echo lava > repos-skip/lava/_conda_forge_name
if [ ! -d repos-skip/lava-optimization ]; then git clone --depth 1 https://github.com/lava-nc/lava-optimization.git repos-skip/lava-optimization ; fi
echo lava-optimization > repos-skip/lava-optimization/_conda_forge_name
if [ ! -d repos-skip/lbnightlytools ]; then git clone --depth 1 https://gitlab.cern.ch/lhcb-core/LbNightlyTools.git repos-skip/lbnightlytools ; fi
echo lbnightlytools > repos-skip/lbnightlytools/_pypi_name
echo lbnightlytools > repos-skip/lbnightlytools/_conda_forge_name
if [ ! -d repos-skip/libsemigroups_cppyy ]; then git clone --depth 1 https://github.com/libsemigroups/libsemigroups_cppyy.git repos-skip/libsemigroups_cppyy ; fi
echo libsemigroups_cppyy > repos-skip/libsemigroups_cppyy/_conda_forge_name
if [ ! -d repos-skip/matplotx ]; then git clone --depth 1 https://github.com/nschloe/matplotx.git repos-skip/matplotx ; fi
echo matplotx > repos-skip/matplotx/_pypi_name
echo matplotx > repos-skip/matplotx/_conda_forge_name
if [ ! -d repos-skip/mdanalysis ]; then git clone --depth 1 https://github.com/MDAnalysis/mdanalysis.git repos-skip/mdanalysis ; fi
echo mdanalysis > repos-skip/mdanalysis/_pypi_name
echo mdanalysis > repos-skip/mdanalysis/_conda_forge_name
if [ ! -d repos-skip/medcam ]; then git clone --depth 1 https://github.com/MECLabTUDA/M3d-Cam.git repos-skip/medcam ; fi
echo medcam > repos-skip/medcam/_pypi_name
echo medcam > repos-skip/medcam/_conda_forge_name
if [ ! -d repos-skip/mosdef_cassandra ]; then git clone --depth 1 https://github.com/MaginnGroup/mosdef_cassandra.git repos-skip/mosdef_cassandra ; fi
echo mosdef_cassandra > repos-skip/mosdef_cassandra/_conda_forge_name
if [ ! -d repos-skip/napari-filament-annotator ]; then git clone --depth 1 https://github.com/amedyukhina/napari-filament-annotator.git repos-skip/napari-filament-annotator ; fi
echo napari-filament-annotator > repos-skip/napari-filament-annotator/_pypi_name
echo napari-filament-annotator > repos-skip/napari-filament-annotator/_conda_forge_name
if [ ! -d repos-skip/nomad-camels ]; then git clone --depth 1 https://github.com/FAU-LAP/NOMAD-CAMELS.git repos-skip/nomad-camels ; fi
echo nomad-camels > repos-skip/nomad-camels/_pypi_name
echo nomad-camels > repos-skip/nomad-camels/_conda_forge_name
if [ ! -d repos-skip/openfermion ]; then git clone --depth 1 https://github.com/quantumlib/OpenFermion.git repos-skip/openfermion ; fi
echo openfermion > repos-skip/openfermion/_pypi_name
echo openfermion > repos-skip/openfermion/_conda_forge_name
if [ ! -d repos-skip/openff-evaluator ]; then git clone --depth 1 https://github.com/openforcefield/openff-evaluator.git repos-skip/openff-evaluator ; fi
echo openff-evaluator > repos-skip/openff-evaluator/_conda_forge_name
if [ ! -d repos-skip/openff-fragmenter ]; then git clone --depth 1 https://github.com/openforcefield/openff-fragmenter.git repos-skip/openff-fragmenter ; fi
echo openff-fragmenter > repos-skip/openff-fragmenter/_conda_forge_name
if [ ! -d repos-skip/openmmforcefields ]; then git clone --depth 1 https://github.com/openmm/openmmforcefields.git repos-skip/openmmforcefields ; fi
echo openmmforcefields > repos-skip/openmmforcefields/_conda_forge_name
if [ ! -d repos-skip/plio ]; then git clone --depth 1 https://github.com/USGS-Astrogeology/plio.git repos-skip/plio ; fi
echo plio > repos-skip/plio/_conda_forge_name
if [ ! -d repos-skip/pmapper ]; then git clone --depth 1 https://github.com/DrrDom/pmapper.git repos-skip/pmapper ; fi
echo pmapper > repos-skip/pmapper/_pypi_name
echo pmapper > repos-skip/pmapper/_conda_forge_name
if [ ! -d repos-skip/prov ]; then git clone --depth 1 https://github.com/trungdong/prov.git repos-skip/prov ; fi
echo prov > repos-skip/prov/_pypi_name
echo prov > repos-skip/prov/_conda_forge_name
if [ ! -d repos-skip/ptac ]; then git clone --depth 1 https://github.com/DLR-VF/PtAC.git repos-skip/ptac ; fi
echo ptac > repos-skip/ptac/_pypi_name
echo ptac > repos-skip/ptac/_conda_forge_name
if [ ! -d repos-skip/pytfa ]; then git clone --depth 1 https://github.com/EPFL-LCSB/pytfa.git repos-skip/pytfa ; fi
echo pytfa > repos-skip/pytfa/_conda_forge_name
if [ ! -d repos-skip/qibolab ]; then git clone --depth 1 https://github.com/qiboteam/qibolab.git repos-skip/qibolab ; fi
echo qibolab > repos-skip/qibolab/_conda_forge_name
if [ ! -d repos-skip/quantum-blackbird ]; then git clone --depth 1 https://github.com/XanaduAI/blackbird.git repos-skip/quantum-blackbird ; fi
echo quantum-blackbird > repos-skip/quantum-blackbird/_pypi_name
echo quantum-blackbird > repos-skip/quantum-blackbird/_conda_forge_name
if [ ! -d repos-skip/responsibleai ]; then git clone --depth 1 https://github.com/microsoft/responsible-ai-toolbox.git repos-skip/responsibleai ; fi
echo responsibleai > repos-skip/responsibleai/_pypi_name
echo responsibleai > repos-skip/responsibleai/_conda_forge_name
if [ ! -d repos-skip/roseau-load-flow ]; then git clone --depth 1 https://github.com/RoseauTechnologies/Roseau_Load_Flow.git repos-skip/roseau-load-flow ; fi
echo roseau-load-flow > repos-skip/roseau-load-flow/_pypi_name
echo roseau-load-flow > repos-skip/roseau-load-flow/_conda_forge_name
if [ ! -d repos-skip/rptools ]; then git clone --depth 1 https://github.com/brsynth/rptools.git repos-skip/rptools ; fi
echo rptools > repos-skip/rptools/_conda_forge_name
if [ ! -d repos-skip/rubinenv ]; then git clone --depth 1 https://github.com/conda-forge/rubinenv-feedstock.git repos-skip/rubinenv ; fi
echo rubinenv > repos-skip/rubinenv/_conda_forge_name
if [ ! -d repos-skip/sknw ]; then git clone --depth 1 https://github.com/yxdragon/sknw.git repos-skip/sknw ; fi
echo sknw > repos-skip/sknw/_pypi_name
echo sknw > repos-skip/sknw/_conda_forge_name
if [ ! -d repos-skip/skypy ]; then git clone --depth 1 https://github.com/skypyproject/skypy.git repos-skip/skypy ; fi
echo skypy > repos-skip/skypy/_pypi_name
echo skypy > repos-skip/skypy/_conda_forge_name
if [ ! -d repos-skip/squidpy ]; then git clone --depth 1 https://github.com/scverse/squidpy.git repos-skip/squidpy ; fi
echo squidpy > repos-skip/squidpy/_pypi_name
echo squidpy > repos-skip/squidpy/_conda_forge_name
if [ ! -d repos-skip/stanza ]; then git clone --depth 1 https://github.com/stanfordnlp/stanza.git repos-skip/stanza ; fi
echo stanza > repos-skip/stanza/_pypi_name
echo stanza > repos-skip/stanza/_conda_forge_name
if [ ! -d repos-skip/torch-scatter ]; then git clone --depth 1 https://github.com/rusty1s/pytorch_scatter.git repos-skip/torch-scatter ; fi
echo torch-scatter > repos-skip/torch-scatter/_pypi_name
echo torch-scatter > repos-skip/torch-scatter/_conda_forge_name
if [ ! -d repos-skip/trackintel ]; then git clone --depth 1 https://github.com/mie-lab/trackintel.git repos-skip/trackintel ; fi
echo trackintel > repos-skip/trackintel/_pypi_name
echo trackintel > repos-skip/trackintel/_conda_forge_name
if [ ! -d repos-skip/treedecomp ]; then git clone --depth 1 https://gitlab.inria.fr/amibio/treedecomp.git repos-skip/treedecomp ; fi
echo treedecomp > repos-skip/treedecomp/_pypi_name
echo treedecomp > repos-skip/treedecomp/_conda_forge_name
if [ ! -d repos-skip/waves ]; then git clone --depth 1 https://github.com/lanl/waves.git repos-skip/waves ; fi
echo waves > repos-skip/waves/_conda_forge_name
if [ ! -d repos-skip/yake ]; then git clone --depth 1 https://github.com/LIAAD/yake.git repos-skip/yake ; fi
echo yake > repos-skip/yake/_pypi_name
echo yake > repos-skip/yake/_conda_forge_name
