#!/usr/bin/env bash
#
# THIS FILE IS AUTOMATICALLY GENERATED BY _1_create_git_clone.py
mkdir -p repos-transitive
if [ ! -d repos-transitive/abipy ]; then git clone --depth 1 https://github.com/abinit/abipy.git repos-transitive/abipy ; fi
echo abipy > repos-transitive/abipy/_pypi_name
echo abipy > repos-transitive/abipy/_conda_forge_name
if [ ! -d repos-transitive/alchemiscale ]; then git clone --depth 1 https://github.com/openforcefield/alchemiscale.git repos-transitive/alchemiscale ; fi
echo alchemiscale > repos-transitive/alchemiscale/_conda_forge_name
if [ ! -d repos-transitive/alibi-detect ]; then git clone --depth 1 https://github.com/SeldonIO/alibi-detect.git repos-transitive/alibi-detect ; fi
echo alibi-detect > repos-transitive/alibi-detect/_pypi_name
echo alibi-detect > repos-transitive/alibi-detect/_conda_forge_name
if [ ! -d repos-transitive/alignn ]; then git clone --depth 1 https://github.com/usnistgov/alignn.git repos-transitive/alignn ; fi
echo alignn > repos-transitive/alignn/_conda_forge_name
if [ ! -d repos-transitive/amazon-braket-ocean-plugin ]; then git clone --depth 1 https://github.com/aws/amazon-braket-ocean-plugin-python.git repos-transitive/amazon-braket-ocean-plugin ; fi
echo amazon-braket-ocean-plugin > repos-transitive/amazon-braket-ocean-plugin/_pypi_name
echo amazon-braket-ocean-plugin > repos-transitive/amazon-braket-ocean-plugin/_conda_forge_name
if [ ! -d repos-transitive/amep ]; then git clone --depth 1 https://github.com/amepproject/amep.git repos-transitive/amep ; fi
echo amep > repos-transitive/amep/_pypi_name
echo amep > repos-transitive/amep/_conda_forge_name
if [ ! -d repos-transitive/antiberty ]; then git clone --depth 1 https://github.com/jeffreyruffolo/AntiBERTy.git repos-transitive/antiberty ; fi
echo antiberty > repos-transitive/antiberty/_pypi_name
echo antiberty > repos-transitive/antiberty/_conda_forge_name
if [ ! -d repos-transitive/arabica ]; then git clone --depth 1 https://github.com/PetrKorab/Arabica.git repos-transitive/arabica ; fi
echo arabica > repos-transitive/arabica/_pypi_name
echo arabica > repos-transitive/arabica/_conda_forge_name
if [ ! -d repos-transitive/asapdiscovery ]; then git clone --depth 1 https://github.com/asapdiscovery/asapdiscovery.git repos-transitive/asapdiscovery ; fi
echo asapdiscovery > repos-transitive/asapdiscovery/_conda_forge_name
if [ ! -d repos-transitive/auto_gptq ]; then git clone --depth 1 https://github.com/PanQiWei/AutoGPTQ.git repos-transitive/auto_gptq ; fi
echo auto_gptq > repos-transitive/auto_gptq/_conda_forge_name
if [ ! -d repos-transitive/autoawq ]; then git clone --depth 1 https://github.com/casper-hansen/AutoAWQ.git repos-transitive/autoawq ; fi
echo autoawq > repos-transitive/autoawq/_conda_forge_name
if [ ! -d repos-transitive/autogluon ]; then git clone --depth 1 https://github.com/autogluon/autogluon.git repos-transitive/autogluon ; fi
echo autogluon > repos-transitive/autogluon/_pypi_name
echo autogluon > repos-transitive/autogluon/_conda_forge_name
if [ ! -d repos-transitive/autogluon.multimodal ]; then git clone --depth 1 https://github.com/autogluon/autogluon.git repos-transitive/autogluon.multimodal ; fi
echo autogluon.multimodal > repos-transitive/autogluon.multimodal/_pypi_name
echo autogluon.multimodal > repos-transitive/autogluon.multimodal/_conda_forge_name
if [ ! -d repos-transitive/autogluon.text ]; then git clone --depth 1 https://github.com/autogluon/autogluon.git repos-transitive/autogluon.text ; fi
echo autogluon.text > repos-transitive/autogluon.text/_pypi_name
echo autogluon.text > repos-transitive/autogluon.text/_conda_forge_name
if [ ! -d repos-transitive/autogluon.vision ]; then git clone --depth 1 https://github.com/autogluon/autogluon.git repos-transitive/autogluon.vision ; fi
echo autogluon.vision > repos-transitive/autogluon.vision/_pypi_name
echo autogluon.vision > repos-transitive/autogluon.vision/_conda_forge_name
if [ ! -d repos-transitive/bert-extractive-summarizer ]; then git clone --depth 1 https://github.com/dmmiller612/bert-extractive-summarizer.git repos-transitive/bert-extractive-summarizer ; fi
echo bert-extractive-summarizer > repos-transitive/bert-extractive-summarizer/_conda_forge_name
if [ ! -d repos-transitive/biofilm ]; then git clone --depth 1 https://github.com/smautner/biofilm.git repos-transitive/biofilm ; fi
echo biofilm > repos-transitive/biofilm/_pypi_name
echo biofilm > repos-transitive/biofilm/_conda_forge_name
if [ ! -d repos-transitive/brainglobe-atlasapi ]; then git clone --depth 1 https://github.com/brainglobe/brainglobe-atlasapi.git repos-transitive/brainglobe-atlasapi ; fi
echo brainglobe-atlasapi > repos-transitive/brainglobe-atlasapi/_pypi_name
echo brainglobe-atlasapi > repos-transitive/brainglobe-atlasapi/_conda_forge_name
if [ ! -d repos-transitive/cartes ]; then git clone --depth 1 https://github.com/xoolive/cartes.git repos-transitive/cartes ; fi
echo cartes > repos-transitive/cartes/_pypi_name
echo cartes > repos-transitive/cartes/_conda_forge_name
if [ ! -d repos-transitive/caustics ]; then git clone --depth 1 https://github.com/Ciela-Institute/caustics.git repos-transitive/caustics ; fi
echo caustics > repos-transitive/caustics/_pypi_name
echo caustics > repos-transitive/caustics/_conda_forge_name
if [ ! -d repos-transitive/cbcflow ]; then git clone --depth 1 https://github.com/rhiannon-udall/cbcflow.git repos-transitive/cbcflow ; fi
echo cbcflow > repos-transitive/cbcflow/_pypi_name
echo cbcflow > repos-transitive/cbcflow/_conda_forge_name
if [ ! -d repos-transitive/chilife ]; then git clone --depth 1 https://github.com/stollLab/chiLife.git repos-transitive/chilife ; fi
echo chilife > repos-transitive/chilife/_pypi_name
echo chilife > repos-transitive/chilife/_conda_forge_name
if [ ! -d repos-transitive/chowlk-unofficial-fork ]; then git clone --depth 1 https://github.com/pablo-de-andres/Chowlk.git repos-transitive/chowlk-unofficial-fork ; fi
echo chowlk-unofficial-fork > repos-transitive/chowlk-unofficial-fork/_pypi_name
echo chowlk-unofficial-fork > repos-transitive/chowlk-unofficial-fork/_conda_forge_name
if [ ! -d repos-transitive/cmeutils ]; then git clone --depth 1 https://github.com/cmelab/cmeutils.git repos-transitive/cmeutils ; fi
echo cmeutils > repos-transitive/cmeutils/_conda_forge_name
if [ ! -d repos-transitive/cosolvkit ]; then git clone --depth 1 https://github.com/forlilab/cosolvkit.git repos-transitive/cosolvkit ; fi
echo cosolvkit > repos-transitive/cosolvkit/_pypi_name
echo cosolvkit > repos-transitive/cosolvkit/_conda_forge_name
if [ ! -d repos-transitive/crystal-toolkit ]; then git clone --depth 1 https://github.com/materialsproject/crystaltoolkit.git repos-transitive/crystal-toolkit ; fi
echo crystal-toolkit > repos-transitive/crystal-toolkit/_pypi_name
echo crystal-toolkit > repos-transitive/crystal-toolkit/_conda_forge_name
if [ ! -d repos-transitive/data2rdf ]; then git clone --depth 1 https://github.com/MI-FraunhoferIWM/data2rdf.git repos-transitive/data2rdf ; fi
echo data2rdf > repos-transitive/data2rdf/_pypi_name
echo data2rdf > repos-transitive/data2rdf/_conda_forge_name
if [ ! -d repos-transitive/dbt-athena-community ]; then git clone --depth 1 https://github.com/dbt-athena/dbt-athena.git repos-transitive/dbt-athena-community ; fi
echo dbt-athena-community > repos-transitive/dbt-athena-community/_pypi_name
echo dbt-athena-community > repos-transitive/dbt-athena-community/_conda_forge_name
if [ ! -d repos-transitive/dbt-databricks ]; then git clone --depth 1 https://github.com/databricks/dbt-databricks.git repos-transitive/dbt-databricks ; fi
echo dbt-databricks > repos-transitive/dbt-databricks/_pypi_name
echo dbt-databricks > repos-transitive/dbt-databricks/_conda_forge_name
if [ ! -d repos-transitive/dbt-ibis ]; then git clone --depth 1 https://github.com/binste/dbt-ibis.git repos-transitive/dbt-ibis ; fi
echo dbt-ibis > repos-transitive/dbt-ibis/_pypi_name
echo dbt-ibis > repos-transitive/dbt-ibis/_conda_forge_name
if [ ! -d repos-transitive/dbt-postgres ]; then git clone --depth 1 https://github.com/dbt-labs/dbt-postgres.git repos-transitive/dbt-postgres ; fi
echo dbt-postgres > repos-transitive/dbt-postgres/_pypi_name
echo dbt-postgres > repos-transitive/dbt-postgres/_conda_forge_name
if [ ! -d repos-transitive/deepcs ]; then git clone --depth 1 https://github.com/jeremyfix/deepcs.git repos-transitive/deepcs ; fi
echo deepcs > repos-transitive/deepcs/_pypi_name
echo deepcs > repos-transitive/deepcs/_conda_forge_name
if [ ! -d repos-transitive/deepinv ]; then git clone --depth 1 https://github.com/deepinv/deepinv.git repos-transitive/deepinv ; fi
echo deepinv > repos-transitive/deepinv/_pypi_name
echo deepinv > repos-transitive/deepinv/_conda_forge_name
if [ ! -d repos-transitive/diive ]; then git clone --depth 1 https://github.com/holukas/diive.git repos-transitive/diive ; fi
echo diive > repos-transitive/diive/_conda_forge_name
if [ ! -d repos-transitive/dirac-grid ]; then git clone --depth 1 https://github.com/DIRACGrid/DIRAC.git repos-transitive/dirac-grid ; fi
echo dirac > repos-transitive/dirac-grid/_pypi_name
echo dirac-grid > repos-transitive/dirac-grid/_conda_forge_name
if [ ! -d repos-transitive/dsms-sdk ]; then git clone --depth 1 https://github.com/MI-FraunhoferIWM/dsms-python-sdk.git repos-transitive/dsms-sdk ; fi
echo dsms-sdk > repos-transitive/dsms-sdk/_pypi_name
echo dsms-sdk > repos-transitive/dsms-sdk/_conda_forge_name
if [ ! -d repos-transitive/dwave-greedy ]; then git clone --depth 1 https://github.com/dwavesystems/dwave-greedy.git repos-transitive/dwave-greedy ; fi
echo dwave-greedy > repos-transitive/dwave-greedy/_pypi_name
echo dwave-greedy > repos-transitive/dwave-greedy/_conda_forge_name
if [ ! -d repos-transitive/dwave-system ]; then git clone --depth 1 https://github.com/dwavesystems/dwave-system.git repos-transitive/dwave-system ; fi
echo dwave-system > repos-transitive/dwave-system/_pypi_name
echo dwave-system > repos-transitive/dwave-system/_conda_forge_name
if [ ! -d repos-transitive/dymos ]; then git clone --depth 1 https://github.com/OpenMDAO/dymos.git repos-transitive/dymos ; fi
echo dymos > repos-transitive/dymos/_pypi_name
echo dymos > repos-transitive/dymos/_conda_forge_name
if [ ! -d repos-transitive/earthstat ]; then git clone --depth 1 https://github.com/abdelrahmanamr3/earthstat.git repos-transitive/earthstat ; fi
echo earthstat > repos-transitive/earthstat/_pypi_name
echo earthstat > repos-transitive/earthstat/_conda_forge_name
if [ ! -d repos-transitive/echoregions ]; then git clone --depth 1 https://github.com/OSOceanAcoustics/echoregions.git repos-transitive/echoregions ; fi
echo echoregions > repos-transitive/echoregions/_pypi_name
echo echoregions > repos-transitive/echoregions/_conda_forge_name
if [ ! -d repos-transitive/eis_toolkit ]; then git clone --depth 1 https://github.com/GispoCoding/eis_toolkit.git repos-transitive/eis_toolkit ; fi
echo eis_toolkit > repos-transitive/eis_toolkit/_conda_forge_name
if [ ! -d repos-transitive/elyra-code-snippet-extension ]; then git clone --depth 1 https://github.com/elyra-ai/elyra.git repos-transitive/elyra-code-snippet-extension ; fi
echo elyra-code-snippet-extension > repos-transitive/elyra-code-snippet-extension/_pypi_name
echo elyra-code-snippet-extension > repos-transitive/elyra-code-snippet-extension/_conda_forge_name
if [ ! -d repos-transitive/elyra-pipeline-editor-extension ]; then git clone --depth 1 https://github.com/elyra-ai/elyra.git repos-transitive/elyra-pipeline-editor-extension ; fi
echo elyra-pipeline-editor-extension > repos-transitive/elyra-pipeline-editor-extension/_pypi_name
echo elyra-pipeline-editor-extension > repos-transitive/elyra-pipeline-editor-extension/_conda_forge_name
if [ ! -d repos-transitive/elyra-python-editor-extension ]; then git clone --depth 1 https://github.com/elyra-ai/elyra.git repos-transitive/elyra-python-editor-extension ; fi
echo elyra-python-editor-extension > repos-transitive/elyra-python-editor-extension/_pypi_name
echo elyra-python-editor-extension > repos-transitive/elyra-python-editor-extension/_conda_forge_name
if [ ! -d repos-transitive/elyra-r-editor-extension ]; then git clone --depth 1 https://github.com/elyra-ai/elyra.git repos-transitive/elyra-r-editor-extension ; fi
echo elyra-r-editor-extension > repos-transitive/elyra-r-editor-extension/_pypi_name
echo elyra-r-editor-extension > repos-transitive/elyra-r-editor-extension/_conda_forge_name
if [ ! -d repos-transitive/elyra-scala-editor-extension ]; then git clone --depth 1 https://github.com/elyra-ai/elyra.git repos-transitive/elyra-scala-editor-extension ; fi
echo elyra-scala-editor-extension > repos-transitive/elyra-scala-editor-extension/_pypi_name
echo elyra-scala-editor-extension > repos-transitive/elyra-scala-editor-extension/_conda_forge_name
if [ ! -d repos-transitive/emmet-api ]; then git clone --depth 1 https://github.com/materialsproject/emmet.git repos-transitive/emmet-api ; fi
echo emmet-api > repos-transitive/emmet-api/_pypi_name
echo emmet-api > repos-transitive/emmet-api/_conda_forge_name
if [ ! -d repos-transitive/emmet-builders ]; then git clone --depth 1 https://github.com/materialsproject/emmet.git repos-transitive/emmet-builders ; fi
echo emmet-builders > repos-transitive/emmet-builders/_pypi_name
echo emmet-builders > repos-transitive/emmet-builders/_conda_forge_name
if [ ! -d repos-transitive/emmet-core ]; then git clone --depth 1 https://github.com/materialsproject/emmet.git repos-transitive/emmet-core ; fi
echo emmet-core > repos-transitive/emmet-core/_pypi_name
echo emmet-core > repos-transitive/emmet-core/_conda_forge_name
if [ ! -d repos-transitive/espaloma_charge ]; then git clone --depth 1 https://github.com/choderalab/espaloma_charge.git repos-transitive/espaloma_charge ; fi
echo espaloma_charge > repos-transitive/espaloma_charge/_conda_forge_name
if [ ! -d repos-transitive/extruct ]; then git clone --depth 1 https://github.com/scrapinghub/extruct.git repos-transitive/extruct ; fi
echo extruct > repos-transitive/extruct/_pypi_name
echo extruct > repos-transitive/extruct/_conda_forge_name
if [ ! -d repos-transitive/flash-attn ]; then git clone --depth 1 https://github.com/Dao-AILab/flash-attention.git repos-transitive/flash-attn ; fi
echo flash-attn > repos-transitive/flash-attn/_pypi_name
echo flash-attn > repos-transitive/flash-attn/_conda_forge_name
if [ ! -d repos-transitive/flowsom ]; then git clone --depth 1 https://github.com/saeyslab/FlowSOM_Python.git repos-transitive/flowsom ; fi
echo flowsom > repos-transitive/flowsom/_conda_forge_name
if [ ! -d repos-transitive/forte ]; then git clone --depth 1 https://github.com/evangelistalab/forte.git repos-transitive/forte ; fi
echo forte > repos-transitive/forte/_conda_forge_name
if [ ! -d repos-transitive/fragmenstein ]; then git clone --depth 1 https://github.com/matteoferla/Fragmenstein.git repos-transitive/fragmenstein ; fi
echo fragmenstein > repos-transitive/fragmenstein/_pypi_name
echo fragmenstein > repos-transitive/fragmenstein/_conda_forge_name
if [ ! -d repos-transitive/galore-torch ]; then git clone --depth 1 https://github.com/jiaweizzhao/GaLore.git repos-transitive/galore-torch ; fi
echo galore-torch > repos-transitive/galore-torch/_pypi_name
echo galore-torch > repos-transitive/galore-torch/_conda_forge_name
if [ ! -d repos-transitive/gauche ]; then git clone --depth 1 https://github.com/leojklarner/gauche.git repos-transitive/gauche ; fi
echo gauche > repos-transitive/gauche/_pypi_name
echo gauche > repos-transitive/gauche/_conda_forge_name
if [ ! -d repos-transitive/gensim ]; then git clone --depth 1 https://github.com/RaRe-Technologies/gensim.git repos-transitive/gensim ; fi
echo gensim > repos-transitive/gensim/_pypi_name
echo gensim > repos-transitive/gensim/_conda_forge_name
if [ ! -d repos-transitive/geosnap ]; then git clone --depth 1 https://github.com/spatialucr/geosnap.git repos-transitive/geosnap ; fi
echo geosnap > repos-transitive/geosnap/_pypi_name
echo geosnap > repos-transitive/geosnap/_conda_forge_name
if [ ! -d repos-transitive/glasspy ]; then git clone --depth 1 https://github.com/drcassar/glasspy.git repos-transitive/glasspy ; fi
echo glasspy > repos-transitive/glasspy/_pypi_name
echo glasspy > repos-transitive/glasspy/_conda_forge_name
if [ ! -d repos-transitive/graphium ]; then git clone --depth 1 https://github.com/datamol-io/graphium.git repos-transitive/graphium ; fi
echo graphium > repos-transitive/graphium/_pypi_name
echo graphium > repos-transitive/graphium/_conda_forge_name
if [ ! -d repos-transitive/hagerstrand ]; then git clone --depth 1 https://github.com/jimmy-feng/hagerstrand.git repos-transitive/hagerstrand ; fi
echo hagerstrand > repos-transitive/hagerstrand/_pypi_name
echo hagerstrand > repos-transitive/hagerstrand/_conda_forge_name
if [ ! -d repos-transitive/hazm ]; then git clone --depth 1 https://github.com/sobhe/hazm.git repos-transitive/hazm ; fi
echo hazm > repos-transitive/hazm/_pypi_name
echo hazm > repos-transitive/hazm/_conda_forge_name
if [ ! -d repos-transitive/hipscat ]; then git clone --depth 1 https://github.com/astronomy-commons/hipscat.git repos-transitive/hipscat ; fi
echo hipscat > repos-transitive/hipscat/_conda_forge_name
if [ ! -d repos-transitive/hssm ]; then git clone --depth 1 https://github.com/lnccbrown/HSSM.git repos-transitive/hssm ; fi
echo hssm > repos-transitive/hssm/_pypi_name
echo hssm > repos-transitive/hssm/_conda_forge_name
if [ ! -d repos-transitive/hypercoast ]; then git clone --depth 1 https://github.com/opengeos/HyperCoast.git repos-transitive/hypercoast ; fi
echo hypercoast > repos-transitive/hypercoast/_pypi_name
echo hypercoast > repos-transitive/hypercoast/_conda_forge_name
if [ ! -d repos-transitive/hysetter ]; then git clone --depth 1 https://github.com/hyriver/hysetter.git repos-transitive/hysetter ; fi
echo hysetter > repos-transitive/hysetter/_pypi_name
echo hysetter > repos-transitive/hysetter/_conda_forge_name
if [ ! -d repos-transitive/imagepy ]; then git clone --depth 1 https://github.com/Image-Py/imagepy.git repos-transitive/imagepy ; fi
echo imagepy > repos-transitive/imagepy/_pypi_name
echo imagepy > repos-transitive/imagepy/_conda_forge_name
if [ ! -d repos-transitive/indexedconv ]; then git clone --depth 1 https://github.com/IndexedConv/IndexedConv.git repos-transitive/indexedconv ; fi
echo indexedconv > repos-transitive/indexedconv/_pypi_name
echo indexedconv > repos-transitive/indexedconv/_conda_forge_name
if [ ! -d repos-transitive/insightface ]; then git clone --depth 1 https://github.com/deepinsight/insightface.git repos-transitive/insightface ; fi
echo insightface > repos-transitive/insightface/_pypi_name
echo insightface > repos-transitive/insightface/_conda_forge_name
if [ ! -d repos-transitive/ioos_metrics ]; then git clone --depth 1 https://github.com/ioos/ioos_metrics.git repos-transitive/ioos_metrics ; fi
echo ioos-metrics > repos-transitive/ioos_metrics/_pypi_name
echo ioos_metrics > repos-transitive/ioos_metrics/_conda_forge_name
if [ ! -d repos-transitive/jarvis-leaderboard ]; then git clone --depth 1 https://github.com/usnistgov/jarvis_leaderboard.git repos-transitive/jarvis-leaderboard ; fi
echo jarvis-leaderboard > repos-transitive/jarvis-leaderboard/_conda_forge_name
if [ ! -d repos-transitive/keybert ]; then git clone --depth 1 https://github.com/MaartenGr/keyBERT.git repos-transitive/keybert ; fi
echo keybert > repos-transitive/keybert/_pypi_name
echo keybert > repos-transitive/keybert/_conda_forge_name
if [ ! -d repos-transitive/langchain-huggingface ]; then git clone --depth 1 https://github.com/langchain-ai/langchain.git repos-transitive/langchain-huggingface ; fi
echo langchain-huggingface > repos-transitive/langchain-huggingface/_pypi_name
echo langchain-huggingface > repos-transitive/langchain-huggingface/_conda_forge_name
if [ ! -d repos-transitive/lhcbdirac ]; then git clone --depth 1 https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC.git repos-transitive/lhcbdirac ; fi
echo lhcbdirac > repos-transitive/lhcbdirac/_pypi_name
echo lhcbdirac > repos-transitive/lhcbdirac/_conda_forge_name
if [ ! -d repos-transitive/libmetatensor-torch ]; then git clone --depth 1 https://github.com/lab-cosmo/metatensor.git repos-transitive/libmetatensor-torch ; fi
echo libmetatensor-torch > repos-transitive/libmetatensor-torch/_conda_forge_name
if [ ! -d repos-transitive/lightpath ]; then git clone --depth 1 https://github.com/pcdshub/lightpath.git repos-transitive/lightpath ; fi
echo lightpath > repos-transitive/lightpath/_conda_forge_name
if [ ! -d repos-transitive/llama-index-cli ]; then git clone --depth 1 https://github.com/run-llama/llama_index/tree/main/llama-index-cli.git repos-transitive/llama-index-cli ; fi
echo llama-index-cli > repos-transitive/llama-index-cli/_pypi_name
echo llama-index-cli > repos-transitive/llama-index-cli/_conda_forge_name
if [ ! -d repos-transitive/llama-index-indices-managed-llama-cloud ]; then git clone --depth 1 https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/indices/llama-index-indices-managed-llama-cloud.git repos-transitive/llama-index-indices-managed-llama-cloud ; fi
echo llama-index-indices-managed-llama-cloud > repos-transitive/llama-index-indices-managed-llama-cloud/_pypi_name
echo llama-index-indices-managed-llama-cloud > repos-transitive/llama-index-indices-managed-llama-cloud/_conda_forge_name
if [ ! -d repos-transitive/llama-index-readers-file ]; then git clone --depth 1 https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/readers/llama-index-readers-file.git repos-transitive/llama-index-readers-file ; fi
echo llama-index-readers-file > repos-transitive/llama-index-readers-file/_pypi_name
echo llama-index-readers-file > repos-transitive/llama-index-readers-file/_conda_forge_name
if [ ! -d repos-transitive/llama-index-readers-llama-parse ]; then git clone --depth 1 https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/readers/llama-index-readers-llama-parse.git repos-transitive/llama-index-readers-llama-parse ; fi
echo llama-index-readers-llama-parse > repos-transitive/llama-index-readers-llama-parse/_pypi_name
echo llama-index-readers-llama-parse > repos-transitive/llama-index-readers-llama-parse/_conda_forge_name
if [ ! -d repos-transitive/llama-parse ]; then git clone --depth 1 https://github.com/run-llama/llama_parse.git repos-transitive/llama-parse ; fi
echo llama-parse > repos-transitive/llama-parse/_pypi_name
echo llama-parse > repos-transitive/llama-parse/_conda_forge_name
if [ ! -d repos-transitive/llmlingua ]; then git clone --depth 1 https://github.com/microsoft/LLMLingua.git repos-transitive/llmlingua ; fi
echo llmlingua > repos-transitive/llmlingua/_pypi_name
echo llmlingua > repos-transitive/llmlingua/_conda_forge_name
if [ ! -d repos-transitive/llmtuner ]; then git clone --depth 1 https://github.com/hiyouga/LLaMA-Factory.git repos-transitive/llmtuner ; fi
echo llmtuner > repos-transitive/llmtuner/_conda_forge_name
if [ ! -d repos-transitive/lsdb ]; then git clone --depth 1 https://github.com/astronomy-commons/lsdb.git repos-transitive/lsdb ; fi
echo lsdb > repos-transitive/lsdb/_conda_forge_name
if [ ! -d repos-transitive/lsds ]; then git clone --depth 1 https://github.com/funkelab/lsd.git repos-transitive/lsds ; fi
echo lsds > repos-transitive/lsds/_conda_forge_name
if [ ! -d repos-transitive/madminer ]; then git clone --depth 1 https://github.com/madminer-tool/madminer.git repos-transitive/madminer ; fi
echo madminer > repos-transitive/madminer/_pypi_name
echo madminer > repos-transitive/madminer/_conda_forge_name
if [ ! -d repos-transitive/maite ]; then git clone --depth 1 https://github.com/mit-ll-ai-technology/maite.git repos-transitive/maite ; fi
echo maite > repos-transitive/maite/_pypi_name
echo maite > repos-transitive/maite/_conda_forge_name
if [ ! -d repos-transitive/mdsapt ]; then git clone --depth 1 https://github.com/calpolyccg/MDSAPT.git repos-transitive/mdsapt ; fi
echo mdsapt > repos-transitive/mdsapt/_conda_forge_name
if [ ! -d repos-transitive/ml4xcube ]; then git clone --depth 1 https://github.com/deepesdl/ML-Toolkits/tree/develop/mltools/ml4xcube.git repos-transitive/ml4xcube ; fi
echo ml4xcube > repos-transitive/ml4xcube/_pypi_name
echo ml4xcube > repos-transitive/ml4xcube/_conda_forge_name
if [ ! -d repos-transitive/mlx-image ]; then git clone --depth 1 https://github.com/riccardomusmeci/mlx-image.git repos-transitive/mlx-image ; fi
echo mlx-image > repos-transitive/mlx-image/_pypi_name
echo mlx-image > repos-transitive/mlx-image/_conda_forge_name
if [ ! -d repos-transitive/mlx-vlm ]; then git clone --depth 1 https://github.com/Blaizzy/mlx-vlm.git repos-transitive/mlx-vlm ; fi
echo mlx-vlm > repos-transitive/mlx-vlm/_pypi_name
echo mlx-vlm > repos-transitive/mlx-vlm/_conda_forge_name
if [ ! -d repos-transitive/moleculeace ]; then git clone --depth 1 https://github.com/molML/MoleculeACE.git repos-transitive/moleculeace ; fi
echo moleculeace > repos-transitive/moleculeace/_pypi_name
echo moleculeace > repos-transitive/moleculeace/_conda_forge_name
if [ ! -d repos-transitive/molsimplify ]; then git clone --depth 1 https://github.com/hjkgrp/molSimplify.git repos-transitive/molsimplify ; fi
echo molsimplify > repos-transitive/molsimplify/_conda_forge_name
if [ ! -d repos-transitive/morphometrics ]; then git clone --depth 1 https://github.com/morphometrics/morphometrics.git repos-transitive/morphometrics ; fi
echo morphometrics > repos-transitive/morphometrics/_pypi_name
echo morphometrics > repos-transitive/morphometrics/_conda_forge_name
if [ ! -d repos-transitive/mosdef-dihedral-fit ]; then git clone --depth 1 https://github.com/GOMC-WSU/MoSDeF-dihedral-fit.git repos-transitive/mosdef-dihedral-fit ; fi
echo mosdef-dihedral-fit > repos-transitive/mosdef-dihedral-fit/_conda_forge_name
if [ ! -d repos-transitive/napari-toothfairy-annotator ]; then git clone --depth 1 https://github.com/LucaLumetti/napari-toothfairy-annotator.git repos-transitive/napari-toothfairy-annotator ; fi
echo napari-toothfairy-annotator > repos-transitive/napari-toothfairy-annotator/_pypi_name
echo napari-toothfairy-annotator > repos-transitive/napari-toothfairy-annotator/_conda_forge_name
if [ ! -d repos-transitive/ncplot ]; then git clone --depth 1 https://github.com/pmlmodelling/ncplot.git repos-transitive/ncplot ; fi
echo ncplot > repos-transitive/ncplot/_pypi_name
echo ncplot > repos-transitive/ncplot/_conda_forge_name
if [ ! -d repos-transitive/neurdflib ]; then git clone --depth 1 https://github.com/tgbugs/rdflib.git repos-transitive/neurdflib ; fi
echo neurdflib > repos-transitive/neurdflib/_pypi_name
echo neurdflib > repos-transitive/neurdflib/_conda_forge_name
if [ ! -d repos-transitive/nomad-lab ]; then git clone --depth 1 https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR.git repos-transitive/nomad-lab ; fi
echo nomad-lab > repos-transitive/nomad-lab/_pypi_name
echo nomad-lab > repos-transitive/nomad-lab/_conda_forge_name
if [ ! -d repos-transitive/nrtk-explorer ]; then git clone --depth 1 https://github.com/Kitware/nrtk-explorer.git repos-transitive/nrtk-explorer ; fi
echo nrtk-explorer > repos-transitive/nrtk-explorer/_pypi_name
echo nrtk-explorer > repos-transitive/nrtk-explorer/_conda_forge_name
if [ ! -d repos-transitive/openff-nagl ]; then git clone --depth 1 https://github.com/openforcefield/openff-nagl.git repos-transitive/openff-nagl ; fi
echo openff-nagl > repos-transitive/openff-nagl/_conda_forge_name
if [ ! -d repos-transitive/orange3-network ]; then git clone --depth 1 https://github.com/biolab/orange3-network.git repos-transitive/orange3-network ; fi
echo orange3-network > repos-transitive/orange3-network/_pypi_name
echo orange3-network > repos-transitive/orange3-network/_conda_forge_name
if [ ! -d repos-transitive/orange3-singlecell ]; then git clone --depth 1 https://github.com/biolab/orange3-single-cell.git repos-transitive/orange3-singlecell ; fi
echo orange3-singlecell > repos-transitive/orange3-singlecell/_pypi_name
echo orange3-singlecell > repos-transitive/orange3-singlecell/_conda_forge_name
if [ ! -d repos-transitive/pandas-profiling ]; then git clone --depth 1 https://github.com/pandas-profiling/pandas-profiling.git repos-transitive/pandas-profiling ; fi
echo pandas-profiling > repos-transitive/pandas-profiling/_pypi_name
echo pandas-profiling > repos-transitive/pandas-profiling/_conda_forge_name
if [ ! -d repos-transitive/pdemtools ]; then git clone --depth 1 https://github.com/trchudley/pdemtools.git repos-transitive/pdemtools ; fi
echo pdemtools > repos-transitive/pdemtools/_pypi_name
echo pdemtools > repos-transitive/pdemtools/_conda_forge_name
if [ ! -d repos-transitive/penaltymodel-cache ]; then git clone --depth 1 https://github.com/dwavesystems/penaltymodel.git repos-transitive/penaltymodel-cache ; fi
echo penaltymodel-cache > repos-transitive/penaltymodel-cache/_pypi_name
echo penaltymodel-cache > repos-transitive/penaltymodel-cache/_conda_forge_name
if [ ! -d repos-transitive/penaltymodel-lp ]; then git clone --depth 1 https://github.com/dwavesystems/penaltymodel.git repos-transitive/penaltymodel-lp ; fi
echo penaltymodel-lp > repos-transitive/penaltymodel-lp/_pypi_name
echo penaltymodel-lp > repos-transitive/penaltymodel-lp/_conda_forge_name
if [ ! -d repos-transitive/pennylane-qchem ]; then git clone --depth 1 https://github.com/PennyLaneAI/pennylane.git repos-transitive/pennylane-qchem ; fi
echo pennylane-qchem > repos-transitive/pennylane-qchem/_pypi_name
echo pennylane-qchem > repos-transitive/pennylane-qchem/_conda_forge_name
if [ ! -d repos-transitive/physicsml ]; then git clone --depth 1 https://github.com/Exscientia/physicsml.git repos-transitive/physicsml ; fi
echo physicsml > repos-transitive/physicsml/_pypi_name
echo physicsml > repos-transitive/physicsml/_conda_forge_name
if [ ! -d repos-transitive/plasticparcels ]; then git clone --depth 1 https://github.com/OceanParcels/plasticparcels.git repos-transitive/plasticparcels ; fi
echo plasticparcels > repos-transitive/plasticparcels/_conda_forge_name
if [ ! -d repos-transitive/pmda ]; then git clone --depth 1 https://github.com/MDAnalysis/pmda.git repos-transitive/pmda ; fi
echo pmda > repos-transitive/pmda/_pypi_name
echo pmda > repos-transitive/pmda/_conda_forge_name
if [ ! -d repos-transitive/polybeat ]; then git clone --depth 1 https://github.com/chunribu/polybeat.git repos-transitive/polybeat ; fi
echo polybeat > repos-transitive/polybeat/_pypi_name
echo polybeat > repos-transitive/polybeat/_conda_forge_name
if [ ! -d repos-transitive/protis ]; then git clone --depth 1 https://gitlab.com/protis/protis.git repos-transitive/protis ; fi
echo protis > repos-transitive/protis/_conda_forge_name
if [ ! -d repos-transitive/pyaimnet2 ]; then git clone --depth 1 https://github.com/jthorton/AIMNet2.git repos-transitive/pyaimnet2 ; fi
echo pyaimnet2 > repos-transitive/pyaimnet2/_conda_forge_name
if [ ! -d repos-transitive/pycycle ]; then git clone --depth 1 https://github.com/OpenMDAO/pyCycle.git repos-transitive/pycycle ; fi
echo om-pycycle > repos-transitive/pycycle/_pypi_name
echo pycycle > repos-transitive/pycycle/_conda_forge_name
if [ ! -d repos-transitive/pydefect ]; then git clone --depth 1 https://github.com/kumagai-group/pydefect.git repos-transitive/pydefect ; fi
echo pydefect > repos-transitive/pydefect/_pypi_name
echo pydefect > repos-transitive/pydefect/_conda_forge_name
if [ ! -d repos-transitive/pygsp ]; then git clone --depth 1 https://github.com/epfl-lts2/pygsp.git repos-transitive/pygsp ; fi
echo pygsp > repos-transitive/pygsp/_pypi_name
echo pygsp > repos-transitive/pygsp/_conda_forge_name
if [ ! -d repos-transitive/pymatgen-analysis-diffusion ]; then git clone --depth 1 https://github.com/materialsvirtuallab/pymatgen-diffusion.git repos-transitive/pymatgen-analysis-diffusion ; fi
echo pymatgen-analysis-diffusion > repos-transitive/pymatgen-analysis-diffusion/_pypi_name
echo pymatgen-analysis-diffusion > repos-transitive/pymatgen-analysis-diffusion/_conda_forge_name
if [ ! -d repos-transitive/pymatgen-diffusion ]; then git clone --depth 1 https://github.com/materialsvirtuallab/pymatgen-analysis-diffusion.git repos-transitive/pymatgen-diffusion ; fi
echo pymatgen-diffusion > repos-transitive/pymatgen-diffusion/_pypi_name
echo pymatgen-diffusion > repos-transitive/pymatgen-diffusion/_conda_forge_name
if [ ! -d repos-transitive/pyprocar ]; then git clone --depth 1 https://github.com/romerogroup/pyprocar.git repos-transitive/pyprocar ; fi
echo pyprocar > repos-transitive/pyprocar/_pypi_name
echo pyprocar > repos-transitive/pyprocar/_conda_forge_name
if [ ! -d repos-transitive/pyrdfa3 ]; then git clone --depth 1 https://github.com/prrvchr/pyrdfa3.git repos-transitive/pyrdfa3 ; fi
echo pyrdfa3 > repos-transitive/pyrdfa3/_pypi_name
echo pyrdfa3 > repos-transitive/pyrdfa3/_conda_forge_name
if [ ! -d repos-transitive/pyrosm ]; then git clone --depth 1 https://github.com/HTenkanen/pyrosm.git repos-transitive/pyrosm ; fi
echo pyrosm > repos-transitive/pyrosm/_pypi_name
echo pyrosm > repos-transitive/pyrosm/_conda_forge_name
if [ ! -d repos-transitive/pyrovelocity ]; then git clone --depth 1 https://github.com/pinellolab/pyrovelocity.git repos-transitive/pyrovelocity ; fi
echo pyrovelocity > repos-transitive/pyrovelocity/_pypi_name
echo pyrovelocity > repos-transitive/pyrovelocity/_conda_forge_name
if [ ! -d repos-transitive/pysisso ]; then git clone --depth 1 https://github.com/Matgenix/pysisso.git repos-transitive/pysisso ; fi
echo pysisso > repos-transitive/pysisso/_pypi_name
echo pysisso > repos-transitive/pysisso/_conda_forge_name
if [ ! -d repos-transitive/python-elf ]; then git clone --depth 1 https://github.com/constantinpape/elf.git repos-transitive/python-elf ; fi
echo python-elf > repos-transitive/python-elf/_conda_forge_name
if [ ! -d repos-transitive/python-tsp ]; then git clone --depth 1 https://github.com/fillipe-gsm/python-tsp.git repos-transitive/python-tsp ; fi
echo python-tsp > repos-transitive/python-tsp/_pypi_name
echo python-tsp > repos-transitive/python-tsp/_conda_forge_name
if [ ! -d repos-transitive/pytometry ]; then git clone --depth 1 https://github.com/buettnerlab/pytometry.git repos-transitive/pytometry ; fi
echo pytometry > repos-transitive/pytometry/_pypi_name
echo pytometry > repos-transitive/pytometry/_conda_forge_name
if [ ! -d repos-transitive/qcmanybody ]; then git clone --depth 1 https://github.com/MolSSI/QCManyBody.git repos-transitive/qcmanybody ; fi
echo qcmanybody > repos-transitive/qcmanybody/_pypi_name
echo qcmanybody > repos-transitive/qcmanybody/_conda_forge_name
if [ ! -d repos-transitive/raydar ]; then git clone --depth 1 https://github.com/point72/raydar.git repos-transitive/raydar ; fi
echo raydar > repos-transitive/raydar/_pypi_name
echo raydar > repos-transitive/raydar/_conda_forge_name
if [ ! -d repos-transitive/robomimic ]; then git clone --depth 1 https://github.com/ARISE-Initiative/robomimic.git repos-transitive/robomimic ; fi
echo robomimic > repos-transitive/robomimic/_pypi_name
echo robomimic > repos-transitive/robomimic/_conda_forge_name
if [ ! -d repos-transitive/rxnmapper ]; then git clone --depth 1 https://github.com/rxn4chemistry/rxnmapper.git repos-transitive/rxnmapper ; fi
echo rxnmapper > repos-transitive/rxnmapper/_pypi_name
echo rxnmapper > repos-transitive/rxnmapper/_conda_forge_name
if [ ! -d repos-transitive/s1_frame_enumerator ]; then git clone --depth 1 https://github.com/ACCESS-Cloud-Based-InSAR/s1_frame_enumerator.git repos-transitive/s1_frame_enumerator ; fi
echo s1-frame-enumerator > repos-transitive/s1_frame_enumerator/_pypi_name
echo s1_frame_enumerator > repos-transitive/s1_frame_enumerator/_conda_forge_name
if [ ! -d repos-transitive/safe-mol ]; then git clone --depth 1 https://github.com/datamol-io/safe.git repos-transitive/safe-mol ; fi
echo safe-mol > repos-transitive/safe-mol/_pypi_name
echo safe-mol > repos-transitive/safe-mol/_conda_forge_name
if [ ! -d repos-transitive/sarpy ]; then git clone --depth 1 https://github.com/ngageoint/sarpy.git repos-transitive/sarpy ; fi
echo sarpy > repos-transitive/sarpy/_pypi_name
echo sarpy > repos-transitive/sarpy/_conda_forge_name
if [ ! -d repos-transitive/scifireaders ]; then git clone --depth 1 https://github.com/pycroscopy/SciFiReaders.git repos-transitive/scifireaders ; fi
echo scifireaders > repos-transitive/scifireaders/_pypi_name
echo scifireaders > repos-transitive/scifireaders/_conda_forge_name
if [ ! -d repos-transitive/scikit-mobility ]; then git clone --depth 1 https://github.com/scikit-mobility/scikit-mobility.git repos-transitive/scikit-mobility ; fi
echo scikit-mobility > repos-transitive/scikit-mobility/_pypi_name
echo scikit-mobility > repos-transitive/scikit-mobility/_conda_forge_name
if [ ! -d repos-transitive/scvelo ]; then git clone --depth 1 https://github.com/theislab/scvelo.git repos-transitive/scvelo ; fi
echo scvelo > repos-transitive/scvelo/_pypi_name
echo scvelo > repos-transitive/scvelo/_conda_forge_name
if [ ! -d repos-transitive/sisl ]; then git clone --depth 1 https://github.com/zerothi/sisl.git repos-transitive/sisl ; fi
echo sisl > repos-transitive/sisl/_conda_forge_name
if [ ! -d repos-transitive/snkit ]; then git clone --depth 1 https://github.com/tomalrussell/snkit.git repos-transitive/snkit ; fi
echo snkit > repos-transitive/snkit/_pypi_name
echo snkit > repos-transitive/snkit/_conda_forge_name
if [ ! -d repos-transitive/somata ]; then git clone --depth 1 https://github.com/mh105/somata.git repos-transitive/somata ; fi
echo somata > repos-transitive/somata/_pypi_name
echo somata > repos-transitive/somata/_conda_forge_name
if [ ! -d repos-transitive/sos-pbs ]; then git clone --depth 1 https://github.com/vatlab/SOS.git repos-transitive/sos-pbs ; fi
echo sos-pbs > repos-transitive/sos-pbs/_pypi_name
echo sos-pbs > repos-transitive/sos-pbs/_conda_forge_name
if [ ! -d repos-transitive/spots-in-yeasts ]; then git clone --depth 1 https://github.com/MontpellierRessourcesImagerie/spots-in-yeasts.git repos-transitive/spots-in-yeasts ; fi
echo spots-in-yeasts > repos-transitive/spots-in-yeasts/_pypi_name
echo spots-in-yeasts > repos-transitive/spots-in-yeasts/_conda_forge_name
if [ ! -d repos-transitive/stlearn ]; then git clone --depth 1 https://github.com/BiomedicalMachineLearning/stLearn.git repos-transitive/stlearn ; fi
echo stlearn > repos-transitive/stlearn/_pypi_name
echo stlearn > repos-transitive/stlearn/_conda_forge_name
if [ ! -d repos-transitive/string2string ]; then git clone --depth 1 https://github.com/stanfordnlp/string2string.git repos-transitive/string2string ; fi
echo string2string > repos-transitive/string2string/_pypi_name
echo string2string > repos-transitive/string2string/_conda_forge_name
if [ ! -d repos-transitive/structuregraph-helpers ]; then git clone --depth 1 https://github.com/kjappelbaum/structuregraph-helpers.git repos-transitive/structuregraph-helpers ; fi
echo structuregraph-helpers > repos-transitive/structuregraph-helpers/_pypi_name
echo structuregraph-helpers > repos-transitive/structuregraph-helpers/_conda_forge_name
if [ ! -d repos-transitive/sunkit-magex ]; then git clone --depth 1 https://github.com/sunpy/sunkit-magex.git repos-transitive/sunkit-magex ; fi
echo sunkit-magex > repos-transitive/sunkit-magex/_pypi_name
echo sunkit-magex > repos-transitive/sunkit-magex/_conda_forge_name
if [ ! -d repos-transitive/superblockify ]; then git clone --depth 1 https://github.com/NERDSITU/superblockify.git repos-transitive/superblockify ; fi
echo superblockify > repos-transitive/superblockify/_pypi_name
echo superblockify > repos-transitive/superblockify/_conda_forge_name
if [ ! -d repos-transitive/suxarray ]; then git clone --depth 1 https://github.com/cadwrdeltamodeling/suxarray.git repos-transitive/suxarray ; fi
echo suxarray > repos-transitive/suxarray/_pypi_name
echo suxarray > repos-transitive/suxarray/_conda_forge_name
if [ ! -d repos-transitive/synthetic-data ]; then git clone --depth 1 https://github.com/capitalone/synthetic-data.git repos-transitive/synthetic-data ; fi
echo synthetic-data > repos-transitive/synthetic-data/_pypi_name
echo synthetic-data > repos-transitive/synthetic-data/_conda_forge_name
if [ ! -d repos-transitive/tad-dftd3 ]; then git clone --depth 1 https://github.com/dftd3/tad-dftd3.git repos-transitive/tad-dftd3 ; fi
echo tad-dftd3 > repos-transitive/tad-dftd3/_pypi_name
echo tad-dftd3 > repos-transitive/tad-dftd3/_conda_forge_name
if [ ! -d repos-transitive/tad-dftd4 ]; then git clone --depth 1 https://github.com/dftd4/tad-dftd4.git repos-transitive/tad-dftd4 ; fi
echo tad-dftd4 > repos-transitive/tad-dftd4/_pypi_name
echo tad-dftd4 > repos-transitive/tad-dftd4/_conda_forge_name
if [ ! -d repos-transitive/tad-mctc ]; then git clone --depth 1 https://github.com/tad-mctc/tad-mctc.git repos-transitive/tad-mctc ; fi
echo tad-mctc > repos-transitive/tad-mctc/_pypi_name
echo tad-mctc > repos-transitive/tad-mctc/_conda_forge_name
if [ ! -d repos-transitive/tad-multicharge ]; then git clone --depth 1 https://github.com/tad-mctc/tad-multicharge.git repos-transitive/tad-multicharge ; fi
echo tad-multicharge > repos-transitive/tad-multicharge/_pypi_name
echo tad-multicharge > repos-transitive/tad-multicharge/_conda_forge_name
if [ ! -d repos-transitive/teachopencadd ]; then git clone --depth 1 https://github.com/volkamerlab/teachopencadd.git repos-transitive/teachopencadd ; fi
echo teachopencadd > repos-transitive/teachopencadd/_conda_forge_name
if [ ! -d repos-transitive/tobac ]; then git clone --depth 1 https://github.com/tobac-project/tobac.git repos-transitive/tobac ; fi
echo tobac > repos-transitive/tobac/_conda_forge_name
if [ ! -d repos-transitive/torch-nl ]; then git clone --depth 1 https://github.com/felixmusil/torch_nl.git repos-transitive/torch-nl ; fi
echo torch-nl > repos-transitive/torch-nl/_pypi_name
echo torch-nl > repos-transitive/torch-nl/_conda_forge_name
if [ ! -d repos-transitive/torchopt ]; then git clone --depth 1 https://github.com/metaopt/torchopt.git repos-transitive/torchopt ; fi
echo torchopt > repos-transitive/torchopt/_pypi_name
echo torchopt > repos-transitive/torchopt/_conda_forge_name
if [ ! -d repos-transitive/transbigdata ]; then git clone --depth 1 https://github.com/ni1o1/transbigdata.git repos-transitive/transbigdata ; fi
echo transbigdata > repos-transitive/transbigdata/_pypi_name
echo transbigdata > repos-transitive/transbigdata/_conda_forge_name
if [ ! -d repos-transitive/trl ]; then git clone --depth 1 https://github.com/huggingface/trl.git repos-transitive/trl ; fi
echo trl > repos-transitive/trl/_conda_forge_name
if [ ! -d repos-transitive/tvb-framework ]; then git clone --depth 1 https://github.com/the-virtual-brain/tvb-root.git repos-transitive/tvb-framework ; fi
echo tvb-framework > repos-transitive/tvb-framework/_pypi_name
echo tvb-framework > repos-transitive/tvb-framework/_conda_forge_name
if [ ! -d repos-transitive/tvb-storage ]; then git clone --depth 1 https://github.com/the-virtual-brain/tvb-root.git repos-transitive/tvb-storage ; fi
echo tvb-storage > repos-transitive/tvb-storage/_pypi_name
echo tvb-storage > repos-transitive/tvb-storage/_conda_forge_name
if [ ! -d repos-transitive/txtai ]; then git clone --depth 1 https://github.com/neuml/txtai.git repos-transitive/txtai ; fi
echo txtai > repos-transitive/txtai/_pypi_name
echo txtai > repos-transitive/txtai/_conda_forge_name
if [ ! -d repos-transitive/upkie ]; then git clone --depth 1 https://github.com/upkie/upkie.git repos-transitive/upkie ; fi
echo upkie > repos-transitive/upkie/_pypi_name
echo upkie > repos-transitive/upkie/_conda_forge_name
if [ ! -d repos-transitive/uxarray ]; then git clone --depth 1 https://github.com/UXARRAY/uxarray.git repos-transitive/uxarray ; fi
echo uxarray > repos-transitive/uxarray/_conda_forge_name
if [ ! -d repos-transitive/vastdb ]; then git clone --depth 1 https://github.com/vast-data/vastdb_sdk.git repos-transitive/vastdb ; fi
echo vastdb > repos-transitive/vastdb/_pypi_name
echo vastdb > repos-transitive/vastdb/_conda_forge_name
if [ ! -d repos-transitive/veloxchem ]; then git clone --depth 1 https://gitlab.com/veloxchem/veloxchem.git repos-transitive/veloxchem ; fi
echo veloxchem > repos-transitive/veloxchem/_conda_forge_name
if [ ! -d repos-transitive/vise ]; then git clone --depth 1 https://github.com/kumagai-group/vise.git repos-transitive/vise ; fi
echo vise > repos-transitive/vise/_pypi_name
echo vise > repos-transitive/vise/_conda_forge_name
if [ ! -d repos-transitive/ydata-profiling ]; then git clone --depth 1 https://github.com/ydataai/ydata-profiling.git repos-transitive/ydata-profiling ; fi
echo ydata-profiling > repos-transitive/ydata-profiling/_pypi_name
echo ydata-profiling > repos-transitive/ydata-profiling/_conda_forge_name
