#!/usr/bin/env bash
# Copyright (c) 2024, NVIDIA CORPORATION.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# THIS FILE IS AUTOMATICALLY GENERATED BY _1_create_git_clone.py
mkdir -p repos-transitive
if [ ! -d repos-transitive/abipy ]; then git clone --depth 1 https://github.com/abinit/abipy.git repos-transitive/abipy ; fi
echo abipy > repos-transitive/abipy/_pypi_name
echo abipy > repos-transitive/abipy/_conda_forge_name
if [ ! -d repos-transitive/albumentations ]; then git clone --depth 1 https://github.com/albu/albumentations.git repos-transitive/albumentations ; fi
echo albumentations > repos-transitive/albumentations/_pypi_name
echo albumentations > repos-transitive/albumentations/_conda_forge_name
if [ ! -d repos-transitive/alchemiscale ]; then git clone --depth 1 https://github.com/openforcefield/alchemiscale.git repos-transitive/alchemiscale ; fi
echo alchemiscale > repos-transitive/alchemiscale/_conda_forge_name
if [ ! -d repos-transitive/alibi-detect ]; then git clone --depth 1 https://github.com/SeldonIO/alibi-detect.git repos-transitive/alibi-detect ; fi
echo alibi-detect > repos-transitive/alibi-detect/_pypi_name
echo alibi-detect > repos-transitive/alibi-detect/_conda_forge_name
if [ ! -d repos-transitive/amazon-braket-ocean-plugin ]; then git clone --depth 1 https://github.com/aws/amazon-braket-ocean-plugin-python.git repos-transitive/amazon-braket-ocean-plugin ; fi
echo amazon-braket-ocean-plugin > repos-transitive/amazon-braket-ocean-plugin/_pypi_name
echo amazon-braket-ocean-plugin > repos-transitive/amazon-braket-ocean-plugin/_conda_forge_name
if [ ! -d repos-transitive/apache-airflow-providers-apache-beam ]; then git clone --depth 1 https://github.com/apache/airflow.git repos-transitive/apache-airflow-providers-apache-beam ; fi
echo apache-airflow-providers-apache-beam > repos-transitive/apache-airflow-providers-apache-beam/_pypi_name
echo apache-airflow-providers-apache-beam > repos-transitive/apache-airflow-providers-apache-beam/_conda_forge_name
if [ ! -d repos-transitive/apache-airflow-providers-celery ]; then git clone --depth 1 https://github.com/apache/airflow.git repos-transitive/apache-airflow-providers-celery ; fi
echo apache-airflow-providers-celery > repos-transitive/apache-airflow-providers-celery/_pypi_name
echo apache-airflow-providers-celery > repos-transitive/apache-airflow-providers-celery/_conda_forge_name
if [ ! -d repos-transitive/apache-airflow-providers-google ]; then git clone --depth 1 https://github.com/apache/airflow.git repos-transitive/apache-airflow-providers-google ; fi
echo apache-airflow-providers-google > repos-transitive/apache-airflow-providers-google/_pypi_name
echo apache-airflow-providers-google > repos-transitive/apache-airflow-providers-google/_conda_forge_name
if [ ! -d repos-transitive/apache-beam ]; then git clone --depth 1 https://github.com/apache/beam.git repos-transitive/apache-beam ; fi
echo apache-beam > repos-transitive/apache-beam/_pypi_name
echo apache-beam > repos-transitive/apache-beam/_conda_forge_name
if [ ! -d repos-transitive/autogluon ]; then git clone --depth 1 https://github.com/autogluon/autogluon.git repos-transitive/autogluon ; fi
echo autogluon > repos-transitive/autogluon/_pypi_name
echo autogluon > repos-transitive/autogluon/_conda_forge_name
if [ ! -d repos-transitive/autogluon.multimodal ]; then git clone --depth 1 https://github.com/autogluon/autogluon.git repos-transitive/autogluon.multimodal ; fi
echo autogluon.multimodal > repos-transitive/autogluon.multimodal/_pypi_name
echo autogluon.multimodal > repos-transitive/autogluon.multimodal/_conda_forge_name
if [ ! -d repos-transitive/autogluon.text ]; then git clone --depth 1 https://github.com/autogluon/autogluon.git repos-transitive/autogluon.text ; fi
echo autogluon.text > repos-transitive/autogluon.text/_pypi_name
echo autogluon.text > repos-transitive/autogluon.text/_conda_forge_name
if [ ! -d repos-transitive/autogluon.vision ]; then git clone --depth 1 https://github.com/autogluon/autogluon.git repos-transitive/autogluon.vision ; fi
echo autogluon.vision > repos-transitive/autogluon.vision/_pypi_name
echo autogluon.vision > repos-transitive/autogluon.vision/_conda_forge_name
if [ ! -d repos-transitive/biofilm ]; then git clone --depth 1 https://github.com/smautner/biofilm.git repos-transitive/biofilm ; fi
echo biofilm > repos-transitive/biofilm/_pypi_name
echo biofilm > repos-transitive/biofilm/_conda_forge_name
if [ ! -d repos-transitive/cartes ]; then git clone --depth 1 https://github.com/xoolive/cartes.git repos-transitive/cartes ; fi
echo cartes > repos-transitive/cartes/_pypi_name
echo cartes > repos-transitive/cartes/_conda_forge_name
if [ ! -d repos-transitive/cellpose ]; then git clone --depth 1 https://github.com/MouseLand/cellpose.git repos-transitive/cellpose ; fi
echo cellpose > repos-transitive/cellpose/_pypi_name
echo cellpose > repos-transitive/cellpose/_conda_forge_name
if [ ! -d repos-transitive/cenpy ]; then git clone --depth 1 https://github.com/cenpy-devs/cenpy.git repos-transitive/cenpy ; fi
echo cenpy > repos-transitive/cenpy/_pypi_name
echo cenpy > repos-transitive/cenpy/_conda_forge_name
if [ ! -d repos-transitive/chitra ]; then git clone --depth 1 https://github.com/aniketmaurya/chitra.git repos-transitive/chitra ; fi
echo chitra > repos-transitive/chitra/_pypi_name
echo chitra > repos-transitive/chitra/_conda_forge_name
if [ ! -d repos-transitive/cloud-data-connector ]; then git clone --depth 1 https://github.com/IntelAI/models.git repos-transitive/cloud-data-connector ; fi
echo cloud-data-connector > repos-transitive/cloud-data-connector/_pypi_name
echo cloud-data-connector > repos-transitive/cloud-data-connector/_conda_forge_name
if [ ! -d repos-transitive/cmeutils ]; then git clone --depth 1 https://github.com/cmelab/cmeutils.git repos-transitive/cmeutils ; fi
echo cmeutils > repos-transitive/cmeutils/_conda_forge_name
if [ ! -d repos-transitive/crypten ]; then git clone --depth 1 https://github.com/facebookresearch/CrypTen.git repos-transitive/crypten ; fi
echo crypten > repos-transitive/crypten/_pypi_name
echo crypten > repos-transitive/crypten/_conda_forge_name
if [ ! -d repos-transitive/d3rlpy ]; then git clone --depth 1 https://github.com/takuseno/d3rlpy.git repos-transitive/d3rlpy ; fi
echo d3rlpy > repos-transitive/d3rlpy/_pypi_name
echo d3rlpy > repos-transitive/d3rlpy/_conda_forge_name
if [ ! -d repos-transitive/dask-imread ]; then git clone --depth 1 https://github.com/dask-image/dask-imread.git repos-transitive/dask-imread ; fi
echo dask-imread > repos-transitive/dask-imread/_pypi_name
echo dask-imread > repos-transitive/dask-imread/_conda_forge_name
if [ ! -d repos-transitive/detectron2 ]; then git clone --depth 1 https://github.com/facebookresearch/detectron2.git repos-transitive/detectron2 ; fi
echo detectron2 > repos-transitive/detectron2/_conda_forge_name
if [ ! -d repos-transitive/diffusers ]; then git clone --depth 1 https://github.com/huggingface/diffusers.git repos-transitive/diffusers ; fi
echo diffusers > repos-transitive/diffusers/_pypi_name
echo diffusers > repos-transitive/diffusers/_conda_forge_name
if [ ! -d repos-transitive/dwave-greedy ]; then git clone --depth 1 https://github.com/dwavesystems/dwave-greedy.git repos-transitive/dwave-greedy ; fi
echo dwave-greedy > repos-transitive/dwave-greedy/_pypi_name
echo dwave-greedy > repos-transitive/dwave-greedy/_conda_forge_name
if [ ! -d repos-transitive/dwave-ocean-sdk ]; then git clone --depth 1 https://github.com/dwavesystems/dwave-ocean-sdk.git repos-transitive/dwave-ocean-sdk ; fi
echo dwave-ocean-sdk > repos-transitive/dwave-ocean-sdk/_pypi_name
echo dwave-ocean-sdk > repos-transitive/dwave-ocean-sdk/_conda_forge_name
if [ ! -d repos-transitive/dwave-system ]; then git clone --depth 1 https://github.com/dwavesystems/dwave-system.git repos-transitive/dwave-system ; fi
echo dwave-system > repos-transitive/dwave-system/_pypi_name
echo dwave-system > repos-transitive/dwave-system/_conda_forge_name
if [ ! -d repos-transitive/dymos ]; then git clone --depth 1 https://github.com/OpenMDAO/dymos.git repos-transitive/dymos ; fi
echo dymos > repos-transitive/dymos/_pypi_name
echo dymos > repos-transitive/dymos/_conda_forge_name
if [ ! -d repos-transitive/easyocr ]; then git clone --depth 1 https://github.com/jaidedai/easyocr.git repos-transitive/easyocr ; fi
echo easyocr > repos-transitive/easyocr/_conda_forge_name
if [ ! -d repos-transitive/elyra-code-snippet-extension ]; then git clone --depth 1 https://github.com/elyra-ai/elyra.git repos-transitive/elyra-code-snippet-extension ; fi
echo elyra-code-snippet-extension > repos-transitive/elyra-code-snippet-extension/_pypi_name
echo elyra-code-snippet-extension > repos-transitive/elyra-code-snippet-extension/_conda_forge_name
if [ ! -d repos-transitive/elyra-pipeline-editor-extension ]; then git clone --depth 1 https://github.com/elyra-ai/elyra.git repos-transitive/elyra-pipeline-editor-extension ; fi
echo elyra-pipeline-editor-extension > repos-transitive/elyra-pipeline-editor-extension/_pypi_name
echo elyra-pipeline-editor-extension > repos-transitive/elyra-pipeline-editor-extension/_conda_forge_name
if [ ! -d repos-transitive/elyra-python-editor-extension ]; then git clone --depth 1 https://github.com/elyra-ai/elyra.git repos-transitive/elyra-python-editor-extension ; fi
echo elyra-python-editor-extension > repos-transitive/elyra-python-editor-extension/_pypi_name
echo elyra-python-editor-extension > repos-transitive/elyra-python-editor-extension/_conda_forge_name
if [ ! -d repos-transitive/elyra-r-editor-extension ]; then git clone --depth 1 https://github.com/elyra-ai/elyra.git repos-transitive/elyra-r-editor-extension ; fi
echo elyra-r-editor-extension > repos-transitive/elyra-r-editor-extension/_pypi_name
echo elyra-r-editor-extension > repos-transitive/elyra-r-editor-extension/_conda_forge_name
if [ ! -d repos-transitive/elyra-scala-editor-extension ]; then git clone --depth 1 https://github.com/elyra-ai/elyra.git repos-transitive/elyra-scala-editor-extension ; fi
echo elyra-scala-editor-extension > repos-transitive/elyra-scala-editor-extension/_pypi_name
echo elyra-scala-editor-extension > repos-transitive/elyra-scala-editor-extension/_conda_forge_name
if [ ! -d repos-transitive/emmet-api ]; then git clone --depth 1 https://github.com/materialsproject/emmet.git repos-transitive/emmet-api ; fi
echo emmet-api > repos-transitive/emmet-api/_pypi_name
echo emmet-api > repos-transitive/emmet-api/_conda_forge_name
if [ ! -d repos-transitive/emmet-builders ]; then git clone --depth 1 https://github.com/materialsproject/emmet.git repos-transitive/emmet-builders ; fi
echo emmet-builders > repos-transitive/emmet-builders/_pypi_name
echo emmet-builders > repos-transitive/emmet-builders/_conda_forge_name
if [ ! -d repos-transitive/emmet-core ]; then git clone --depth 1 https://github.com/materialsproject/emmet.git repos-transitive/emmet-core ; fi
echo emmet-core > repos-transitive/emmet-core/_pypi_name
echo emmet-core > repos-transitive/emmet-core/_conda_forge_name
if [ ! -d repos-transitive/eo-learn ]; then git clone --depth 1 https://github.com/sentinel-hub/eo-learn.git repos-transitive/eo-learn ; fi
echo eo-learn > repos-transitive/eo-learn/_pypi_name
echo eo-learn > repos-transitive/eo-learn/_conda_forge_name
if [ ! -d repos-transitive/eo-learn-core ]; then git clone --depth 1 https://github.com/sentinel-hub/eo-learn.git repos-transitive/eo-learn-core ; fi
echo eo-learn-core > repos-transitive/eo-learn-core/_pypi_name
echo eo-learn-core > repos-transitive/eo-learn-core/_conda_forge_name
if [ ! -d repos-transitive/eo-learn-coregistration ]; then git clone --depth 1 https://github.com/sentinel-hub/eo-learn.git repos-transitive/eo-learn-coregistration ; fi
echo eo-learn-coregistration > repos-transitive/eo-learn-coregistration/_pypi_name
echo eo-learn-coregistration > repos-transitive/eo-learn-coregistration/_conda_forge_name
if [ ! -d repos-transitive/eo-learn-features ]; then git clone --depth 1 https://github.com/sentinel-hub/eo-learn.git repos-transitive/eo-learn-features ; fi
echo eo-learn-features > repos-transitive/eo-learn-features/_pypi_name
echo eo-learn-features > repos-transitive/eo-learn-features/_conda_forge_name
if [ ! -d repos-transitive/eo-learn-geometry ]; then git clone --depth 1 https://github.com/sentinel-hub/eo-learn.git repos-transitive/eo-learn-geometry ; fi
echo eo-learn-geometry > repos-transitive/eo-learn-geometry/_pypi_name
echo eo-learn-geometry > repos-transitive/eo-learn-geometry/_conda_forge_name
if [ ! -d repos-transitive/eo-learn-io ]; then git clone --depth 1 https://github.com/sentinel-hub/eo-learn.git repos-transitive/eo-learn-io ; fi
echo eo-learn-io > repos-transitive/eo-learn-io/_pypi_name
echo eo-learn-io > repos-transitive/eo-learn-io/_conda_forge_name
if [ ! -d repos-transitive/eo-learn-mask ]; then git clone --depth 1 https://github.com/sentinel-hub/eo-learn.git repos-transitive/eo-learn-mask ; fi
echo eo-learn-mask > repos-transitive/eo-learn-mask/_pypi_name
echo eo-learn-mask > repos-transitive/eo-learn-mask/_conda_forge_name
if [ ! -d repos-transitive/eo-learn-ml-tools ]; then git clone --depth 1 https://github.com/sentinel-hub/eo-learn.git repos-transitive/eo-learn-ml-tools ; fi
echo eo-learn-ml-tools > repos-transitive/eo-learn-ml-tools/_pypi_name
echo eo-learn-ml-tools > repos-transitive/eo-learn-ml-tools/_conda_forge_name
if [ ! -d repos-transitive/eo-learn-visualization ]; then git clone --depth 1 https://github.com/sentinel-hub/eo-learn.git repos-transitive/eo-learn-visualization ; fi
echo eo-learn-visualization > repos-transitive/eo-learn-visualization/_pypi_name
echo eo-learn-visualization > repos-transitive/eo-learn-visualization/_conda_forge_name
if [ ! -d repos-transitive/espnet ]; then git clone --depth 1 https://github.com/espnet/espnet.git repos-transitive/espnet ; fi
echo espnet > repos-transitive/espnet/_pypi_name
echo espnet > repos-transitive/espnet/_conda_forge_name
if [ ! -d repos-transitive/fairseq ]; then git clone --depth 1 https://github.com/pytorch/fairseq.git repos-transitive/fairseq ; fi
echo fairseq > repos-transitive/fairseq/_conda_forge_name
if [ ! -d repos-transitive/flytekitplugins-modin ]; then git clone --depth 1 https://github.com/flyteorg/flytekit.git repos-transitive/flytekitplugins-modin ; fi
echo flytekitplugins-modin > repos-transitive/flytekitplugins-modin/_pypi_name
echo flytekitplugins-modin > repos-transitive/flytekitplugins-modin/_conda_forge_name
if [ ! -d repos-transitive/flytekitplugins-pandera ]; then git clone --depth 1 https://github.com/flyteorg/flytekit.git repos-transitive/flytekitplugins-pandera ; fi
echo flytekitplugins-pandera > repos-transitive/flytekitplugins-pandera/_pypi_name
echo flytekitplugins-pandera > repos-transitive/flytekitplugins-pandera/_conda_forge_name
if [ ! -d repos-transitive/gemgis ]; then git clone --depth 1 https://github.com/cgre-aachen/gemgis.git repos-transitive/gemgis ; fi
echo gemgis > repos-transitive/gemgis/_pypi_name
echo gemgis > repos-transitive/gemgis/_conda_forge_name
if [ ! -d repos-transitive/gensim ]; then git clone --depth 1 https://github.com/RaRe-Technologies/gensim.git repos-transitive/gensim ; fi
echo gensim > repos-transitive/gensim/_pypi_name
echo gensim > repos-transitive/gensim/_conda_forge_name
if [ ! -d repos-transitive/geopandas ]; then git clone --depth 1 https://github.com/geopandas/geopandas.git repos-transitive/geopandas ; fi
echo geopandas > repos-transitive/geopandas/_conda_forge_name
if [ ! -d repos-transitive/geosnap ]; then git clone --depth 1 https://github.com/spatialucr/geosnap.git repos-transitive/geosnap ; fi
echo geosnap > repos-transitive/geosnap/_pypi_name
echo geosnap > repos-transitive/geosnap/_conda_forge_name
if [ ! -d repos-transitive/geoutils ]; then git clone --depth 1 https://github.com/GlacioHack/geoutils.git repos-transitive/geoutils ; fi
echo geoutils > repos-transitive/geoutils/_conda_forge_name
if [ ! -d repos-transitive/graphium ]; then git clone --depth 1 https://github.com/datamol-io/graphium.git repos-transitive/graphium ; fi
echo graphium > repos-transitive/graphium/_pypi_name
echo graphium > repos-transitive/graphium/_conda_forge_name
if [ ! -d repos-transitive/hagerstrand ]; then git clone --depth 1 https://github.com/jimmy-feng/hagerstrand.git repos-transitive/hagerstrand ; fi
echo hagerstrand > repos-transitive/hagerstrand/_pypi_name
echo hagerstrand > repos-transitive/hagerstrand/_conda_forge_name
if [ ! -d repos-transitive/heat ]; then git clone --depth 1 https://github.com/helmholtz-analytics/heat.git repos-transitive/heat ; fi
echo heat > repos-transitive/heat/_pypi_name
echo heat > repos-transitive/heat/_conda_forge_name
if [ ! -d repos-transitive/hummingbird-ml ]; then git clone --depth 1 https://github.com/microsoft/hummingbird.git repos-transitive/hummingbird-ml ; fi
echo hummingbird-ml > repos-transitive/hummingbird-ml/_pypi_name
echo hummingbird-ml > repos-transitive/hummingbird-ml/_conda_forge_name
if [ ! -d repos-transitive/imagepy ]; then git clone --depth 1 https://github.com/Image-Py/imagepy.git repos-transitive/imagepy ; fi
echo imagepy > repos-transitive/imagepy/_pypi_name
echo imagepy > repos-transitive/imagepy/_conda_forge_name
if [ ! -d repos-transitive/imaxt-image ]; then git clone --depth 1 https://github.com/IMAXT/imaxt-image.git repos-transitive/imaxt-image ; fi
echo imaxt-image > repos-transitive/imaxt-image/_pypi_name
echo imaxt-image > repos-transitive/imaxt-image/_conda_forge_name
if [ ! -d repos-transitive/insightface ]; then git clone --depth 1 https://github.com/deepinsight/insightface.git repos-transitive/insightface ; fi
echo insightface > repos-transitive/insightface/_pypi_name
echo insightface > repos-transitive/insightface/_conda_forge_name
if [ ! -d repos-transitive/isce2 ]; then git clone --depth 1 https://github.com/isce-framework/isce2.git repos-transitive/isce2 ; fi
echo isce2 > repos-transitive/isce2/_conda_forge_name
if [ ! -d repos-transitive/kornia ]; then git clone --depth 1 https://github.com/kornia/kornia.git repos-transitive/kornia ; fi
echo kornia > repos-transitive/kornia/_pypi_name
echo kornia > repos-transitive/kornia/_conda_forge_name
if [ ! -d repos-transitive/libertem ]; then git clone --depth 1 https://github.com/LiberTEM/LiberTEM.git repos-transitive/libertem ; fi
echo libertem > repos-transitive/libertem/_pypi_name
echo libertem > repos-transitive/libertem/_conda_forge_name
if [ ! -d repos-transitive/lightning ]; then git clone --depth 1 https://github.com/Lightning-AI/lightning.git repos-transitive/lightning ; fi
echo lightning > repos-transitive/lightning/_pypi_name
echo lightning > repos-transitive/lightning/_conda_forge_name
if [ ! -d repos-transitive/lightpath ]; then git clone --depth 1 https://github.com/pcdshub/lightpath.git repos-transitive/lightpath ; fi
echo lightpath > repos-transitive/lightpath/_conda_forge_name
if [ ! -d repos-transitive/loralib ]; then git clone --depth 1 https://github.com/microsoft/LoRA.git repos-transitive/loralib ; fi
echo loralib > repos-transitive/loralib/_pypi_name
echo loralib > repos-transitive/loralib/_conda_forge_name
if [ ! -d repos-transitive/lsds ]; then git clone --depth 1 https://github.com/funkelab/lsd.git repos-transitive/lsds ; fi
echo lsds > repos-transitive/lsds/_conda_forge_name
if [ ! -d repos-transitive/matbench-genmetrics ]; then git clone --depth 1 https://github.com/sparks-baird/matbench-genmetrics.git repos-transitive/matbench-genmetrics ; fi
echo matbench-genmetrics > repos-transitive/matbench-genmetrics/_pypi_name
echo matbench-genmetrics > repos-transitive/matbench-genmetrics/_conda_forge_name
if [ ! -d repos-transitive/mmcv-recipe ]; then git clone --depth 1 https://github.com/open-mmlab/mmcv.git repos-transitive/mmcv-recipe ; fi
echo mmcv-recipe > repos-transitive/mmcv-recipe/_conda_forge_name
if [ ! -d repos-transitive/mmdet ]; then git clone --depth 1 https://github.com/open-mmlab/mmdetection.git repos-transitive/mmdet ; fi
echo mmdet > repos-transitive/mmdet/_conda_forge_name
if [ ! -d repos-transitive/mmgp ]; then git clone --depth 1 https://gitlab.com/drti/mmgp.git repos-transitive/mmgp ; fi
echo mmgp > repos-transitive/mmgp/_conda_forge_name
if [ ! -d repos-transitive/mne ]; then git clone --depth 1 https://github.com/mne-tools/mne-python.git repos-transitive/mne ; fi
echo mne > repos-transitive/mne/_pypi_name
echo mne > repos-transitive/mne/_conda_forge_name
if [ ! -d repos-transitive/mne-bids ]; then git clone --depth 1 https://github.com/mne-tools/mne-bids.git repos-transitive/mne-bids ; fi
echo mne-bids > repos-transitive/mne-bids/_pypi_name
echo mne-bids > repos-transitive/mne-bids/_conda_forge_name
if [ ! -d repos-transitive/molsimplify ]; then git clone --depth 1 https://github.com/hjkgrp/molSimplify.git repos-transitive/molsimplify ; fi
echo molsimplify > repos-transitive/molsimplify/_conda_forge_name
if [ ! -d repos-transitive/monai ]; then git clone --depth 1 https://github.com/Project-MONAI/MONAI.git repos-transitive/monai ; fi
echo monai > repos-transitive/monai/_conda_forge_name
if [ ! -d repos-transitive/morphometrics ]; then git clone --depth 1 https://github.com/morphometrics/morphometrics.git repos-transitive/morphometrics ; fi
echo morphometrics > repos-transitive/morphometrics/_pypi_name
echo morphometrics > repos-transitive/morphometrics/_conda_forge_name
if [ ! -d repos-transitive/mp_time_split ]; then git clone --depth 1 https://github.com/sparks-baird/mp-time-split.git repos-transitive/mp_time_split ; fi
echo mp_time_split > repos-transitive/mp_time_split/_pypi_name
echo mp_time_split > repos-transitive/mp_time_split/_conda_forge_name
if [ ! -d repos-transitive/neurdflib ]; then git clone --depth 1 https://github.com/tgbugs/rdflib.git repos-transitive/neurdflib ; fi
echo neurdflib > repos-transitive/neurdflib/_pypi_name
echo neurdflib > repos-transitive/neurdflib/_conda_forge_name
if [ ! -d repos-transitive/nomad-lab ]; then git clone --depth 1 https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR.git repos-transitive/nomad-lab ; fi
echo nomad-lab > repos-transitive/nomad-lab/_pypi_name
echo nomad-lab > repos-transitive/nomad-lab/_conda_forge_name
if [ ! -d repos-transitive/norse ]; then git clone --depth 1 https://github.com/norse/norse.git repos-transitive/norse ; fi
echo norse > repos-transitive/norse/_pypi_name
echo norse > repos-transitive/norse/_conda_forge_name
if [ ! -d repos-transitive/nvidia-apex ]; then git clone --depth 1 https://github.com/NVIDIA/apex.git repos-transitive/nvidia-apex ; fi
echo nvidia-apex > repos-transitive/nvidia-apex/_conda_forge_name
if [ ! -d repos-transitive/onnx2pytorch ]; then git clone --depth 1 https://github.com/ToriML/onnx2pytorch.git repos-transitive/onnx2pytorch ; fi
echo onnx2pytorch > repos-transitive/onnx2pytorch/_pypi_name
echo onnx2pytorch > repos-transitive/onnx2pytorch/_conda_forge_name
if [ ! -d repos-transitive/onnx2torch ]; then git clone --depth 1 https://github.com/ENOT-AutoDL/onnx2torch.git repos-transitive/onnx2torch ; fi
echo onnx2torch > repos-transitive/onnx2torch/_pypi_name
echo onnx2torch > repos-transitive/onnx2torch/_conda_forge_name
if [ ! -d repos-transitive/openff-nagl ]; then git clone --depth 1 https://github.com/openforcefield/openff-nagl.git repos-transitive/openff-nagl ; fi
echo openff-nagl > repos-transitive/openff-nagl/_conda_forge_name
if [ ! -d repos-transitive/optimum ]; then git clone --depth 1 https://github.com/huggingface/optimum.git repos-transitive/optimum ; fi
echo optimum > repos-transitive/optimum/_pypi_name
echo optimum > repos-transitive/optimum/_conda_forge_name
if [ ! -d repos-transitive/optimum-habana ]; then git clone --depth 1 https://github.com/huggingface/optimum-habana.git repos-transitive/optimum-habana ; fi
echo optimum-habana > repos-transitive/optimum-habana/_pypi_name
echo optimum-habana > repos-transitive/optimum-habana/_conda_forge_name
if [ ! -d repos-transitive/orange3-network ]; then git clone --depth 1 https://github.com/biolab/orange3-network.git repos-transitive/orange3-network ; fi
echo orange3-network > repos-transitive/orange3-network/_pypi_name
echo orange3-network > repos-transitive/orange3-network/_conda_forge_name
if [ ! -d repos-transitive/palmari ]; then git clone --depth 1 https://github.com/hippover/palmari.git repos-transitive/palmari ; fi
echo palmari > repos-transitive/palmari/_pypi_name
echo palmari > repos-transitive/palmari/_conda_forge_name
if [ ! -d repos-transitive/pandas-profiling ]; then git clone --depth 1 https://github.com/pandas-profiling/pandas-profiling.git repos-transitive/pandas-profiling ; fi
echo pandas-profiling > repos-transitive/pandas-profiling/_pypi_name
echo pandas-profiling > repos-transitive/pandas-profiling/_conda_forge_name
if [ ! -d repos-transitive/penaltymodel-cache ]; then git clone --depth 1 https://github.com/dwavesystems/penaltymodel.git repos-transitive/penaltymodel-cache ; fi
echo penaltymodel-cache > repos-transitive/penaltymodel-cache/_pypi_name
echo penaltymodel-cache > repos-transitive/penaltymodel-cache/_conda_forge_name
if [ ! -d repos-transitive/penaltymodel-lp ]; then git clone --depth 1 https://github.com/dwavesystems/penaltymodel.git repos-transitive/penaltymodel-lp ; fi
echo penaltymodel-lp > repos-transitive/penaltymodel-lp/_pypi_name
echo penaltymodel-lp > repos-transitive/penaltymodel-lp/_conda_forge_name
if [ ! -d repos-transitive/pennylane-qchem ]; then git clone --depth 1 https://github.com/PennyLaneAI/pennylane.git repos-transitive/pennylane-qchem ; fi
echo pennylane-qchem > repos-transitive/pennylane-qchem/_pypi_name
echo pennylane-qchem > repos-transitive/pennylane-qchem/_conda_forge_name
if [ ! -d repos-transitive/plaid ]; then git clone --depth 1 https://gitlab.com/drti/plaid.git repos-transitive/plaid ; fi
echo plaid > repos-transitive/plaid/_conda_forge_name
if [ ! -d repos-transitive/pmda ]; then git clone --depth 1 https://github.com/MDAnalysis/pmda.git repos-transitive/pmda ; fi
echo pmda > repos-transitive/pmda/_pypi_name
echo pmda > repos-transitive/pmda/_conda_forge_name
if [ ! -d repos-transitive/prospect ]; then git clone --depth 1 https://github.com/deppen8/prospect.git repos-transitive/prospect ; fi
echo prospect > repos-transitive/prospect/_pypi_name
echo prospect > repos-transitive/prospect/_conda_forge_name
if [ ! -d repos-transitive/pycycle ]; then git clone --depth 1 https://github.com/OpenMDAO/pyCycle.git repos-transitive/pycycle ; fi
echo om-pycycle > repos-transitive/pycycle/_pypi_name
echo pycycle > repos-transitive/pycycle/_conda_forge_name
if [ ! -d repos-transitive/pygsp ]; then git clone --depth 1 https://github.com/epfl-lts2/pygsp.git repos-transitive/pygsp ; fi
echo pygsp > repos-transitive/pygsp/_pypi_name
echo pygsp > repos-transitive/pygsp/_conda_forge_name
if [ ! -d repos-transitive/pyheatdemand ]; then git clone --depth 1 https://github.com/AlexanderJuestel/pyheatdemand.git repos-transitive/pyheatdemand ; fi
echo pyheatdemand > repos-transitive/pyheatdemand/_pypi_name
echo pyheatdemand > repos-transitive/pyheatdemand/_conda_forge_name
if [ ! -d repos-transitive/pyiron_atomistics ]; then git clone --depth 1 https://github.com/pyiron/pyiron_atomistics.git repos-transitive/pyiron_atomistics ; fi
echo pyiron-atomistics > repos-transitive/pyiron_atomistics/_pypi_name
echo pyiron_atomistics > repos-transitive/pyiron_atomistics/_conda_forge_name
if [ ! -d repos-transitive/pymatgen-analysis-diffusion ]; then git clone --depth 1 https://github.com/materialsvirtuallab/pymatgen-diffusion.git repos-transitive/pymatgen-analysis-diffusion ; fi
echo pymatgen-analysis-diffusion > repos-transitive/pymatgen-analysis-diffusion/_pypi_name
echo pymatgen-analysis-diffusion > repos-transitive/pymatgen-analysis-diffusion/_conda_forge_name
if [ ! -d repos-transitive/pymatgen-diffusion ]; then git clone --depth 1 https://github.com/materialsvirtuallab/pymatgen-analysis-diffusion.git repos-transitive/pymatgen-diffusion ; fi
echo pymatgen-diffusion > repos-transitive/pymatgen-diffusion/_pypi_name
echo pymatgen-diffusion > repos-transitive/pymatgen-diffusion/_conda_forge_name
if [ ! -d repos-transitive/pyposeidon ]; then git clone --depth 1 https://github.com/ec-jrc/pyPoseidon.git repos-transitive/pyposeidon ; fi
echo pyposeidon > repos-transitive/pyposeidon/_conda_forge_name
if [ ! -d repos-transitive/pyprocar ]; then git clone --depth 1 https://github.com/romerogroup/pyprocar.git repos-transitive/pyprocar ; fi
echo pyprocar > repos-transitive/pyprocar/_pypi_name
echo pyprocar > repos-transitive/pyprocar/_conda_forge_name
if [ ! -d repos-transitive/pyrosm ]; then git clone --depth 1 https://github.com/HTenkanen/pyrosm.git repos-transitive/pyrosm ; fi
echo pyrosm > repos-transitive/pyrosm/_pypi_name
echo pyrosm > repos-transitive/pyrosm/_conda_forge_name
if [ ! -d repos-transitive/pysipfenn ]; then git clone --depth 1 https://github.com/PhasesResearchLab/pySIPFENN.git repos-transitive/pysipfenn ; fi
echo pysipfenn > repos-transitive/pysipfenn/_pypi_name
echo pysipfenn > repos-transitive/pysipfenn/_conda_forge_name
if [ ! -d repos-transitive/pytensor-suite ]; then git clone --depth 1 https://github.com/pymc-devs/pytensor.git repos-transitive/pytensor-suite ; fi
echo pytensor > repos-transitive/pytensor-suite/_pypi_name
echo pytensor-suite > repos-transitive/pytensor-suite/_conda_forge_name
if [ ! -d repos-transitive/python-elf ]; then git clone --depth 1 https://github.com/constantinpape/elf.git repos-transitive/python-elf ; fi
echo python-elf > repos-transitive/python-elf/_conda_forge_name
if [ ! -d repos-transitive/python-flair ]; then git clone --depth 1 https://github.com/flairNLP/flair.git repos-transitive/python-flair ; fi
echo python-flair > repos-transitive/python-flair/_conda_forge_name
if [ ! -d repos-transitive/pytorch-pretrained-bert ]; then git clone --depth 1 https://github.com/huggingface/pytorch-pretrained-BERT.git repos-transitive/pytorch-pretrained-bert ; fi
echo pytorch-pretrained-bert > repos-transitive/pytorch-pretrained-bert/_pypi_name
echo pytorch-pretrained-bert > repos-transitive/pytorch-pretrained-bert/_conda_forge_name
if [ ! -d repos-transitive/pytorch_tabular ]; then git clone --depth 1 https://github.com/manujosephv/pytorch_tabular.git repos-transitive/pytorch_tabular ; fi
echo pytorch_tabular > repos-transitive/pytorch_tabular/_pypi_name
echo pytorch_tabular > repos-transitive/pytorch_tabular/_conda_forge_name
if [ ! -d repos-transitive/qibo ]; then git clone --depth 1 https://github.com/qiboteam/qibo.git repos-transitive/qibo ; fi
echo qibo > repos-transitive/qibo/_conda_forge_name
if [ ! -d repos-transitive/ray-packages ]; then git clone --depth 1 https://github.com/ray-project/ray.git repos-transitive/ray-packages ; fi
echo ray-packages > repos-transitive/ray-packages/_conda_forge_name
if [ ! -d repos-transitive/riverrem ]; then git clone --depth 1 https://github.com/OpenTopography/RiverREM.git repos-transitive/riverrem ; fi
echo riverrem > repos-transitive/riverrem/_conda_forge_name
if [ ! -d repos-transitive/s1_frame_enumerator ]; then git clone --depth 1 https://github.com/ACCESS-Cloud-Based-InSAR/s1_frame_enumerator.git repos-transitive/s1_frame_enumerator ; fi
echo s1-frame-enumerator > repos-transitive/s1_frame_enumerator/_pypi_name
echo s1_frame_enumerator > repos-transitive/s1_frame_enumerator/_conda_forge_name
if [ ! -d repos-transitive/safe-mol ]; then git clone --depth 1 https://github.com/datamol-io/safe.git repos-transitive/safe-mol ; fi
echo safe-mol > repos-transitive/safe-mol/_pypi_name
echo safe-mol > repos-transitive/safe-mol/_conda_forge_name
if [ ! -d repos-transitive/sarpy ]; then git clone --depth 1 https://github.com/ngageoint/sarpy.git repos-transitive/sarpy ; fi
echo sarpy > repos-transitive/sarpy/_pypi_name
echo sarpy > repos-transitive/sarpy/_conda_forge_name
if [ ! -d repos-transitive/schist ]; then git clone --depth 1 https://github.com/dawe/schist.git repos-transitive/schist ; fi
echo schist > repos-transitive/schist/_conda_forge_name
if [ ! -d repos-transitive/scifireaders ]; then git clone --depth 1 https://github.com/pycroscopy/SciFiReaders.git repos-transitive/scifireaders ; fi
echo scifireaders > repos-transitive/scifireaders/_pypi_name
echo scifireaders > repos-transitive/scifireaders/_conda_forge_name
if [ ! -d repos-transitive/scikit-mobility ]; then git clone --depth 1 https://github.com/scikit-mobility/scikit-mobility.git repos-transitive/scikit-mobility ; fi
echo scikit-mobility > repos-transitive/scikit-mobility/_pypi_name
echo scikit-mobility > repos-transitive/scikit-mobility/_conda_forge_name
if [ ! -d repos-transitive/scvelo ]; then git clone --depth 1 https://github.com/theislab/scvelo.git repos-transitive/scvelo ; fi
echo scvelo > repos-transitive/scvelo/_pypi_name
echo scvelo > repos-transitive/scvelo/_conda_forge_name
if [ ! -d repos-transitive/segment-anything ]; then git clone --depth 1 https://github.com/opengeos/segment-anything.git repos-transitive/segment-anything ; fi
echo segment-anything-py > repos-transitive/segment-anything/_pypi_name
echo segment-anything > repos-transitive/segment-anything/_conda_forge_name
if [ ! -d repos-transitive/segment-anything-hq ]; then git clone --depth 1 https://github.com/SysCV/sam-hq.git repos-transitive/segment-anything-hq ; fi
echo segment-anything-hq > repos-transitive/segment-anything-hq/_pypi_name
echo segment-anything-hq > repos-transitive/segment-anything-hq/_conda_forge_name
if [ ! -d repos-transitive/setfit ]; then git clone --depth 1 https://github.com/SetFit/setfit.git repos-transitive/setfit ; fi
echo setfit > repos-transitive/setfit/_pypi_name
echo setfit > repos-transitive/setfit/_conda_forge_name
if [ ! -d repos-transitive/sisl ]; then git clone --depth 1 https://github.com/zerothi/sisl.git repos-transitive/sisl ; fi
echo sisl > repos-transitive/sisl/_conda_forge_name
if [ ! -d repos-transitive/snkit ]; then git clone --depth 1 https://github.com/tomalrussell/snkit.git repos-transitive/snkit ; fi
echo snkit > repos-transitive/snkit/_pypi_name
echo snkit > repos-transitive/snkit/_conda_forge_name
if [ ! -d repos-transitive/sorcha ]; then git clone --depth 1 https://github.com/dirac-institute/sorcha.git repos-transitive/sorcha ; fi
echo sorcha > repos-transitive/sorcha/_conda_forge_name
if [ ! -d repos-transitive/sos-pbs ]; then git clone --depth 1 https://github.com/vatlab/SOS.git repos-transitive/sos-pbs ; fi
echo sos-pbs > repos-transitive/sos-pbs/_pypi_name
echo sos-pbs > repos-transitive/sos-pbs/_conda_forge_name
if [ ! -d repos-transitive/spots-in-yeasts ]; then git clone --depth 1 https://github.com/MontpellierRessourcesImagerie/spots-in-yeasts.git repos-transitive/spots-in-yeasts ; fi
echo spots-in-yeasts > repos-transitive/spots-in-yeasts/_pypi_name
echo spots-in-yeasts > repos-transitive/spots-in-yeasts/_conda_forge_name
if [ ! -d repos-transitive/stlearn ]; then git clone --depth 1 https://github.com/BiomedicalMachineLearning/stLearn.git repos-transitive/stlearn ; fi
echo stlearn > repos-transitive/stlearn/_pypi_name
echo stlearn > repos-transitive/stlearn/_conda_forge_name
if [ ! -d repos-transitive/string2string ]; then git clone --depth 1 https://github.com/stanfordnlp/string2string.git repos-transitive/string2string ; fi
echo string2string > repos-transitive/string2string/_pypi_name
echo string2string > repos-transitive/string2string/_conda_forge_name
if [ ! -d repos-transitive/structuregraph-helpers ]; then git clone --depth 1 https://github.com/kjappelbaum/structuregraph-helpers.git repos-transitive/structuregraph-helpers ; fi
echo structuregraph-helpers > repos-transitive/structuregraph-helpers/_pypi_name
echo structuregraph-helpers > repos-transitive/structuregraph-helpers/_conda_forge_name
if [ ! -d repos-transitive/sunpy ]; then git clone --depth 1 https://github.com/sunpy/sunpy.git repos-transitive/sunpy ; fi
echo sunpy > repos-transitive/sunpy/_pypi_name
echo sunpy > repos-transitive/sunpy/_conda_forge_name
if [ ! -d repos-transitive/synthetic-data ]; then git clone --depth 1 https://github.com/capitalone/synthetic-data.git repos-transitive/synthetic-data ; fi
echo synthetic-data > repos-transitive/synthetic-data/_pypi_name
echo synthetic-data > repos-transitive/synthetic-data/_conda_forge_name
if [ ! -d repos-transitive/teachopencadd ]; then git clone --depth 1 https://github.com/volkamerlab/teachopencadd.git repos-transitive/teachopencadd ; fi
echo teachopencadd > repos-transitive/teachopencadd/_conda_forge_name
if [ ! -d repos-transitive/timm ]; then git clone --depth 1 https://github.com/rwightman/pytorch-image-models.git repos-transitive/timm ; fi
echo timm > repos-transitive/timm/_pypi_name
echo timm > repos-transitive/timm/_conda_forge_name
if [ ! -d repos-transitive/tobac ]; then git clone --depth 1 https://github.com/tobac-project/tobac.git repos-transitive/tobac ; fi
echo tobac > repos-transitive/tobac/_conda_forge_name
if [ ! -d repos-transitive/torch-fidelity ]; then git clone --depth 1 https://github.com/toshas/torch-fidelity.git repos-transitive/torch-fidelity ; fi
echo torch-fidelity > repos-transitive/torch-fidelity/_conda_forge_name
if [ ! -d repos-transitive/torch_em ]; then git clone --depth 1 https://github.com/constantinpape/torch-em.git repos-transitive/torch_em ; fi
echo torch_em > repos-transitive/torch_em/_conda_forge_name
if [ ! -d repos-transitive/torchvision ]; then git clone --depth 1 https://github.com/pytorch/vision.git repos-transitive/torchvision ; fi
echo torchvision > repos-transitive/torchvision/_conda_forge_name
if [ ! -d repos-transitive/towhee ]; then git clone --depth 1 https://github.com/towhee-io/towhee.git repos-transitive/towhee ; fi
echo towhee > repos-transitive/towhee/_conda_forge_name
if [ ! -d repos-transitive/transbigdata ]; then git clone --depth 1 https://github.com/ni1o1/transbigdata.git repos-transitive/transbigdata ; fi
echo transbigdata > repos-transitive/transbigdata/_pypi_name
echo transbigdata > repos-transitive/transbigdata/_conda_forge_name
if [ ! -d repos-transitive/tts ]; then git clone --depth 1 https://github.com/coqui-ai/TTS.git repos-transitive/tts ; fi
echo tts > repos-transitive/tts/_pypi_name
echo tts > repos-transitive/tts/_conda_forge_name
if [ ! -d repos-transitive/tvb-framework ]; then git clone --depth 1 https://github.com/the-virtual-brain/tvb-root.git repos-transitive/tvb-framework ; fi
echo tvb-framework > repos-transitive/tvb-framework/_pypi_name
echo tvb-framework > repos-transitive/tvb-framework/_conda_forge_name
if [ ! -d repos-transitive/tvb-storage ]; then git clone --depth 1 https://github.com/the-virtual-brain/tvb-root.git repos-transitive/tvb-storage ; fi
echo tvb-storage > repos-transitive/tvb-storage/_pypi_name
echo tvb-storage > repos-transitive/tvb-storage/_conda_forge_name
if [ ! -d repos-transitive/txtai ]; then git clone --depth 1 https://github.com/neuml/txtai.git repos-transitive/txtai ; fi
echo txtai > repos-transitive/txtai/_pypi_name
echo txtai > repos-transitive/txtai/_conda_forge_name
if [ ! -d repos-transitive/ufish ]; then git clone --depth 1 https://github.com/UFISH-Team/U-FISH.git repos-transitive/ufish ; fi
echo ufish > repos-transitive/ufish/_pypi_name
echo ufish > repos-transitive/ufish/_conda_forge_name
if [ ! -d repos-transitive/ultralytics ]; then git clone --depth 1 https://github.com/ultralytics/ultralytics.git repos-transitive/ultralytics ; fi
echo ultralytics > repos-transitive/ultralytics/_pypi_name
echo ultralytics > repos-transitive/ultralytics/_conda_forge_name
if [ ! -d repos-transitive/veloxchem ]; then git clone --depth 1 https://gitlab.com/veloxchem/veloxchem.git repos-transitive/veloxchem ; fi
echo veloxchem > repos-transitive/veloxchem/_conda_forge_name
if [ ! -d repos-transitive/xdem ]; then git clone --depth 1 https://github.com/GlacioHack/xdem.git repos-transitive/xdem ; fi
echo xdem > repos-transitive/xdem/_conda_forge_name
if [ ! -d repos-transitive/xraylarch ]; then git clone --depth 1 https://github.com/xraypy/xraylarch.git repos-transitive/xraylarch ; fi
echo xraylarch > repos-transitive/xraylarch/_pypi_name
echo xraylarch > repos-transitive/xraylarch/_conda_forge_name
if [ ! -d repos-transitive/xrtpy ]; then git clone --depth 1 https://github.com/HinodeXRT/xrtpy.git repos-transitive/xrtpy ; fi
echo xrtpy > repos-transitive/xrtpy/_pypi_name
echo xrtpy > repos-transitive/xrtpy/_conda_forge_name
if [ ! -d repos-transitive/xtal2png ]; then git clone --depth 1 https://github.com/sparks-baird/xtal2png.git repos-transitive/xtal2png ; fi
echo xtal2png > repos-transitive/xtal2png/_pypi_name
echo xtal2png > repos-transitive/xtal2png/_conda_forge_name
if [ ! -d repos-transitive/ydata-profiling ]; then git clone --depth 1 https://github.com/ydataai/ydata-profiling.git repos-transitive/ydata-profiling ; fi
echo ydata-profiling > repos-transitive/ydata-profiling/_pypi_name
echo ydata-profiling > repos-transitive/ydata-profiling/_conda_forge_name
