def lazy_import(module_name, submodules, submod_attrs):
    import sys
    import importlib
    import importlib.util

    all_funcs = []
    for mod, funcs in submod_attrs.items():
        all_funcs.extend(funcs)
    name_to_submod = {
        func: mod for mod, funcs in submod_attrs.items() for func in funcs
    }

    def require(fullname):
        if fullname in sys.modules:
            return sys.modules[fullname]
        spec = importlib.util.find_spec(fullname)
        try:
            module = importlib.util.module_from_spec(spec)
        except Exception:
            raise ImportError(
                "Could not lazy import module {fullname}".format(fullname=fullname)
            ) from None
        loader = importlib.util.LazyLoader(spec.loader)
        sys.modules[fullname] = module
        loader.exec_module(module)
        return module

    def __getattr__(name):
        if name in submodules:
            fullname = "{module_name}.{name}".format(module_name=module_name, name=name)
            attr = require(fullname)
        elif name in name_to_submod:
            modname = name_to_submod[name]
            module = importlib.import_module(
                "{module_name}.{modname}".format(
                    module_name=module_name, modname=modname
                )
            )
            attr = getattr(module, name)
        else:
            raise AttributeError(
                "No {module_name} attribute {name}".format(
                    module_name=module_name, name=name
                )
            )
        globals()[name] = attr
        return attr

    return __getattr__


__getattr__ = lazy_import(
    __name__,
    submodules={
        "coreviews",
        "digraph",
        "filters",
        "function",
        "graph",
        "graphviews",
        "multidigraph",
        "multigraph",
        "ordered",
        "reportviews",
        "tests",
    },
    submod_attrs={
        "coreviews": [
            "AdjacencyView",
            "AtlasView",
            "FilterAdjacency",
            "FilterAtlas",
            "FilterMultiAdjacency",
            "FilterMultiInner",
            "MultiAdjacencyView",
            "UnionAdjacency",
            "UnionAtlas",
            "UnionMultiAdjacency",
            "UnionMultiInner",
        ],
        "digraph": [
            "DiGraph",
        ],
        "filters": [
            "hide_diedges",
            "hide_edges",
            "hide_multidiedges",
            "hide_multiedges",
            "hide_nodes",
            "no_filter",
            "show_diedges",
            "show_edges",
            "show_multidiedges",
            "show_multiedges",
            "show_nodes",
        ],
        "function": [
            "add_cycle",
            "add_path",
            "add_star",
            "all_neighbors",
            "common_neighbors",
            "create_empty_copy",
            "degree",
            "degree_histogram",
            "density",
            "edge_subgraph",
            "edges",
            "freeze",
            "get_edge_attributes",
            "get_node_attributes",
            "induced_subgraph",
            "info",
            "is_directed",
            "is_empty",
            "is_frozen",
            "is_negatively_weighted",
            "is_path",
            "is_weighted",
            "neighbors",
            "nodes",
            "nodes_with_selfloops",
            "non_edges",
            "non_neighbors",
            "number_of_edges",
            "number_of_nodes",
            "number_of_selfloops",
            "path_weight",
            "restricted_view",
            "reverse_view",
            "selfloop_edges",
            "set_edge_attributes",
            "set_node_attributes",
            "subgraph",
            "subgraph_view",
            "to_directed",
            "to_undirected",
        ],
        "graph": [
            "Graph",
        ],
        "graphviews": [
            "generic_graph_view",
            "reverse_view",
            "subgraph_view",
        ],
        "multidigraph": [
            "MultiDiGraph",
        ],
        "multigraph": [
            "MultiGraph",
        ],
        "reportviews": [
            "DegreeView",
            "DiDegreeView",
            "DiMultiDegreeView",
            "EdgeDataView",
            "EdgeView",
            "InDegreeView",
            "InEdgeDataView",
            "InEdgeView",
            "InMultiDegreeView",
            "InMultiEdgeDataView",
            "InMultiEdgeView",
            "MultiDegreeView",
            "MultiEdgeDataView",
            "MultiEdgeView",
            "NodeDataView",
            "NodeView",
            "OutDegreeView",
            "OutEdgeDataView",
            "OutEdgeView",
            "OutMultiDegreeView",
            "OutMultiEdgeDataView",
            "OutMultiEdgeView",
        ],
        "tests": [
            "BaseAttrDiGraphTester",
            "BaseAttrGraphTester",
            "BaseDiGraphTester",
            "BaseGraphTester",
            "BaseMultiDiGraphTester",
            "BaseMultiGraphTester",
            "HistoricalTests",
            "TestAdjacencyView",
            "TestAtlasView",
            "TestChainsOfViews",
            "TestCommonNeighbors",
            "TestDegreeView",
            "TestDiDegreeView",
            "TestDiGraph",
            "TestDiGraphHistorical",
            "TestDiMultiDegreeView",
            "TestEdgeDataView",
            "TestEdgeSubGraph",
            "TestEdgeSubgraph",
            "TestEdgeView",
            "TestFilterFactory",
            "TestFilteredGraphs",
            "TestFunction",
            "TestGraph",
            "TestGraphHistorical",
            "TestInDegreeView",
            "TestInEdgeDataView",
            "TestInEdgeView",
            "TestInMultiDegreeView",
            "TestInMultiEdgeDataView",
            "TestInMultiEdgeView",
            "TestInducedSubGraph",
            "TestMultiAdjacencyView",
            "TestMultiDegreeView",
            "TestMultiDiGraph",
            "TestMultiDiGraphView",
            "TestMultiEdgeDataView",
            "TestMultiEdgeView",
            "TestMultiGraph",
            "TestMultiGraphView",
            "TestMultiReverseView",
            "TestNodeDataView",
            "TestNodeDataViewDefaultSetOps",
            "TestNodeDataViewSetOps",
            "TestNodeView",
            "TestNodeViewSetOps",
            "TestOrdered",
            "TestOrderedDiGraph",
            "TestOrderedFeatures",
            "TestOrderedGraph",
            "TestOrderedMultiDiGraph",
            "TestOrderedMultiGraph",
            "TestOutDegreeView",
            "TestOutEdgeDataView",
            "TestOutEdgeView",
            "TestOutMultiDegreeView",
            "TestOutMultiEdgeDataView",
            "TestOutMultiEdgeView",
            "TestReverseView",
            "TestSpecialDiGraph",
            "TestSpecialGraph",
            "TestSpecialMultiDiGraph",
            "TestSpecialMultiGraph",
            "TestSubDiGraphView",
            "TestSubGraphView",
            "TestThinDiGraph",
            "TestThinGraph",
            "TestToDirected",
            "TestToUndirected",
            "TestUnionAdjacency",
            "TestUnionAtlas",
            "TestUnionMultiAdjacency",
            "TestUnionMultiInner",
            "historical_tests",
            "test_coreviews",
            "test_digraph",
            "test_digraph_historical",
            "test_factories",
            "test_filters",
            "test_function",
            "test_generic_multitype",
            "test_get_edge_attributes",
            "test_get_node_attributes",
            "test_graph",
            "test_graph_historical",
            "test_graphviews",
            "test_is_empty",
            "test_ispath",
            "test_multidigraph",
            "test_multigraph",
            "test_multigraph_add_edges_from_four_tuple_misordered",
            "test_nodedataview_unhashable",
            "test_ordered",
            "test_pathweight",
            "test_reportviews",
            "test_restricted_view",
            "test_restricted_view_multi",
            "test_selfloop_edges_attr",
            "test_selfloop_edges_multi_with_data_and_keys",
            "test_selfloops",
            "test_selfloops_removal",
            "test_selfloops_removal_multi",
            "test_set_edge_attributes",
            "test_set_edge_attributes_ignores_extra_edges",
            "test_set_edge_attributes_multi",
            "test_set_edge_attributes_multi_ignores_extra_edges",
            "test_set_node_attributes",
            "test_set_node_attributes_ignores_extra_nodes",
            "test_slicing_reportviews",
            "test_special",
            "test_subgraphviews",
        ],
    },
)


def __dir__():
    return __all__


__all__ = [
    "AdjacencyView",
    "AtlasView",
    "BaseAttrDiGraphTester",
    "BaseAttrGraphTester",
    "BaseDiGraphTester",
    "BaseGraphTester",
    "BaseMultiDiGraphTester",
    "BaseMultiGraphTester",
    "DegreeView",
    "DiDegreeView",
    "DiGraph",
    "DiMultiDegreeView",
    "EdgeDataView",
    "EdgeView",
    "FilterAdjacency",
    "FilterAtlas",
    "FilterMultiAdjacency",
    "FilterMultiInner",
    "Graph",
    "HistoricalTests",
    "InDegreeView",
    "InEdgeDataView",
    "InEdgeView",
    "InMultiDegreeView",
    "InMultiEdgeDataView",
    "InMultiEdgeView",
    "MultiAdjacencyView",
    "MultiDegreeView",
    "MultiDiGraph",
    "MultiEdgeDataView",
    "MultiEdgeView",
    "MultiGraph",
    "NodeDataView",
    "NodeView",
    "OutDegreeView",
    "OutEdgeDataView",
    "OutEdgeView",
    "OutMultiDegreeView",
    "OutMultiEdgeDataView",
    "OutMultiEdgeView",
    "TestAdjacencyView",
    "TestAtlasView",
    "TestChainsOfViews",
    "TestCommonNeighbors",
    "TestDegreeView",
    "TestDiDegreeView",
    "TestDiGraph",
    "TestDiGraphHistorical",
    "TestDiMultiDegreeView",
    "TestEdgeDataView",
    "TestEdgeSubGraph",
    "TestEdgeSubgraph",
    "TestEdgeView",
    "TestFilterFactory",
    "TestFilteredGraphs",
    "TestFunction",
    "TestGraph",
    "TestGraphHistorical",
    "TestInDegreeView",
    "TestInEdgeDataView",
    "TestInEdgeView",
    "TestInMultiDegreeView",
    "TestInMultiEdgeDataView",
    "TestInMultiEdgeView",
    "TestInducedSubGraph",
    "TestMultiAdjacencyView",
    "TestMultiDegreeView",
    "TestMultiDiGraph",
    "TestMultiDiGraphView",
    "TestMultiEdgeDataView",
    "TestMultiEdgeView",
    "TestMultiGraph",
    "TestMultiGraphView",
    "TestMultiReverseView",
    "TestNodeDataView",
    "TestNodeDataViewDefaultSetOps",
    "TestNodeDataViewSetOps",
    "TestNodeView",
    "TestNodeViewSetOps",
    "TestOrdered",
    "TestOrderedDiGraph",
    "TestOrderedFeatures",
    "TestOrderedGraph",
    "TestOrderedMultiDiGraph",
    "TestOrderedMultiGraph",
    "TestOutDegreeView",
    "TestOutEdgeDataView",
    "TestOutEdgeView",
    "TestOutMultiDegreeView",
    "TestOutMultiEdgeDataView",
    "TestOutMultiEdgeView",
    "TestReverseView",
    "TestSpecialDiGraph",
    "TestSpecialGraph",
    "TestSpecialMultiDiGraph",
    "TestSpecialMultiGraph",
    "TestSubDiGraphView",
    "TestSubGraphView",
    "TestThinDiGraph",
    "TestThinGraph",
    "TestToDirected",
    "TestToUndirected",
    "TestUnionAdjacency",
    "TestUnionAtlas",
    "TestUnionMultiAdjacency",
    "TestUnionMultiInner",
    "UnionAdjacency",
    "UnionAtlas",
    "UnionMultiAdjacency",
    "UnionMultiInner",
    "add_cycle",
    "add_path",
    "add_star",
    "all_neighbors",
    "common_neighbors",
    "coreviews",
    "create_empty_copy",
    "degree",
    "degree_histogram",
    "density",
    "digraph",
    "edge_subgraph",
    "edges",
    "filters",
    "freeze",
    "function",
    "generic_graph_view",
    "get_edge_attributes",
    "get_node_attributes",
    "graph",
    "graphviews",
    "hide_diedges",
    "hide_edges",
    "hide_multidiedges",
    "hide_multiedges",
    "hide_nodes",
    "historical_tests",
    "induced_subgraph",
    "info",
    "is_directed",
    "is_empty",
    "is_frozen",
    "is_negatively_weighted",
    "is_path",
    "is_weighted",
    "multidigraph",
    "multigraph",
    "neighbors",
    "no_filter",
    "nodes",
    "nodes_with_selfloops",
    "non_edges",
    "non_neighbors",
    "number_of_edges",
    "number_of_nodes",
    "number_of_selfloops",
    "ordered",
    "path_weight",
    "reportviews",
    "restricted_view",
    "reverse_view",
    "selfloop_edges",
    "set_edge_attributes",
    "set_node_attributes",
    "show_diedges",
    "show_edges",
    "show_multidiedges",
    "show_multiedges",
    "show_nodes",
    "subgraph",
    "subgraph_view",
    "test_coreviews",
    "test_digraph",
    "test_digraph_historical",
    "test_factories",
    "test_filters",
    "test_function",
    "test_generic_multitype",
    "test_get_edge_attributes",
    "test_get_node_attributes",
    "test_graph",
    "test_graph_historical",
    "test_graphviews",
    "test_is_empty",
    "test_ispath",
    "test_multidigraph",
    "test_multigraph",
    "test_multigraph_add_edges_from_four_tuple_misordered",
    "test_nodedataview_unhashable",
    "test_ordered",
    "test_pathweight",
    "test_reportviews",
    "test_restricted_view",
    "test_restricted_view_multi",
    "test_selfloop_edges_attr",
    "test_selfloop_edges_multi_with_data_and_keys",
    "test_selfloops",
    "test_selfloops_removal",
    "test_selfloops_removal_multi",
    "test_set_edge_attributes",
    "test_set_edge_attributes_ignores_extra_edges",
    "test_set_edge_attributes_multi",
    "test_set_edge_attributes_multi_ignores_extra_edges",
    "test_set_node_attributes",
    "test_set_node_attributes_ignores_extra_nodes",
    "test_slicing_reportviews",
    "test_special",
    "test_subgraphviews",
    "tests",
    "to_directed",
    "to_undirected",
]
