.. This (-*- rst -*-) format file contains commonly used link targets
   and name substitutions.  It may be included in many files,
   therefore it should only contain link targets and name
   substitutions.  Try grepping for "^\.\. _" to find plausible
   candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   nipy, NIPY, Nipy, etc...

.. git internals
.. _git: http://git-scm.com/
.. _github: http://github.com
.. _github help: https://git-scm.com/docs/git
.. _github more help: https://help.github.com/articles/git-and-github-learning-resources/
.. _git svn crash course: http://git-scm.com/course/svn.html
.. _network graph visualizer: http://github.com/blog/39-say-hello-to-the-network-graph-visualizer
.. _git tutorial: https://git-scm.com/docs/gittutorial
.. _git clone: https://git-scm.com/docs/git-clone
.. _git checkout: https://git-scm.com/docs/git-checkout
.. _git commit: https://git-scm.com/docs/git-commit
.. _git push: https://git-scm.com/docs/git-push
.. _git pull: https://git-scm.com/docs/git-pull
.. _git add: https://git-scm.com/docs/git-add
.. _git status: https://git-scm.com/docs/git-status
.. _git diff: https://git-scm.com/docs/git-diff
.. _git log: https://git-scm.com/docs/git-log
.. _git branch: https://git-scm.com/docs/git-branch
.. _git remote: https://git-scm.com/docs/git-remote
.. _git rebase: https://git-scm.com/docs/git-rebase
.. _git config: https://git-scm.com/docs/git-config

.. git guides
.. _git concepts: http://www.eecs.harvard.edu/~cduan/technical/git/
.. _git magic: http://www-cs-students.stanford.edu/~blynn/gitmagic/index.html
.. _msysgit: http://code.google.com/p/msysgit/downloads/list
.. _git-osx-installer: http://code.google.com/p/git-osx-installer/downloads/list
.. _subversion: http://subversion.tigris.org/
.. _Nick Quaranto: http://www.gitready.com/
.. _Fernando Perez: http://www.fperez.org/py4science/git.html
.. _why the -a flag?: http://www.gitready.com/beginner/2009/01/18/the-staging-area.html
.. _git staging area: http://www.gitready.com/beginner/2009/01/18/the-staging-area.html
.. _tangled working copy problem: http://tomayko.com/writings/the-thing-about-git 
.. _Linus Torvalds: http://www.mail-archive.com/dri-devel@lists.sourceforge.net/msg39091.html
.. _git parable: http://tom.preston-werner.com/2009/05/19/the-git-parable.html
.. _git foundation: http://matthew-brett.github.com/pydagogue/foundation.html
.. _deleting master on github: http://matthew-brett.github.com/pydagogue/gh_delete_master.html
.. _rebase without tears: http://matthew-brett.github.com/pydagogue/rebase_without_tears.html
.. _resolving a merge: http://schacon.github.com/git/user-manual.html#resolving-a-merge
.. _ipython git workflow: http://mail.scipy.org/pipermail/ipython-dev/2010-October/006746.html

.. other stuff
.. _python: http://www.python.org

.. |emdash| unicode:: U+02014

.. vim: ft=rst
