
.. _core-developers-team:

Core Developers
---------------

NetworkX development is guided by the following core team:



.. raw:: html

   <div class="team-member">
     <a href="https://github.com/boothby" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/569654?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @boothby"
           />
        </div>
        Kelly Boothby
     </a>
     <div class="team-member-handle">@boothby</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/dschult" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/915037?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @dschult"
           />
        </div>
        Dan Schult
     </a>
     <div class="team-member-handle">@dschult</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/eriknw" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/2058401?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @eriknw"
           />
        </div>
        Erik Welch
     </a>
     <div class="team-member-handle">@eriknw</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/hagberg" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/187875?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @hagberg"
           />
        </div>
        Aric Hagberg
     </a>
     <div class="team-member-handle">@hagberg</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/jarrodmillman" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/123428?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @jarrodmillman"
           />
        </div>
        Jarrod Millman
     </a>
     <div class="team-member-handle">@jarrodmillman</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/mjschwenne" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/19698215?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @mjschwenne"
           />
        </div>
        Matt Schwennesen
     </a>
     <div class="team-member-handle">@mjschwenne</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/MridulS" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/5363860?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @MridulS"
           />
        </div>
        Mridul Seth
     </a>
     <div class="team-member-handle">@MridulS</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/rossbar" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/1268991?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @rossbar"
           />
        </div>
        Ross Barnowski
     </a>
     <div class="team-member-handle">@rossbar</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/Schefflera-Arboricola" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/91629733?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @Schefflera-Arboricola"
           />
        </div>
        Aditi Juneja
     </a>
     <div class="team-member-handle">@Schefflera-Arboricola</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/stefanv" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/45071?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @stefanv"
           />
        </div>
        Stefan van der Walt
     </a>
     <div class="team-member-handle">@stefanv</div>
   </div>

.. raw:: html

   <div class="team-member">
     <a href="https://github.com/amcandio" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/13503925?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @amcandio"
           />
        </div>
        Alejandro Candioti
     </a>
     <div class="team-member-handle">@amcandio</div>
   </div>


Emeritus Developers
-------------------

We thank these previously-active core developers for their contributions to NetworkX.



.. raw:: html

   <div class="team-member">
     <a href="https://github.com/bjedwards" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/726274?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @bjedwards"
           />
        </div>
        Benjamin Edwards
     </a>
     <div class="team-member-handle">@bjedwards</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/camillescott" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/2896301?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @camillescott"
           />
        </div>
        Camille Scott
     </a>
     <div class="team-member-handle">@camillescott</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/chebee7i" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/326005?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @chebee7i"
           />
        </div>
        @chebee7i
     </a>
     <div class="team-member-handle">@chebee7i</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/ericmjl" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/2631566?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @ericmjl"
           />
        </div>
        Eric Ma
     </a>
     <div class="team-member-handle">@ericmjl</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/harshal-dupare" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/52428908?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @harshal-dupare"
           />
        </div>
        Harshal Dupare
     </a>
     <div class="team-member-handle">@harshal-dupare</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/jfinkels" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/121755?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @jfinkels"
           />
        </div>
        @jfinkels
     </a>
     <div class="team-member-handle">@jfinkels</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/jtorrents" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/1184374?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @jtorrents"
           />
        </div>
        Jordi Torrents
     </a>
     <div class="team-member-handle">@jtorrents</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/loicseguin" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/812562?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @loicseguin"
           />
        </div>
        Loïc Séguin-Charbonneau
     </a>
     <div class="team-member-handle">@loicseguin</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/paulitapb" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/44149844?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @paulitapb"
           />
        </div>
        Paula Pérez Bianchi
     </a>
     <div class="team-member-handle">@paulitapb</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/vadyushkins" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/43042296?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @vadyushkins"
           />
        </div>
        Vadim
     </a>
     <div class="team-member-handle">@vadyushkins</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/z3y50n" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/33282622?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @z3y50n"
           />
        </div>
        Dimitrios Papageorgiou
     </a>
     <div class="team-member-handle">@z3y50n</div>
   </div>


.. _steering-council-team:

Steering Council
----------------




.. raw:: html

   <div class="team-member">
     <a href="https://github.com/boothby" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/569654?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @boothby"
           />
        </div>
        Kelly Boothby
     </a>
     <div class="team-member-handle">@boothby</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/dschult" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/915037?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @dschult"
           />
        </div>
        Dan Schult
     </a>
     <div class="team-member-handle">@dschult</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/hagberg" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/187875?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @hagberg"
           />
        </div>
        Aric Hagberg
     </a>
     <div class="team-member-handle">@hagberg</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/jarrodmillman" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/123428?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @jarrodmillman"
           />
        </div>
        Jarrod Millman
     </a>
     <div class="team-member-handle">@jarrodmillman</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/MridulS" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/5363860?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @MridulS"
           />
        </div>
        Mridul Seth
     </a>
     <div class="team-member-handle">@MridulS</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/rossbar" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/1268991?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @rossbar"
           />
        </div>
        Ross Barnowski
     </a>
     <div class="team-member-handle">@rossbar</div>
   </div>


.. raw:: html

   <div class="team-member">
     <a href="https://github.com/stefanv" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/45071?v=4&s=40"
             loading="lazy"
             alt="Avatar picture of @stefanv"
           />
        </div>
        Stefan van der Walt
     </a>
     <div class="team-member-handle">@stefanv</div>
   </div>

