### Inspired from https://github.com/scikit-image/scikit-image/blob/main/.github/workflows/benchmarks.yml

name: Benchmark PR
on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  ## This code below is to make sure a new commit on a PR with the label
  ## retriggers the benchmark, otherwise the label needs to be removed and
  ## applied again to run the benchmark.
  check:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/github-script@v9
        name: Check for benchmark label and new commit
        id: check
        with:
          script: |
            const { owner, repo, number: pull_number } = context.issue;

            // Check for label
            const { data: pullRequest } = await github.rest.pulls.get({ owner, repo, pull_number });
            if (!pullRequest.labels.some(({ name }) => name === 'run:benchmark')) {
              return false;
            }

            // Check for repo name and organization name
            const { data: repository } = await github.rest.repos.get({ owner, repo });
            return repository.name === 'networkx' && repository.owner.login === 'networkx';
  benchmark:
    needs: check
    if: ${{ needs.check.outputs.result == 'true' }}
    # if: contains(github.event.pull_request.labels.*.name, 'run:benchmark') || ${{ github.event.label.name == 'run:benchmark' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: prefix-dev/setup-pixi@v0.9.6
        with:
          environments: benchmark

      - name: Run benchmarks
        id: benchmark
        run: |
          set -euxo pipefail

          echo "Baseline:  ${{ github.event.pull_request.base.sha }} (${{ github.event.pull_request.base.label }})"
          echo "Contender: ${GITHUB_SHA} (${{ github.event.pull_request.head.label }})"

          pixi run -e benchmark benchmark-continuous \
              ${{ github.event.pull_request.base.sha }} ${GITHUB_SHA} \
              | sed "/Traceback \|failed$\|PERFORMANCE DECREASED/ s/^/::error::/" \
              | tee benchmarks/benchmarks.log

          if grep "Traceback \|failed$\|PERFORMANCE DECREASED" benchmarks/benchmarks.log > /dev/null ; then
             exit 1
          fi

      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: asv-benchmark-results-${{ runner.os }}
          path: benchmarks/benchmarks.log
