name: deploy

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  documentation:
    # Do not attempt to deploy documentation on forks
    if: github.repository_owner == 'networkx'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          environments: docs
      - name: Register graphviz plugins
        run: pixi run -e docs dot -c
      - name: Install backend stubs
        run: pixi run -e docs install-backend-stubs

      # To set up a cross-repository deploy key:
      # 1. Create a key pair:
      #   `ssh-keygen -t ed25519 -C "nx_doc_deploy_bot@nomail"`
      # 2. Add the public key to the networkx/documentation repo
      #   - Settings -> Deploy keys -> Add new
      #   - Make sure the key has write permissions
      # 3. Add private key as a secret to networkx/networkx repo
      #   - Settings -> Secrets -> New Repository Secret
      #   - Make sure the name is the same as below: CI_DEPLOY_KEY
      - name: Install SSH agent
        if: github.ref == 'refs/heads/main'
        uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: ${{ secrets.CI_DEPLOY_KEY }}

      - name: Build docs
        if: github.ref == 'refs/heads/main'
        run: pixi run -e docs docs-build

      - name: Deploy docs
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # releases/v4
        with:
          git-config-name: nx-doc-deploy-bot
          git-config-email: nx-doc-deploy-bot@nomail
          folder: doc/build/html
          repository-name: networkx/documentation
          branch: gh-pages
          target-folder: latest
          ssh-key: true
