name: Upload and build nightly wheels
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  cron:
    # Do not attempt to upload nightly through forks
    if: github.repository_owner == 'networkx'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          environments: build-release
      - name: Build a wheel and a sdist
        run: pixi run -e build-release build-dist
      - name: Verify the distribution
        run: pixi run -e build-release verify-dist
      - name: List contents of sdist
        run: pixi run -e build-release python -m tarfile --list dist/networkx-*.tar.gz
      - name: List contents of wheel
        run: pixi run -e build-release python -m zipfile --list dist/networkx-*.whl
      - name: Upload nightly wheel
        uses: scientific-python/upload-nightly-action@e76cfec8a4611fd02808a801b0ff5a7d7c1b2d99 # 0.6.4
        with:
          anaconda_nightly_upload_token: ${{ secrets.ANACONDA_NIGHTLY }}
          artifacts_path: dist/
