name: Build Wheel and Release
on:
  push:
    tags:
      - networkx-*

permissions:
  contents: read

jobs:
  pypi-publish:
    name: upload release to PyPI
    if: github.repository_owner == 'networkx' && startsWith(github.ref, 'refs/tags/networkx-') && always()
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      attestations: write
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        with:
          environments: build-release
      - name: Build wheels
        run: |
          git clean -fxd
          pixi run -e build-release build-dist
      - name: Verify the distribution
        run: pixi run -e build-release verify-dist
      - name: Generate artifact attestation for sdist and wheel
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
        with:
          subject-path: "dist/networkx-*"

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1
