name: prerelease

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [Ubuntu, macOS]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Before install
      run: |
        python3 -m venv ~/venv
        source ~/venv/bin/activate

    - name: Install packages
      run: |
        pip install --upgrade pip wheel setuptools
        pip install --pre -r requirements.txt
        pip install .
        pip list

    - name: Test NetworkX
      run: |
        pytest --doctest-modules --durations=10 --pyargs networkx
